### ISSUE TITLE
MIDI file generator is not standard compliant

### ISSUE THREAD

**Issue by zhangchn** [CoderLine/alphaTab#100]
Standard MIDI File (SMF) format requires that a meta event (FF 2F 00) for end-of-track to present at the end of every track.

AlphaTab does not add this event, and would cause problems in Core MIDI/AVFoundation players where a generated MIDI file is regarded as invalid.

**Comment by Danielku15** [comment]
Thanks for this suggestion. I added the end-of-track meta event to the midi generation.
