### ISSUE TITLE
Optimize paddings to allow more compressed music sheets

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#1001]
alphaTab currently has quite many padding definitions which cause a lot of white space across the music sheet. As part of this improvement we should: 

* Reduce the paddings in the `RenderStaff` and make it configurable.
* Add a configurable paddings to `StaveGroup`.
* Optimize effect slot assignment
* Double check the allocated sizes for all glyphs to ensure they reserve the size they actually need.

**Comment by goodgame365** [comment]
I found that many problems can be solved by setting the stretchForce less than 1
