### ISSUE TITLE
Configure option for margin / padding

### ISSUE THREAD

**Issue by tbreuss** [CoderLine/alphaTab#101]
Is it possible to define the margin and/or padding in alphaTab?

The padding on a whole sheet makes sense, but if I try to render only one line of a sheet for example, the option to define padding/margin would be nice. See the gap between the blue and red line on the attached screenshot.

![alphatab-padding](https://cloud.githubusercontent.com/assets/1334161/17642751/3c585a92-6153-11e6-9f6b-8c456fbf2b24.png)

**Comment by Danielku15** [comment]
It looks to me that you are using an old version of alphaTab. I checked your sample in the latest build which is available here on GitHub and it looks like this in case you use the `[horizontal layout](http://demo.alphatab.net/features.html#layouts)`: 
![issue101](https://cloud.githubusercontent.com/assets/674916/17707529/18c5b06c-63e1-11e6-9aca-2dc8db5c8fb5.png)

To your question: The padding is not really configurable but I the padding should be quite small for the horizontal layout (20px). If this is still too big I can make it configurable of course.

**Comment by Danielku15** [comment]
Did you check out the new version? I would like to close this issue if the new display is okay for you.
