### ISSUE TITLE
export gp7 throws exception

### ISSUE THREAD

**Issue by yibo7** [CoderLine/alphaTab#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

export gp7 throws exception “System.NullReferenceException:“Object reference not set to an instance of an object.”

The calling code is as follows
```cs
var exporter = new AlphaTab.Exporter.Gp7Exporter();
            var settings = new Settings();
            settings.Importer.Encoding = "utf-8";
            AlphaTab.Core.EcmaScript.Uint8Array data = exporter.Export(score, settings);
            ArraySegment<byte> bytes = data.Data;
            string fileName = score.Title.Length > 0 ? score.Title + ".gp" : "Untitled.gp";
            var info = new FileInfo(sPath);
            string savePath = Path.Combine(info.DirectoryName, fileName);

            using (var fs = new System.IO.FileStream(savePath, System.IO.FileMode.Create))
            {
                fs.Write(bytes.Array, bytes.Offset, bytes.Count);
            }
```

### Expected Behavior

Hope to export the gp file correctly

### Steps To Reproduce

1.select the gtp file in test-gtp-files.zip

2.call Gp7Exporter of the *.Export(score, settings)

### Found in Version

1.2

### Platform

.net (WinForms)

### Environment

```markdown
- **Windows 10**:
- **WinForm**:
- **.net 6**:
```

### Anything else?

[test-gtp-files.zip](https://github.com/CoderLine/alphaTab/files/9906164/test-gtp-files.zip)

![image](https://user-images.githubusercontent.com/58937236/199143911-15d219aa-e61a-41c8-a14a-98074c176431.png)

**Comment by Danielku15** [comment]
It's a bug related to the lyrics. They are declared as `string[] | null` (`string[]?` in .net syntax) but they are not initialized with empty strings as expected here: 

https://github.com/CoderLine/alphaTab/blob/b1c4efa37fb22c69f38b7aa07d070b29b44407f6/src/model/Track.ts#L103-L105   

Fix will be to either make the lyrics `(string|null)[] | null` (`string?[]?` in .net syntax) or fill them with empty strings there.
