### ISSUE TITLE
Publish workflow (nightly build) is broken

### ISSUE THREAD

**Issue by jonaro00** [CoderLine/alphaTab#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Syntax error in publish.yml

### Expected Behavior

Functioning workflow

### Steps To Reproduce

See the Actions tab

### Found in Version

1.3-alpha

### Platform

Other

### Environment

```markdown
Github ;)
```

### Anything else?

It's probably that two of the Kotlin steps have a `name` tag instead of `run`.

**Comment by Danielku15** [comment]
Fixed
