### ISSUE TITLE
Open files to the player

### ISSUE THREAD

**Issue by pluraldev** [CoderLine/alphaTab#108]
I am trying to implement, based on the available examples, a player that imports files to play, but I am not able to change from the initial file to the loaded ones (it is not available to listen, just for viewing), my code:

HTML: 
`<div id="alphaTab" data-file="files/somefile.gp5"></div>`

SCRIPT:

```
    // 1. Load alphaTab
    at.alphaTab(); 

    // 2. Initialize Player and Setup Player UI
    var as = at.alphaTab('playerInit'); // init alphaSynth
    ...
    function openFile(bytes) {
        try {  
            var currentScore = AlphaTab.Importer.ScoreLoader.LoadScoreFromBytes(new Uint8Array(bytes));
            at.alphaTab('renderer').Render(currentScore.Tracks[0]);

            //Shows the file but keeps the previous sound...

        } catch (e) {
            alert('Error opening the file');
            console.error(e);
        }
    }
```
`
Thanks if you can help.

**Comment by Danielku15** [comment]
Hi .
The jQuery plugin has a `load` function that also accepts TypedArrays. You should be able to use directly
```javascript
var data = new Uint8Array(bytes);
at.alphaTab('load', data);
```
I do not recommend to access the low level renderer for such operations. If you check the source code of the jQuery plugin you will see that it is only a thin wrapper around an API interface to alphaTab. 

If you have a `AlphaTab.Model.Score`object you want to display, you can also set it via `at.alphaTab('score', score)`.

**Comment by Danielku15** [comment]
I assume this problem is solved so I am closing this issue.
