### ISSUE TITLE
128th Notes and Rests

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#111]
Hi Daniel,

I was rendering some computer-generated scores using AlphaTab and some contained 128th notes and rests. After some digging around, looks like AlphaTab doesn't currently handle anything shorter than a 64th note and throws an error when trying to parse these durations. Looks like the bravura font is currently being used for display and after checking out [the documentation](http://www.smufl.org/files/smufl-0.6.pdf) it looks like the font has the capability to display 128th notes and rests.

Here's a jsfiddle of what I'm trying to render: [link](http://jsfiddle.net/02gLwn5m/15/) and below is what the measure should more or less look like (rendered using MuseScore).
![measure](https://cloud.githubusercontent.com/assets/1033190/21159437/78ae8192-c13e-11e6-898a-9fb26c5da074.png)
The JSfiddle works if you change the r.128 to two r.64.

I don't foresee this functionality taking too long to implement, but I don't know the guts of AlphaTab like you do, so you would be able to give a better estimate of the difficulty involved. I don't think we would need anything smaller than 128th as I've never really seen a 256nd note in a score before but I suppose it could happen.

Hope you're having a great December!

Cheers,
Greg

PS. I like the changes to use the new Steinberg font; everything is looking really sharp!

**Comment by Danielku15** [comment]
Hi Greg.

Thanks for this proper feature request.
Yes, 128th durations are currently not supported but should be fairly easy to implement. I expect around 5 to 6 small changes. I have some spare time over christmas time so I hope to add this feature soon.

The use of a webfont was longly needed. It improves the visuals, speeds up rendering and also allows easier adding of new elements (like now).

I will keep this issue updated.

Best Regards
Daniel

**Comment by Danielku15** [comment]
I added some new durations to alphaTab. Sadly there is no symbol for octuple whole notes in SmuFL so I had to let them out. 

Here an example tab showing all durations: https://jsfiddle.net/2mL9u7tn/
