### ISSUE TITLE
GHA publish workflow

### ISSUE THREAD

**Issue by jonaro00** [CoderLine/alphaTab#1112]
GHA publish workflow releases an alpha build every night, even when no change has happened.

Probably due to misconfiguration in `check-sha` and/or `actions/cache@v3`.

**Comment by Danielku15** [comment]
Could be that something changed with cache/v3. It complains about no files being found. I saw the sha file is written to a wrong location. Likely v2 was fine with empty folders and v3 needs files. Lets see if it helps
