### ISSUE TITLE
Playback issue in tabs with tempo changes

### ISSUE THREAD

**Issue by atolle** [CoderLine/alphaTab#113]
I first noticed this in my own implementation of AlphaTab's JS version, and initially thought that it may be something related to my implementation. However, this is also occurring in the [AlphaTab demo]( http://demo.alphatab.net/player.html). 

Songs with tempo changes are playing back incorrectly after the first tempo change in a song. See the end of the song in the link above around measure 90. I've tested this on Firefox and Chrome on multiple machines, so it appears to be a legitimate issue.

**Comment by Danielku15** [comment]
Thanks for this report. I was already hunting for this issue but I didn't realize that this is caused by tempo changes. It seems that suddenly some tracks switch their instrument to percussion which then sounds very wierd. I'll try to fix this problem.

**Comment by Danielku15** [comment]
Problem solved. I also updated the demo where you can see that it's working now.
