### ISSUE TITLE
Can't not play midi file exported by alphatab, how can i fix it ?

### ISSUE THREAD

**Issue by motniemtin** [CoderLine/alphaTab#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't not play midi file exported by alphatab, how can i fix it ?

### Expected Behavior

Can't not play midi file exported by alphatab, how can i fix it ?

### Steps To Reproduce

Can't not play midi file exported by alphatab, how can i fix it ?

### Found in Version

1.2

### Platform

Node.js

### Environment

```markdown
CentOS7
Chrome
```

### Anything else?

Can't not play midi file exported by alphatab, how can i fix it ?

**Comment by Danielku15** [comment]
Duplicate: 
- https://github.com/CoderLine/alphaTab/issues/943 
- https://github.com/CoderLine/alphaTab/discussions/1128

With the "I have searched the existing issues" checked, it is appreciated if you check if the problem is reported already.
