### ISSUE TITLE
Change Displayed Track

### ISSUE THREAD

**Issue by MarcoHansBeyer** [CoderLine/alphaTab#114]
Hello,
i love alphatab this is a very good tool to share tabs with my friends.

Now I want some dropdown menu to choose between different tracks. How can I change the displayed track programmatically? I don't found any demos with this feature in it.

Greets,
Marco

**Comment by Danielku15** [comment]
Hi. 
Yes this works quite easy using the tracks API call. Here is a full example I prepared some time ago: http://demo.alphatab.net/crm/trackselector/

**Comment by MarcoHansBeyer** [comment]
Thank you very much it helps me alot.
