### ISSUE TITLE
Count-in doesn't work when playing selected area

### ISSUE THREAD

**Issue by leocaseiro** [CoderLine/alphaTab#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When playing audio from a selected area, the count-in metronome is triggered but stops after that. No more audio and it normally crashes the app. 

### Expected Behavior

Count-in should work in the middle of a song, not just at the beginning.

### Steps To Reproduce

1. Open a file that has multiple measurements
2. select a part of a song (in the middle) such as measures 5-8
3. Enable count-in.
4. Click play

### Link to jsFiddle, CodePen, Project

https://www.alphatab.net/

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: MacOS Ventura, iOS 16.3.1
- **Browser**: Chrome 111, Safari 16.3
- **.net Version**: ?
```

### Anything else?

I can replicate it at https://www.alphatab.net/ player with any song.

**Comment by Danielku15** [comment]
Thanks for reporting. Yes, this is indeed a bug.

**Comment by leocaseiro** [comment]
Thank you for your fix!
