### ISSUE TITLE
Change track properties

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#117]
Hey,

Are there any options to adjust tracks properties on fly? I think about adjust volume or add mute tracks. Changing sound of a track would be great too. If the option already exist, could you give me a link to an example?

Thanks,
Jarek

**Comment by Danielku15** [comment]
Please notice that alphaTab and alphaSynth are 2 separate libraries. alphaSynth is a standalone midi syntheiszher, it doesn't directly care about alpahTab. The alphaSynth plugin of alphatab just does the following steps:
Whenever a file is loaded into a alphaTab data model, (Score) it is converted into a midi file. This midi file is ´played via alphaSynth in the browser.

So the workflow is: 
Load Gp3-5/GPX/MusicXML or whatever file> data model, > we generate a midi file out of this model > the playback engine (alphaSynth) loads the midi file and plays the 

Hence: If you adjust properties of the data model, this does change anything on the midi or the playback.

**Comment by Danielku15** [comment]
If you think of alphaTab as a very basic midi player, you rather ask for a feature that allows you of adjusting the volumne/balance/etc. of individiual tracks.

**Comment by Danielku15** [comment]
I understand that in the end you want to rebuild the Guitar Pro(Soundslice UI which allows you to adjust columes and instruments. But this considering this strict separation alphaTab for rendering and the adjustmend of the audioplayback you are rather asking for a alphaSynth feature to change the instrument/volume of insturments being played.

**Comment by yaras6** [comment]
Yeah, you are a bit right. Guitar Pro inspired my idea and yesterday I thought that will be great to allow of adjusting track properties. But it isn't requirement for me now. 

To sum up my question, after adjusting properties would be necessary to reload midi file and it is not covered scenario?

On the other side, I have never heard about Soundslice UI. But I saw flat.io project which is really awesome, and they had different great idea. 

To be honest before I found alphatab project I tried to use Vexflow tab, but your project is much better in my usecase and it saved me a lot of work :-)

**Comment by Danielku15** [comment]
Yes, currently adjusting track properties needs regenerating the midi. Definitly not the best approach I agree 😄. For the volume and balance it should be quite easy to add a small feature to alphaTab and alphaSynth that gives more convenience to adjusting those values. 

Changing the instrument on-the-fly is a bit more tricky. GP5 (and also alphaTab) support instrument changes at every bar. Supporting dynamic instrument changes on all bars (even adding new changes) would be technically quite complicated. At least it might cause some small flickering on the playback. 

I might give it a try on the weekend. Are there any other specific properties that you'd like to adjust?

**Comment by LeadGuitarMx** [comment]
This is an excellent idea, sometimes the guitar pro tabs have instruments with the volume very down..

The option of change the volume of instruments or mute some is good.

Like in songsterr.com you have the option of adjust the volumen, mute or solo the sound of each one.

Good luck and thank you very much Daniel for your hard work, you're awesome! : )

**Comment by yaras6** [comment]
To be honest, at this moment volume is most important for me, because sometimes some instruments are too loud or too quiet21.02.2017 18:42 Daniel <notifications@github.com> napisał(a):Yes, currently adjusting track properties needs regenerating the midi. Definitly not the best approach I agree 😄. For the volume and balance it should be quite easy to add a small feature to alphaTab and alphaSynth that gives more convenience to adjusting those values.
Changing the instrument on-the-fly is a bit more tricky. GP5 (and also alphaTab) support instrument changes at every bar. Supporting dynamic instrument changes on all bars (even adding new changes) would be technically quite complicated. At least it might cause some small flickering on the playback.
I might give it a try on the weekend. Are there any other specific properties that you'd like to adjust?

**Comment by Danielku15** [comment]
I was working on the new feature today but was not able to finish it. I needed to clean up some architectural things in the synthesizer first and this took me quite some time. But also the feature itself is already implemented. So far I added:

* Solo/Mute for individual channels
* Changing current/initial program of a channel
* Changing current/initial volume of a channel 

But there are still some things to do and test. One problem I know already is the fade-in effect. I have to find a good solution how to mix volume based effects together with an adjusted overall value.

**Comment by Danielku15** [comment]
One more sunday of development and it I made good progress. The rework of the alphaSynth API is done and working. I integrated all changes into alphaTab and updated the samples to match all changes. The result can be viewed at: http://demo.alphatab.net/player.html (notice the track selector on top where the GP typical settings can be changed). 

With this update a lot of the API changed so be sure to update your code to match the latest event and method naming. 

Changing the Instrument is not yet fully integrated.

**Comment by yaras6** [comment]
Ok, I'll try it for a while. Thanks a lot.

**Comment by yaras6** [comment]
I am trying to apply all changes. of it. After adjusting methods, most of my functionality is working. But I was wondering what is name of previous function SetPositionTick? I used this to update selected bar. Thanks in advance for support.

**Comment by Danielku15** [comment]
The old direct alphaSynth call `as.SetPositionTick` can be replaced replaced by the new alphaTab API `at.alphaTab('tickPosition', value)` call.

**Comment by yaras6** [comment]
Ok, this works fine. But another issue - previously i used track.Color.RGBA to get colors, but now this function always returns red, for each track. Previously it worked fine. Could you check it?

**Comment by Danielku15** [comment]
I added some unit tests that verify that the Track colors are read. GuitarPro 6 was not yet reading the color, so maybe you compared an earlier working GP5 with a not working GP6 file.

**Comment by yaras6** [comment]
Ok, but I don't load GP6 files.

I checked it on file which worked fine before update. Now all Color.RGBA return "#C80000". In your unit test do you have another color than #C80000? 

I debugged current ang previous version and below is example result 

**Current version**
track.ShortName
"Bas"
track.Color.RGBA
"#C80000"

**Previous version**

track.ShortName
"Bas"
track.Color.RGBA
"#FFFF00"

Thanks in advance for fast verification

**Comment by yaras6** [comment]
Additionally I saw in code - the returned color value is default value.

**Comment by Danielku15** [comment]
Here the proof that the colors work in the latest sources from the master branch: http://demo.alphatab.net/crm/colors/

**Comment by yaras6** [comment]
I copied data from your sample, and in my case it works fine. But problem resources only in this event

            at.on("alphaTab.loaded", function (e, score) {
                for (var i = 0; i < score.Tracks.length; i++) {
                    alert(score.Tracks[0].Color.RGBA);
                }
           }
Please check color issue in loaded event. Sorry, because I did not write where exactly problem is.

**Comment by yaras6** [comment]
I debbuged alphatab.js and I know where is the problem. Problem causes AlphaTab.Model.Track.CopyTo.

I have added this peace of code and started working
`dst.Color.RGBA = src.Color.RGBA`

I am not sure it is best solution, but please take care of this function in next update, because  dst.Color.Raw = src.Color.Raw not working.

**Comment by Danielku15** [comment]
Thanks for this finding, I added an appropriate fix. The RGBA value is cached upon creation for performance reasons. Since I enabled WebWorkers now by default, this problem poped up.

**Comment by yaras6** [comment]
Solo and mute works fine. Thanks. In future you may extend adjusting other track properties, but for me it is enough now.

**Comment by yaras6** [comment]
Some tracks have issue with volume - chanel are totally turn down and it is not possible to hear anything. Do you know this issue?

**Comment by yaras6** [comment]
And missed example on not working track for playing

https://tabs.ultimate-guitar.com/tab/213650

**Comment by yaras6** [comment]
Hi,

Any progress with this issue?

**Comment by yaras6** [comment]
I am asking because this problem is a bit annoying. Thanks for info.

**Comment by Danielku15** [comment]
I just had a small look into this file but could not see any particular problems on the file handling or the new feature of changing track properties. It was a general issue with the volume handling for automations/mix-table-changes (that's how Guitar Pro calls changes any changes of track properties during playback). 

I currently do not have much time for developing on alphaTab and since I am working alone on this project, expect fixes to take a bit longer than usual.

**Comment by yaras6** [comment]
Ok, thanks. May be I will try to find some time and I will see how it really works. If how suppose which functions need to be improved, please give me advise.
