### ISSUE TITLE
can not play in iOS Safari

### ISSUE THREAD

**Issue by emc2ws** [CoderLine/alphaTab#119]
Hi,
there is a problem when I run the player demo in iOS Safari .
When I click the 'Play' button, there's no response.
What should I do?
my email: myopenlab@163.com

**Comment by Danielku15** [comment]
Hi. 
The issue is known and entered here: https://github.com/CoderLine/alphaSynth/issues/4

**Comment by emc2ws** [comment]
That not works for me.
Finally,I solved this problem via https://gist.github.com/laziel/7aefabe99ee57b16081c

**Comment by Danielku15** [comment]
Thanks for this hint on solving I will check if I can integrate the same 'workaround' directly to alphaSynth.
