### ISSUE TITLE
Cannot read properties of null (reading 'innerText')

### ISSUE THREAD

**Issue by DevJett** [CoderLine/alphaTab#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following Guitar Pro file. 

[Midnight_Blues_Ballad_Guitar_Backing_Track_Jam_in_E_Minor.gp.zip](https://github.com/CoderLine/alphaTab/files/11929196/Midnight_Blues_Ballad_Guitar_Backing_Track_Jam_in_E_Minor.gp.zip)

I'm facing this error in the last beta version 

I tried this version its working `1.3.0-alpha.670` but not `1.3.0-alpha.675` or above it

It seems there is a bug in `1.3.0-alpha.675` version

```
3989.604e5a9b.js:1 [AlphaTab][ScoreLoader] Score import failed due to unexpected error:  TypeError: Cannot read properties of null (reading 'innerText')
    at St.parseBarXProperties (3989.604e5a9b.js:1:156126)
    at St.parseBar (3989.604e5a9b.js:1:152467)
    at St.parseBars (3989.604e5a9b.js:1:151697)
    at St.parseDom (3989.604e5a9b.js:1:135513)
    at St.parseXml (3989.604e5a9b.js:1:134930)
    at Lt.readScore (3989.604e5a9b.js:1:176440)
    at Js.loadScoreFromBytes (3989.604e5a9b.js:1:375559)
    at ha.load (3989.604e5a9b.js:1:402117)
    at la.load (3989.604e5a9b.js:1:354881)
    at t.onload (1df93b7f.a6818775.js:1:36045)
```

You can try in the live 1.3.0 version at https://next.alphatab.net
    
<img width="1638" alt="Screenshot 2023-07-02 at 12 14 12" src="https://github.com/CoderLine/alphaTab/assets/33762501/21f9e211-6f84-49c6-a32b-9b11f0ab287d">
    
    

### Expected Behavior

Should not return an error

### Steps To Reproduce

1. Go to  https://next.alphatab.net
2. Download & Choose this file `https://github.com/CoderLine/alphaTab/files/11929196/Midnight_Blues_Ballad_Guitar_Backing_Track_Jam_in_E_Minor.gp.zip`

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: MacOS
- **Browser**: Chrome Version 114.0.5735.133
```

**Comment by Danielku15** [comment]
It seems this problem got fixed meanwhile. Using the provided file works fine on next.alphatab.net

If the problem still occurs for you we can reopen this issue and investigate based on your inputs.
