### ISSUE TITLE
Played beat changed

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#122]
alphaTab.played-beat-changed is not fired on empty bars. Is it possible to call it when new bar began?

**Comment by Danielku15** [comment]
This was really a nasty problem I did not think of.  I added some dedicated checks to empty bars to ensure they are included in the necessary caches. This way they are considered for the cursor display and the even you refer to.  

Note that I changed the event name to alphaTab.playedBeatChanged for consistency with the other events.
