### ISSUE TITLE
https://alphatab.net/ is 500 Now

### ISSUE THREAD

**Issue by Code-Lonely** [CoderLine/alphaTab#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

open https://alphatab.net/

### Expected Behavior

normally open

### Steps To Reproduce

https://alphatab.net/

### Found in Version

Other

### Platform

Web

### Environment

```markdown
- **OS**:
- **Browser**:
- **.net Version**:
```

**Comment by Danielku15** [comment]
website is available again
