### ISSUE TITLE
The file generated by Gp7Exporter cannot show multiple tracks in Guitar Pro 8

### ISSUE THREAD

**Issue by Jeswang** [CoderLine/alphaTab#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a score conrtains multiple tracks, Guitar Pro 8 cannot open the file.

With an exported score with one track, Guitar Pro 8 cannot visualize multiple tracks.

There seems to be memory leak in Guitar Pro 8 when it deals with files without `ScoreViews` or `LayoutConfiguration`.

<img width="872" alt="image" src="https://github.com/CoderLine/alphaTab/assets/553783/2f0fff29-04fc-43cf-8369-8f4c149d31a8">

<img width="977" alt="Screenshot 2023-08-04 at 1 39 36 PM" src="https://github.com/CoderLine/alphaTab/assets/553783/d6d0f4a8-14af-4d8a-95ed-94cc353c9c87">

### Expected Behavior

The exported file should be able to add more tracks, and enable mutiple track view in Guitar Pro.

<img width="589" alt="Screenshot 2023-08-04 at 1 31 56 PM" src="https://github.com/CoderLine/alphaTab/assets/553783/c7e4b775-b702-4dff-b57a-a8bbfb508e54">

### Steps To Reproduce

You can create a file from `Guitar Pro 8` which shows multiple tracks fine, and then import and export the file. Now the file is broken.

```
const alphaTab = require("@coderline/alphatab");
const fs = require("fs");

const fileData = fs.readFileSync("Example.gp");
const settings = new alphaTab.Settings();
const score = alphaTab.importer.ScoreLoader.loadScoreFromBytes(
	new Uint8Array(fileData),
	settings
);

const exporter = new alphaTab.exporter.Gp7Exporter()
const data = exporter.export(score, settings);

fs.writeFile("Example-output.gp", data, (err) => {
	if (err) {
		console.log(err);
	} else {
		console.log('File written successfully!');
	}
});

console.log(score.title);
```
[reproduce_files.zip](https://github.com/CoderLine/alphaTab/files/12264516/reproduce_files.zip)

### Found in Version

1.3-alpha

### Platform

Node.js

### Environment

```markdown
- **OS**: macOS, 13.5 (22G74)
- Guitar Pro 8: 8.1.0 Build 48
```

**Comment by Danielku15** [comment]
Thanks for reporting this problem and the detailed analysis. It is a bit unfortunate that Guitar Pro still has some special proprietary binary files in their format. But even if it might be a bug in GP8 (which we could report) I guess it should be possible to write files which makes GP7 and 8 happy. It is a bit a gray zone with the reverse engineering of file formats but as we talk about interopability here it should be fine. Maybe Arobas would be even willing to share some insights about their format like they did in the old days with publishing the GP4 file format description.

**Comment by Danielku15** [comment]
Intermediate findings: The problem seems to be in the `PartConfiguration` the `LayoutConfiguration` seems optional and not making a difference (e.g. when deleting the file in the GP-zip). But it seems the way we generate the `PartConfiguration` is rather wrong compared to what GP8 is doing. Will have to do some deeper reverse engineering there because the file is mandatory. But if we write it wrong that's not good.

**Comment by Danielku15** [comment]
Problems identified and fixed.

**Comment by Jeswang** [comment]
Thanks for the quick responses! Now I can open a multi-track score from the generator (with the new change, it's by default rendering one track)! But I think it still have the same issue when clicking the button to "Switch single track / multitrack". 

<img width="452" alt="Screenshot 2023-08-07 at 8 04 53 AM" src="https://github.com/CoderLine/alphaTab/assets/553783/54455fa7-5880-4bbe-ac14-122c6d662462">

[reproduce.zip](https://github.com/CoderLine/alphaTab/files/12281667/reproduce.zip)

**Comment by Danielku15** [comment]
@Jeswang Do you still experience a bug? I opened your provided example files and it works fine for me with Guitar Pro 8 (8.1.0 Build 48) on Windows. I see you are on a Mac. 

I re-created your testfile with GP8 on windows and sent it through alphaTab to export it and also it works fine. Can you try following two files on your environment and check what happens? 
[multi-track-win.zip](https://github.com/CoderLine/alphaTab/files/13762362/multi-track-win.zip)

**Comment by Jeswang** [comment]
Yep, confirmed that Guitar Pro 8 still cannot render mutlipe tracks with the files attached in the above comment.

<img width="372" alt="image" src="https://github.com/CoderLine/alphaTab/assets/553783/3066e3e4-10fe-4f39-8cf2-d9ab292cd3d9">

**Comment by Danielku15** [comment]
@Jeswang Do I understand you correctly that you also get an error when you try to open `multi-track-win.zip/Example.gp`? Or does it only happen with `multi-track-win.zip/Example-output.gp`?

Example.gp has been created with Guitar Pro 8 and was not touched by alphaTab at all. This would mean Guitar Pro 8 has a bug and we cannot do much from our side.

**Comment by Danielku15** [comment]
Ping @Jeswang any feedback on my last question?

**Comment by Jeswang** [comment]
Sorry for the slow response.



> @Jeswang Do I understand you correctly that you also get an error when you try to open `multi-track-win.zip/Example.gp`? Or does it only happen with `multi-track-win.zip/Example-output.gp`?
> 

I can open `multi-track-win.zip/Example.gp` fine without any error when showing multiple tracks, and only encounter issues with `multi-track-win.zip/Example-output.gp`.

> Example.gp has been created with Guitar Pro 8 and was not touched by alphaTab at all. This would mean Guitar Pro 8 has a bug and we cannot do much from our side.

**Comment by Danielku15** [comment]
@Jeswang: I double checked now many things again and I cannot reporduce the problem with Guitar Pro 8.1.1 Build 17. I took the files from [reproduce.zip](https://github.com/CoderLine/alphaTab/files/12281667/reproduce.zip) and [multi-track-win.zip](https://github.com/CoderLine/alphaTab/files/13762362/multi-track-win.zip) but I can open all files and switch tracks without problems. 


https://github.com/CoderLine/alphaTab/assets/674916/42325af6-ab28-4e0f-bfee-f2af044d4d6b


From the screenshot I realized that there might be something else important: The example files have two tracks one with an empty name and one with "Stell Guitar" but in your screenshot you have two empty strings and one track is muted. 

Are there more details you can share about your environment? I tested on macOS Sonoma using the files we have shared until now.

**Comment by Danielku15** [comment]
Closing this bug as it is not reproducible for me. Tested the same files under the same Reported version and everything is find. If you have more input on how to reproduce this let me know.

**Comment by chenkigba** [comment]
Hi there.

Same Issue with me.

AlphaTab with GP7exporter to .gp

Import to GuitarPro8

Try to switch to multi-track view, then MEMORY leak! Boom

I tested creat a multi track file within gp8, then open it, switch. Works fine.

**Comment by chenkigba** [comment]
Hi, everybody. I just use gpt5.5 xhigh /goal to fix this problem.

I manually tested it, fixed.

Here is the Root Cause Analysis by gpt.

I will fork and post a PR for this.

## Root Cause

  The GPIF top-level <Score> section exported by alphaTab 1.8.4 contains XML shapes that Guitar Pro 8 does not
  handle reliably when switching to multitrack view.

  A typical failing file contains:
```
  <Score>
    <Title><![CDATA[probe minimal builder chord note]]></Title>
    <SubTitle><![CDATA[]]></SubTitle>
    <Artist><![CDATA[]]></Artist>
    ...
    <ScoreSystemsDefaultLayout><![CDATA[3]]></ScoreSystemsDefaultLayout>
    <ScoreSystemsLayout><![CDATA[1]]></ScoreSystemsLayout>
    <ScoreZoomPolicy>Value</ScoreZoomPolicy>
    <ScoreZoom>1</ScoreZoom>
    <MultiVoice>1></MultiVoice>
  </Score>
```

  A Guitar Pro-style file that can switch to multitrack view normally uses this shape instead:
```
  <Score>
    <Title>guitarish</Title>
    <SubTitle />
    <Artist />
    ...
    <ScoreSystemsDefaultLayout>3</ScoreSystemsDefaultLayout>
    <ScoreSystemsLayout />
    <ScoreZoomPolicy>Value</ScoreZoomPolicy>
    <ScoreZoom>1</ScoreZoom>
    <MultiVoice>0</MultiVoice>
  </Score>
```
  The key differences are:

  - Empty string fields are serialized as <![CDATA[]]>, while native Guitar Pro files tend to use empty elements
    such as <Artist />.

  - ScoreSystemsDefaultLayout and ScoreSystemsLayout are wrapped in CDATA.
  - ScoreSystemsLayout is pre-populated with a layout value such as 1.
  - MultiVoice contains an invalid-looking value: <MultiVoice>1></MultiVoice>.

  Guitar Pro 8 can tolerate these fields when opening the file, but switching to multitrack view appears to
  trigger unstable parsing behavior and causes abnormal memory growth.

**Comment by Jeswang** [comment]
thanks for looking into this!
