### ISSUE TITLE
Score playback is currently broken

### ISSUE THREAD

**Issue by BenTalagan** [CoderLine/alphaTab#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The player does not play the score when using the play button.

### Expected Behavior

The player should play the score when using the play button.

### Steps To Reproduce

1. Go to the official site (main page, with the canon rock score open)
2. Select stable version (1.2.3)
3. Click play, the score is played normally.
4. Select next version (1.3.0-alpha-726)
5. Click play, the score does not play (no sound, no cursor movement).

### Link to jsFiddle, CodePen, Project

[Alphatab current](https://alphatab.net)
[Alphatab next](https://next.alphatab.net)

### Found in Version

1.3-alpha (since 724)

### Platform

Web

### Environment

```markdown
- **OS**: MacOS
- **Browser**: Vivaldi / Firefox
```

### Anything else?

I tried to quickly locate when it started to happen using the releases available on jsdeliver ; this is very recent. Version 1.3.0-alpha-719 does not have the problem, whereas 724 does not behave correctly.

**Comment by BenTalagan** [comment]
Update : build 727 seems to fix the problem. (I have tested build 726 and it has also the problem).

**Comment by Danielku15** [comment]
b380147096bfe69dfe66d4ec8fe41d787d981fe5 fixed the problem.
