### ISSUE TITLE
C# controls do not support the AutoSize feature

### ISSUE THREAD

**Issue by LYH8112** [CoderLine/alphaTab#127]
Open gp5 file,  throw exception.  when call RecreateImage, the _width = -1. 
private void RecreateImage()
{
            var newImage = new Bitmap((int)_width, (int)_height, PixelFormat.Format32bppArgb);
            var newGraphics = Graphics.FromImage(newImage);
            newGraphics.SmoothingMode = SmoothingMode.HighQuality;
            newGraphics.TextRenderingHint = TextRenderingHint.AntiAlias;
            newGraphics.Clear(GdiColor.Transparent);

            if (_graphics != null)
                _graphics.Dispose();

            _image = newImage;
            _graphics = newGraphics;
}

**Comment by Danielku15** [comment]
I was lately too much focusing on the JavaScript target without checking the C# target. I added a small fix which sizes alphaTab to 970px for the demos. I will convert this issue to cover the auto-sizing support for the C# controls.

**Comment by Danielku15** [comment]
The JavaScript version supports dynamic resizing nicely whereas the C# controls only support static widths. Also the C# controls should be able to listen to the resize events and rerender the music sheet accordingly.

**Comment by Danielku15** [comment]
The GDI and WPF controls are now also responsive 
https://twitter.com/alphaTabMusic/status/854746806193934337
