### ISSUE TITLE
Play in loop

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#128]
Please think about an API function which give possibility to play few bars in infinity loop.

**Comment by Danielku15** [comment]
Theoretically this is already able today. Users can already visually select a certain range of the music sheet by drag and drop. Programmatic control over the played bar is a bit tricky. The API provides a way of setting the start and end position in midi ticks:

```javascript
at.alphaTab('playbackRange', { StartTick: 100, EndTick: 3000 });
```

An API for specifying the bars would be nice, I will add it in future. 

For the looping you could simply listen for the `alphaTab.finished` event and call `at.alphaTab('play')` again if you have looping enabled from your UI. I will consider a setting for the player which adds the looping, would be easier to enable/disable looping within the player. Also a special event would be nice to highlight that playback was restarted automatically. 

I assume one of the next questions will be that you can also vary the playback speed with every loop, but this really needs to be done via the existing/upcoming APIs. I don't think I will add something like a speed trainer directly as API.

**Comment by Danielku15** [comment]
A new option for enabling the looping is now available.
