### ISSUE TITLE
When enableAnimatedBeatCursor=false, some section pointers may skip some notes

### ISSUE THREAD

**Issue by Code-Lonely** [CoderLine/alphaTab#1281]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I set enableAnimatedBeatCursor to false，Playing normally to the fourth section of a. gp file, the cursor will skip some notes.
I am currently using version 1.2.3, and I have found that this situation does not occur in version 1.2.1

### Expected Behavior

The cursor should pass through all notes

### Steps To Reproduce

```html
<style>
        .at-wrap {
            width: 80vw;
            height: 80vh;
            margin: 0 auto;
            border: 1px solid rgba(0, 0, 0, 0.12);
            display: flex;
            flex-direction: column;
            overflow: hidden;
            position: relative;
        }
        .at-content {
            position: relative;
            overflow: hidden;
            flex: 1 1 auto;
        }
        .at-viewport {
            overflow-y: auto;
            position: absolute;
            top: 0;
            left: 70px;
            right: 0;
            bottom: 0;
            padding-right: 20px;
        }
        .at-cursor-beat {
            /* Defines the beat cursor */
            background: rgba(64, 64, 255, 0.75);
            width: 3px;
            /*background-color: rgba(6, 191, 253, 0.56);*/
        }
        .at-cursor-bar {
            /* Defines the color of the bar background when a bar is played */
            background: rgba(255, 242, 0, 0.25);
        }
        .at-selection div {
            /* Defines the color of the selection background */
            background: rgba(64, 64, 255, 0.1);
        }
    </style>
<div class="at-main"></div>
```

``` js
let scoreElement = document.querySelector(".at-main");
        const settings = {
            file: "123.gp",
            // tracks: [0],
            // tracks: [4],
            fontDirectory: 'font/',
            tracks: 'all',
            display: {
                layoutMode: 0,
                stretchForce: 1.5,
                staveProfile: 3,
                scale: 1.0
            },
            player: {
                // bufferTimeInMilliseconds: 1000,
                enablePlayer: true,
                enableCursor: true,
                enableElementHighlighting: true,
                enableAnimatedBeatCursor: false,
                soundFont: 'https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/soundfont/sonivox.sf2',
                // soundFont: 'sonivox2.sf2',
                // scrollElement: document.querySelector(".at-viewport")
            }
        }
        const api = new alphaTab.AlphaTabApi(scoreElement, settings);
        api.isLooping = true
        api.playerReady.on(() => {
            console.log("playerReady====", api.score.tracks)
            api.play();
        });
```

### Found in Version

Other

### Platform

Web

### Environment

```markdown
- **OS**:Macos
- **Browser**:Chrome 117.0.5938.149
- **alphaTab Version**: 1.2.3
```

**Comment by Code-Lonely** [comment]
[123.gp.zip](https://github.com/CoderLine/alphaTab/files/12888366/123.gp.zip)
This is my file

**Comment by Code-Lonely** [comment]
https://github.com/CoderLine/alphaTab/assets/60993027/291c04a4-44ed-4ec2-9958-92fb77532af9

**Comment by Danielku15** [comment]
Thanks for reporting this. I will look into this soon. Have you checked already if this problem still occurs in 1.3? I remember touching the area around the cursor placement.

**Comment by Code-Lonely** [comment]
Yes, I have checked and the issue also exists on 1.3.0

**Comment by Code-Lonely** [comment]
Could you please repair it as soon as possible

**Comment by Code-Lonely** [comment]
@Danielku15

**Comment by Code-Lonely** [comment]
@Danielku15 Hello, may I ask when you can fix this bug? Thank you very much

**Comment by Danielku15** [comment]
I will write here when I had time to start on this bug and fixed it, no commitments. It's done when it's done.

**Comment by Danielku15** [comment]
The problem seems more general, the enableAnimatedBeatCursor  just makes it more visible that the cursor movement and element highlgihting is not really accurate. 

I minimized the file to show the problem on a small scale. Also on a single-track display we can clearly see that the highlighting is wrong. Also the grace notes are not the cause.  

https://github.com/CoderLine/alphaTab/assets/674916/ece07c36-554a-4d1b-9d48-9a3342f1d871

Seems the MidiTickLookup is handling some aspects wrong on the `findBeatFast` path. When only using `findBeatSlow` beats are updated correctly. Just sometimes the cursor jumps back to the grace notes hinting potentially to some miscalculations on there too. 

[123-small.zip](https://github.com/CoderLine/alphaTab/files/13762392/123-small.zip)
