### ISSUE TITLE
Odd cursor movement when playing repeat-close.gp5

### ISSUE THREAD

**Issue by UlfLTheander** [CoderLine/alphaTab#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Alphatab.Samples.Wpf from alphaTabSamplesDotNet-main.zip playing repeat_close.gp5 gets following odd behavor of the cursor movement and more odd is that when the music is finished the cursor still moves.
Can you look into this?

![Screenshot 2023-10-29 145037](https://github.com/CoderLine/alphaTab/assets/115479640/bf3fac95-2b61-4197-ad36-4cc88cd5cc27)

https://github.com/CoderLine/alphaTab/assets/115479640/80cef94a-41a1-40ec-8167-c22db4580b3f

### Expected Behavior

Cursor movement in sync with music

### Steps To Reproduce

see bitmap and video capture 

### Found in Version

1.3-alpha

### Platform

.net (WPF)

### Environment

```markdown
- Win 11
- desktop
- .net 6.0
```

**Comment by Danielku15** [comment]
Looks like a legit problem. You might want to try using 1.2 if this is a blocking problem. The samples are using the latest 1.3 pre-release builds.

**Comment by UlfLTheander** [comment]
Have tested with 1.2, same problem.
Can you test on your pc if it gives the same problem.
