### ISSUE TITLE
vite build does not work with alphaTab's worker

### ISSUE THREAD

**Issue by fheyen** [CoderLine/alphaTab#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm importing alphaTab as a node module in a svelte/vite project ().

While the developing mode works fine, building leads to the following error:

```
Unexpected early exit. This happens when Promises returned by plugins cannot resolve. 
Unfinished hook action(s) on exit:
(vite:worker-import-meta-url) transform "[...]/visual-guitar-tab-comparison/visual-guitar-tab-comparison/node_modules/@coderline/alphatab/dist/alphaTab.mjs"
error during build:
Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. 
Unfinished hook action(s) on exit:
(vite:worker-import-meta-url) transform "[...]/visual-guitar-tab-comparison/visual-guitar-tab-comparison/node_modules/@coderline/alphatab/dist/alphaTab.mjs"
    at process.handleBeforeExit (file:///[...]/visual-guitar-tab-comparison/visual-guitar-tab-comparison/node_modules/rollup/dist/es/shared/node-entry.js:25902:28)
    at Object.onceWrapper (node:events:629:26)
    at process.emit (node:events:514:28)
```

I suspect this happens because the worker file is not imported in the way that rollup expects it to be.

I created a minimal example.

### Expected Behavior

vite build works without error

### Steps To Reproduce

1. Check out https://github.com/visvar/visual-guitar-tab-comparison
2. cd build-reproduce
3. npm install
4. npm run build

### Link to jsFiddle, CodePen, Project

https://github.com/visvar/visual-guitar-tab-comparison

### Found in Version

1.3-alpha

### Platform

Node.js

### Environment

```markdown
- **OS**: Windows 10
- **Node**: 20.8.1
- **vite**: 4.5.0
```

**Comment by Danielku15** [comment]
You will have to check how to configure rollup in your project. 

https://www.alphatab.net/docs/getting-started/installation-web#bundling
https://www.alphatab.net/docs/reference/settings/core/scriptfile/

https://github.com/CoderLine/alphaTab/issues/759
https://github.com/CoderLine/alphaTab/issues/699
https://github.com/CoderLine/alphaTab/issues/662

Closing as duplicate.
