### ISSUE TITLE
Loading tab in new chrome

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#130]
Hi,

Thanks in advance for help, because issue is very urgent in my opinion.

Many of tabs stopped working on new chrome browser (57.0.2987.110 (64-bit)).  Tabs is no rendered because alphatab.js throw exception. In previous version all worked fine.

![image](https://cloud.githubusercontent.com/assets/25822217/24298637/e7455e98-10a6-11e7-93b0-7ac3369ea546.png)

Here is an example:
https://tabs.ultimate-guitar.com/g/guns_n_roses/sweet_child_o_mine_guitar_pro.htm

**Comment by Danielku15** [comment]
Hi. 
Problem solved. Looks like they broke some code in the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) used for workers. This algorithm is supposed to handle cyclic references. Anyhow I prevent this cyclic references via a custom JSON serialization. This serialization had a small bug which is fixed now.

**Comment by yaras6** [comment]
Thanks a lot
