### ISSUE TITLE
Sample/PngDump crashes on rendering PNG

### ISSUE THREAD

**Issue by tumbleweed-t** [CoderLine/alphaTab#134]
# Your environment

* Version used: (master branch)
* Platform used: C#
* Rendering engine used: GDI
* Operating System and version (desktop or mobile): Windows 7

# Expected Results

I was expecting it to generate a PNG with the partition drawn 

# Observed Results

http://puu.sh/vojJn/d71980d44b.png

# Steps to Reproduce (for bugs)

1. just run it from cmd line, passing one parameter : the gpx file path

# Possible Solution 

It says "parameter is not valid"...

**Comment by Danielku15** [comment]
Thanks for this finding, I forgot to update some of the samples to specify the rendering width after the responsive rendering was introduced.

**Comment by tumbleweed-t** [comment]
Thanks for the quick fix !
Please take that star :+1:

**Comment by Danielku15** [comment]
You're welcome 😉  And thanks for the ⭐️ .
