### ISSUE TITLE
Layout question

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#135]
I need to customize layout of tab. Is there a way to remove tuning info and track name?

![image](https://cloud.githubusercontent.com/assets/25822217/26296506/3d303e12-3ecf-11e7-9f3c-40a852e25557.png)

**Comment by Danielku15** [comment]
No currently there is no option to hide this information. But should be an easy thing to extend.

**Comment by Danielku15** [comment]
I added the requested features. There are 2 new layout settings `hideTuning` and `hideTrackNames` which can be set via the additionalSettings or the newly available data attributes. 

Here an example how to use it: 
https://jsfiddle.net/danielku15/jo64pgLp/

The data attributes are typically easier to use than building the full settings object. The `start` and `count` settings can be ignored, I added them to keep the rendered music sheet small.
