### ISSUE TITLE
When the beginning of a bar is two connected grace notes, the playback cursor gets stuck and cannot move forward normally.

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#1355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after update the committed 1347 (https://github.com/CoderLine/alphaTab/commit/af75ecb9e95788bcc09b2aaa0aa00c4e7c613057)

When the beginning of a bar is two connected grace notes, the playback cursor gets stuck and cannot move forward normally.
![未标题-1](https://github.com/CoderLine/alphaTab/assets/17884664/40ca8078-9d5e-422b-9e49-2a9eef59a300)

happen in the 21- 22 bars
 
[t6.zip](https://github.com/CoderLine/alphaTab/files/14053899/t6.zip)

https://github.com/CoderLine/alphaTab/assets/17884664/41d5ee73-a8b7-43bd-a2a8-049888910ef5

 

err    at the 30 bar

![未标题-2](https://github.com/CoderLine/alphaTab/assets/17884664/b2098aa2-28db-4f1f-8fba-c65271c4b380)

[t3.zip](https://github.com/CoderLine/alphaTab/files/14052641/t3.zip)

https://github.com/CoderLine/alphaTab/assets/17884664/085ee32d-93b1-48bb-a952-ee7e51655ff2

### Expected Behavior

I think this should be a bug

### Steps To Reproduce

open the t.gp

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**:
- **Browser**:
- **.net Version**:
```

**Comment by goodgame365** [comment]
However, the playback of the same bars is normal.
[t4.zip](https://github.com/CoderLine/alphaTab/files/14052832/t4.zip)

https://github.com/CoderLine/alphaTab/assets/17884664/94656dda-ca9e-4b7f-8f02-edf5b54cc959

**Comment by goodgame365** [comment]
I noticed in the src/midi/MidiTickLookup.ts page, within the addBeat method, the line currentMasterBar.previousMasterBar!.addBeat(beat, previousStart, previousStart, currentMasterBar.previousMasterBar!.end - previousStart); has the second and third parameters being the same. I'm not sure if this is a typo. I tried replacing the third parameter with previousEnd, and it seemed to solve the problem, so the code changed to: currentMasterBar.previousMasterBar!.addBeat(beat, previousStart, previousEnd, currentMasterBar.previousMasterBar!.end - previousStart);. However, I'm not certain if this is correct, as I'm still unclear about the mechanism of addBeat

**Comment by Danielku15** [comment]
The co

> I noticed in the src/midi/MidiTickLookup.ts page, within the addBeat method, the line
> 
> `currentMasterBar.previousMasterBar!.addBeat(beat, previousStart, previousStart, currentMasterBar.previousMasterBar!.end - previousStart);`
> 
> has the second and third parameters being the same. I'm not sure if this is a typo. I tried replacing the third parameter with previousEnd, and it seemed to solve the problem, so the code changed to:
> 
> `currentMasterBar.previousMasterBar!.addBeat(beat, previousStart, previousEnd, currentMasterBar.previousMasterBar!.end - previousStart);`
> 
> . However, I'm not certain if this is correct, as I'm still unclear about the mechanism of addBeat

The parameters are correct like this. They are both "start" markers: https://github.com/CoderLine/alphaTab/blob/develop/src/midi/MasterBarTickLookup.ts#L106

But I can confirm the problem from my side. have to dig deeper there. Grace Notes are always a pain.
