### ISSUE TITLE
Can't render only the tablature (or only the partition)

### ISSUE THREAD

**Issue by tumbleweed-t** [CoderLine/alphaTab#136]
Hello,

Using ScoreRenderer, is there a way to completely remove the partition, and show only the tablature ? and vice-versa ?

Thank you man, it's truely great work.

**Comment by Danielku15** [comment]
Hi. 
Simply set the `staves` property of the settings: https://jsfiddle.net/danielku15/hkqrpjtx/
And please use the issue template next time. It is there for reason.

**Comment by tumbleweed-t** [comment]
* Version used: (master branch)
* Platform used: C#
* Rendering engine used: SVG (default), GDI
* Operating System and version (desktop or mobile): Win 7

I've tried to tamper the staves settings (Settings.Staves) But can't manage not to render the tab or the score

**Comment by tumbleweed-t** [comment]
Oh nevermind, found it  : Settings.Staved.Id 

Thank you !
