### ISSUE TITLE
Reading track issue after update

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#137]
Hey,

I tried to update my alphaTab scripts, but unfortunately many tabs stoped working, so I made rollback. Could you fix that? Thanks in advance. You can download example from my site:
http://tuneguitar.net/pl/Player/DownloadSong?Type=1&SongId=8

Object {message: "e.get_Message is not a function", stack: "TypeError: e.get_Message is not a function↵    at …alhost:3215/Scripts/alphaTab/AlphaTab.js?1:83:29)"}
message
:
"e.get_Message is not a function"
stack
:
"TypeError: e.get_Message is not a function↵    at Function.AlphaTab.Importer.ScoreLoader.LoadScoreFromBytes (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:422:110)↵    at AlphaTab.Platform.JavaScript.JsWorker.Load (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:1133:64)↵    at AlphaTab.Platform.JavaScript.JsWorker.HandleMessage (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:1083:22)↵    at delegate (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:83:29)"
__proto__
:
Object

**Comment by Danielku15** [comment]
Sorry but I will stop responding to issues which do not follow the issue template provided when creating new issues.
