### ISSUE TITLE
Loading files issue

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#138]
# Your environment

* Version used: master branch
* Platform used: JavaScript or C#
* Rendering engine used: SVG (default),
* Browser Name and Version: 58.0.3029.110
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: http://tuneguitar.net/

# Expected Results

Load properly tabs, which worked in previous version.

# Observed Results

In newest version some tabs don't load properly. In earlier version worked fine.

Object {message: "e.get_Message is not a function", stack: "TypeError: e.get_Message is not a function↵ at …alhost:3215/Scripts/alphaTab/AlphaTab.js?1:83:29)"}
message
:
"e.get_Message is not a function"
stack
:
"TypeError: e.get_Message is not a function↵ at Function.AlphaTab.Importer.ScoreLoader.LoadScoreFromBytes (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:422:110)↵ at AlphaTab.Platform.JavaScript.JsWorker.Load (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:1133:64)↵ at AlphaTab.Platform.JavaScript.JsWorker.HandleMessage (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:1083:22)↵ at delegate (http://localhost:3215/Scripts/alphaTab/AlphaTab.js?1:83:29)"
proto
:
Object

# Steps to Reproduce (for bugs)

Explain here the exact steps how to reproduce the problem. Try to provide a
running sample showing the issue. If you have problem with a dedicated input file, 
please provide a download link or attach it to the issue. 
 
1. Please download gp file. http://tuneguitar.net/pl/Player?songId=8&type=1
2. `<div class="alphaTab" data-file="Black Sabbath - Iron Man.gp5"></div>`
3.  $(".alphaTab").alphaTab();

**Comment by Danielku15** [comment]
Thanks for the report, problem is fixed with the latest commit.
