### ISSUE TITLE
Not an issue,but very choppy

### ISSUE THREAD

**Issue by comarius** [CoderLine/alphaTab#140]
# Your environment Linux Ubuntu Firefox / crome / any

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default). 
* Browser Name and Version: Firefox Ubuntu 16. / any browser
* Operating System Ubuntu, windows android
* ghitar.com
Very slow, choppy, looses tempo towards end.
At hints where to tweak, or rewrite. Songster/ultimate qut works fine.
I would need some code insights to optimize it. It looks over designed, too many timers and callbacks
Thank you

# Expected Results

Explain here what is your expected behavior of alphaTab. 

# Observed Results

Explain here how alphaTab is behaving currently. 

# Steps to Reproduce (for bugs)

Explain here the exact steps how to reproduce the problem. Try to provide a
running sample showing the issue. If you have problem with a dedicated input file, 
please provide a download link or attach it to the issue. 
 
1. 
2. 
3.  

# Possible Solution 
If you already know a solution to the problem please provide it here.

**Comment by Danielku15** [comment]
Please fill out the issue template properly, I am not responding to improperly reported topics.
