### ISSUE TITLE
Player: "cursorOptions" API call breaks the cursor animation

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#145]
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome Version 59.0.3071.115 
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

Cursor animation should work after a cursor options change.

# Observed Results

The animation doesn't work because the `beatCursor` and `barCursor` members of the `cursorOptions` object are missing. So the animation callback raise exceptions when using these objects:

![](https://image.noelshack.com/fichiers/2017/28/5/1500050070-cursoroptionsexception.png)

# Steps to Reproduce (for bugs)

1. Checkout the master branch
2. Run the player sample
3. In the navigator console, type `at.alphaTab("cursorOptions",{scrollSpeed:200})`
4. Click play

# Possible Solution 

What i've done is using the code before this commit : https://github.com/CoderLine/alphaTab/commit/7df0206c9a3566331d859f259cd114e55937fec6

**Comment by Danielku15** [comment]
I reworked the way how the alphaSynth plugin stores its details, changing the options has no now impact on the cursor elements anymore.
