### ISSUE TITLE
[BUG] Color type prompt in RenderingResources has error

### ISSUE THREAD

**Issue by Barba828** [CoderLine/alphaTab#1463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 It works if I write this, but typescript will report an error because the colorValue is actually a `string`, but mainGlyphColor can only accept the type `Color`, and src/model/Color.ts is not exported.
```ts
display:{
  resources:{
      mainGlyphColor: "#f00",
      staffLineColor: "rgb(255, 0, 0)",
  } as RenderingResources
}
```

### Expected Behavior

can use `string`

### Steps To Reproduce

1. use ts

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**:
- **Browser**:
- **.net Version**:
```

**Comment by Danielku15** [comment]
There a few bits to this issue. Its not a bug but everything is as intended. Here some clarifications: 

1. The use of plain objects might lead to errors. You can "fill" the settings object from a JSON alike object via `settings.fillFromJson` See here: 

![image](https://github.com/CoderLine/alphaTab/assets/674916/aa2794f9-fdb5-4610-8012-67c0e1626034)
https://www.alphatab.net/docs/reference/settings

2. AlphaTab exports all objects through the main module via nested namespaces/objects. 
```ts
// full import with namespace access
import * as alphaTab from '@coderline/alphatab';
const c = new alphaTab.model.Color(255, 0, 0);

// import model
import { model } from '@coderline/alphatab';
const c = new model.Color(255, 0, 0);
```

Hope this helps.
