### ISSUE TITLE
Cursor animation broken on firefox

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#147]
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 54.0.1 (32 bits)
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

When the player is paused, the cursor should stay still.

# Observed Results

The cursor keep moving oddly.

# Steps to Reproduce (for bugs)

1. Open [the player demo](https://demo.alphatab.net/player.html) in Firefox
2. Play
3. Pause

**Comment by Danielku15** [comment]
Firefox has some nasty misbehavior in the WebAudio. For Chrome it's enough to disconnect the ScriptProcessorNode from the output and it stops generating samples. But on Firefox it continues. Disconnecting also the source from the ScriptProcessorNode seems to solve the problem. New version of alphaSynth is available.

**Comment by j4kim** [comment]
Cool!
Really sorry to tell you that, but it seems like now the auto scrolling is broken (again? https://github.com/CoderLine/alphaTab/issues/84) on firefox :smile:

**Comment by Danielku15** [comment]
Firefox is really becoming a nightmare, they are changing many behavior so often and almost never they reach the proper behavior of Chrome. Even Edge is behaving properly. Problem should be solved again.
