### ISSUE TITLE
Print/PDF Sheet Music

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#149]
There is a bug when printing sheet music that prevents all system breaks from being printed. In other words, only a small portion of the sheet music is actually printed (PDF or paper). I assume the severity of the bug is somewhat urgent since many people print sheet music from the browser in order to play it.

# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Issue exists on Chrome, Safari, Firefox (probably others)
* Operating System and version (desktop or mobile): Desktop and mobile browsers
* Link to your project: n/a

# Expected Results

Initiating a File > Print command prints all system breaks in the sheet music.

![screen shot 2017-07-20 at 14 22 52](https://user-images.githubusercontent.com/1033190/28437364-935758a0-6d57-11e7-88c0-ded7d13ad51c.png)

# Observed Results

Currently only about 20% of the systems are being printed or show up on a PDF render in the case where you don't scroll ALL the way through the sheet music in the browser window prior to trying to print or render a PDF. If you scroll all the way to the bottom of the sheet music, all of the systems show up. If you had a 10 page piece of sheet music and only scrolled through the first couple pages, you would only get those pages in the PDF or printout. Obviously not what the user would want.

![screen shot 2017-07-20 at 14 22 36](https://user-images.githubusercontent.com/1033190/28437377-9cd9b4ea-6d57-11e7-95f2-3e472665ddad.png)

# Steps to Reproduce (for bugs)
 
1. Navigate to [https://demo.alphatab.net/player.html](https://demo.alphatab.net/player.html) in any web browser
2. Immediately run the File > Print command without scrolling through the sheet music.
3. See in the print preview/printout/PDF that only a subset of the system breaks are rendered.
4. Reload [https://demo.alphatab.net/player.html](https://demo.alphatab.net/player.html)
5. Scroll all the way to the end of the sheet music.
6. Run the File > Print command without scrolling through the sheet music.
7. See in the print preview/printout/PDF that all system breaks are rendered.

# Possible Solution 

I don't know what internally is causing this but my educated guess is that there's a piece of performance code that prevents all rendering from occurring at once and as you scroll, more music is rendered on-the-fly. It's a thoughtful idea but causes unintended consequences for when you try to view the entire score.

# Bounty

I'll donate you a couple of beers again 👍

**Comment by Danielku15** [comment]
Hi. 
This topic was already addressed some time ago. If you look closely you will find a "Print" button in the toolbar. There is a [special print function](https://github.com/CoderLine/alphaTab/blob/master/Samples/JavaScript/player.html#L187) on the API which renders the music notation in a proper A4 sizing.  

Directly printing is not possible due to the responsive sizing. The browser will take the existing browser size for printing exactly what you see (but with different stylesheet). The print popup does a re-rendering with fixed size and a slighly lower scale and tighter stretching to fit better on A4.

**Comment by gburlet** [comment]
Hi Daniel,

Thanks for directing me to that old issue. I'm unable to use the print button to launch a printable popup since, alongside the web client, I have alphaTab running on iOS and Android within embedded WebViews and that solution doesn't really work in that environment.

Through the commits tied to that old issue I managed to find a `DisableLazyLoading` setting that is populated by the `lazy` json alphaTab parameter. Setting that to false and tweaking the html meta tag viewport scale on mobile devices worked like a charm for me. All the music now shows up and looks great on web, iOS, and Android for me.

You can go ahead and close this issue. Sorry for the dupe, but hopefully my findings help someone else out if they're running alphaTab locally on devices and don't want popups.

**Comment by Danielku15** [comment]
Happy to hear that it works for you. Getting alphaTab prepared for printing depends a lot on how it is used in the applications. Sadly there is no reliable API yet to reorganize your website for printing. There are print-media CSS but sometimes JS Code is needed to do more advanced reorganization. 

Closing this issue now.
