### ISSUE TITLE
Numbered Notation

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#1505]
We should add support for numbered music notation

https://en.wikipedia.org/wiki/Numbered_musical_notation

![Image](https://github.com/CoderLine/alphaTab/assets/674916/f4771c39-d9cc-4ecf-a1ff-f2a9d7cf7659)

Considerations: 

- Staff without lines 
- Only first note of first voice considered
- Accidentals 
- Beam Rendering

**Comment by cao919** [comment]
加油ヾ(◍°∇°◍)ﾉﾞ
