### ISSUE TITLE
Wrong rendering on only-tab mode

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#151]
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: SVG 
* Browser Name and Version: Chrome Version 59.0.3071.115 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

For [this score](https://drive.google.com/open?id=0B9wmO5HutHghOWc5UG15ZnZ1UTg), here is what MuseScore outputs in complete tab mode:

![Smoke on the water tab rendered by MuseScore](https://image.noelshack.com/fichiers/2017/30/1/1500894677-smoke-musescore-tab.png)

# Observed Results

Same score rendered by AlphaTab:

![Smoke on the water tab rendered by MuseScore](https://image.noelshack.com/fichiers/2017/30/1/1500894327-smoke-alphatab.png)

I observe at least 3 problems:
* The quarter notes are displayed with a flag, like eighth notes
* The time signature is missing
* The rests are missing

# Steps to Reproduce (for bugs)

Initialise AlphaTab with these options:

    $('#alphaTab').alphaTab(
        staves: { id: 'tab', additionalSettings: { 'rhythm': true } }
    );

(Like in the Guitar Tabs sample, which is not working in the [online demo](https://demo.alphatab.net/features.html#tabs), by the way)

**Comment by Danielku15** [comment]
Good finding. I haven't used the tab-only display a lot so I missed various details. In the latest commits I added several improvements to the tab-only rendering:

* Quarter notes are rendered properly now
* Time signature is now rendered for tab-only display
* Rests are added
* Dotted notes are shown properly 

I compared the alphaTab output with the Guitar Pro rendering and beside some minor alignment differences it should show the features correctly now. 

Is there anything else you spotted already?

**Comment by j4kim** [comment]
Great ! You definitely are a very efficient developer. I'll let you know if I observe other display errors.

Just in case you didn't notice it, the two first examples under the ["Guitar Tabs" tab](https://demo.alphatab.net/features.html#tabs) are missing in the online feature samples. It seems like the `files/features/Rhythm.gp5` file is missing.
