### ISSUE TITLE
Buggy auto-scroll when using custom scroll element

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#152]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome 59.0.3071.115 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

In vertical scroll mode, the player should always scroll to the correct height, in order to display the played line.

# Observed Results

When using a different scroll element than body, the scroll animation is a mess. The page is scrolled randomly up and down.

# Steps to Reproduce (for bugs)

Here is a JSFiddle which recreates the configuration of my layout: https://jsfiddle.net/j4kim/7ho3mmmm

# Possible Solution 

Here is what I did in a previous version of the AlphaSynth jQuery plugin: https://github.com/j4kim/alphaTab/commit/494f52280585453a7fbdd6261118133a5ad65999
That did the trick. But now I want to update to the current version, and the code has changed a lot (since this: https://github.com/CoderLine/alphaTab/commit/439c97d8a279c590983e3bb40af645868274f7c7). So I don't know precisely where the problem is, but I suspect a wrong calculation in the `elementOffset` or `scrollElementOffset`. 

Here is a sketch I did when I tried to understand what was wrong (in the previous state): ![scrollElementOffset](https://image.noelshack.com/fichiers/2017/26/1/1498466574-elementoffset.jpg) 

I don't know if it helps. It just spots that there is (was) a problem with `elementOffset`, being negative in this case.

**Comment by Danielku15** [comment]
The correct calculation for the scrolling has always been a bit a problem. I fear I really need introduce separate mechanisms for `html,body` based scrolling in comparison to a custom element. There seem to be certain offsets which don't play well together. in both scenarios. 

I'll have an additional look to this topic but it might take a bit longer until I found a proper solution for this.

**Comment by Danielku15** [comment]
As I expected the behavior of `.offset()` is inconsistent between `html,body` and custom elements. For custom elements the offset becomes negative when scrolling. For `html,body` it becomes positive. I made some tests with all browsers and various combinations and it worked fine for me.
