### ISSUE TITLE
How to catch API errors ?

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#154]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome 59.0.3071.115 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

I have a file input for entering a guitar pro file. I load the file in alphaTab when the input changes. In order to validate the file, I need to catch the potential import errors from AlphaTab.

The API could trigger the "alphaTab.error" event when an error occurs. Something like this:
```js
at.on('alphaTab.error', function (e, data) {
    if(data.msg === "importError") ...
}
```

# Observed Results

The errors seem to be just printed in the console.

# Steps to Reproduce (for bugs)

Load a non valid file and try to be notified by some error.

# Possible Solution 

Here is what I did: https://github.com/j4kim/alphaTab/commit/54ddd85d81443f5653d344a78aa4dca093a8e1d4
Added manually a `throw` statement on the failure callback of the fileLoader methods. It does the job in most cases but there are inconveniences:
* I have to maintain an other version up to date, which I found out today is not easy
* It doesn't even catch all the import errors, some files pass through this trick (text files mostly). I think I am not throwing errors in all cases...

well, it's not a good solution.

**Comment by Danielku15** [comment]
I added a new event for handling errors and tried to forward the details about the error. I still need to check through the code where I need to add certain exception handlers with error notifiers but at least general loading and rendering errors should be catchable via the new `alphaTab.error` event. Documentation will follow.

**Comment by Danielku15** [comment]
Error event docs are now available at:
https://docs.alphatab.net/develop/reference/events/error
