### ISSUE TITLE
Tempo/bpm marker overlaps chord symbol on first beat

### ISSUE THREAD

**Issue by bali182** [CoderLine/alphaTab#1560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current behaviour can be observed on the alphaTex docs page:

https://alphatab.net/docs/alphatex/beat-effects#chords

![Untitled](https://github.com/CoderLine/alphaTab/assets/3879181/3e6cce8b-1acd-4f0e-9107-e5eb03338dcf)

### Expected Behavior

The chord symbol not to overlap with the bpm marker

### Steps To Reproduce

Any simple example will do with a chord symbol, eg.:
```
\tempo 140
.
5.6.4 {ch "Am"}
```

### Found in Version

1.3

### Platform

Web

### Environment

```markdown
- **OS**: Win 10
- **Browser**: Chrome
```

**Comment by Danielku15** [comment]
Should be fixed in 1.4 already https://next.alphatab.net/docs/alphatex/beat-effects/#chords
