### ISSUE TITLE
Tempo in track instead of bar ?

### ISSUE THREAD

**Issue by lux-lth** [CoderLine/alphaTab#157]
# Your environment

* Version used: (master branch)
* Platform used: C#
* Rendering engine used: GDI
* Operating System and version : Linux CentOS 7 - mono

# Expected Results

I think bars should have a tempo.
See : in this partition, the tempo changes at the 57th bar :
http://puu.sh/x1ALF/d5cc0cf34d.png

# Observed Results

Currently the tempo is in the track object.

# Possible Solution 
Given the tempo can change from a bar to the other, I think tempo should be an attribute of the bar rather than an attribute of the track.

**Comment by Danielku15** [comment]
Thanks for your report. Tempos are supported on 2 levels: [Score](https://github.com/CoderLine/alphaTab/blob/master/Source/AlphaTab/Model/Score.cs#L82) and [MasterBar](https://github.com/CoderLine/alphaTab/blob/master/Source/AlphaTab/Model/MasterBar.cs#L56). The score defines an overall tempo for the whole song, . The MasterBar defines a tempo **change** for the song at a certain bar index for all tracks. 

It might be a bit redundant that the score has also a tempo if every MasterBar can define one, but that's how Guitar Pro internally holds the information and alphaTab resembles this data structure.

**Comment by tumbleweed-t** [comment]
In MasterBar I only see "TempoAutomation", is that it ?

**Comment by Danielku15** [comment]
Yes. In Guitar Pro 5 they had a concept of "Mix Table Changes" and in Guitar Pro 6 they are called "Automations":
![image](https://user-images.githubusercontent.com/674916/28995472-310e4222-79ea-11e7-8205-956ac2137c1b.png)

Automations can be used to change track volumes, track pan or the global tempo at a certain time. GP5 also supported instrument changes, but Arobas dropped this feature in GP6.

**Comment by Danielku15** [comment]
As there was no update on this, I'm closing the issue. If there is still something open feel free to reopen the issue.
