### ISSUE TITLE
vite-plugin-alphatab-copy: path computing issue on github pages / maybe Ubuntu in general

### ISSUE THREAD

**Issue by bali182** [CoderLine/alphaTab#1577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to deploy an app containing alphaTab on github pages, which is built using vite / alphaTab vite plugin.

On github pages the build fails while the `vite-plugin-alphatab-copy` plugin is trying to copy some assets into the public folder.
https://github.com/bali182/alphatab-vite-build-bug-repro/actions/runs/9906924688/job/27369512708

Messages are like this: 

```
[vite-plugin-alphatab-copy] ENOTDIR: not a directory, copyfile '/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/soundfont/LICENSE/LICENSE' -> '/home/runner/work/stick/stick/public/soundfont/LICENSE'
Error: ENOTDIR: not a directory, copyfile '/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/soundfont/LICENSE/LICENSE' -> '/home/runner/work/stick/stick/public/soundfont/LICENSE'
Error: Process completed with exit code 1.
```

The file names are doubly present in the path its trying to copy from:
```'/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/soundfont/LICENSE/LICENSE'```

To see what's happening, I made a simplified version of `copyAssetsPlugin.ts` and when running it as an individual plugin and logging the  `files` in `copyFiles`, it seems like on gh pages (maybe on Linux on general, IDK) the `readdir` functions `file` already has the full file path. So this:

```ts
await Promise.all(
  files
    .filter((f) => f.isFile())
    .map(async (file) => {
      const sourceFilename = path.join(file.path, file.name)
      console.log({
        'file.path': file.path,
        'file.name': file.name,
        sourceFilename: sourceFilename,
      })
      await fs.promises.copyFile(
        sourceFilename,
        path.join(outputPath!, subdir, file.name),
      )
    }),
)
```

Results in this:

```js
{
  'file.path': '/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/font/Bravura-OFL-FAQ.txt',
  'file.name': 'Bravura-OFL-FAQ.txt',
  sourceFilename: '/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/font/Bravura-OFL-FAQ.txt/Bravura-OFL-FAQ.txt'
}
{
  'file.path': '/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/font/Bravura-OFL.txt',
  'file.name': 'Bravura-OFL.txt',
  sourceFilename: '/home/runner/work/stick/stick/node_modules/@coderline/alphatab/dist/font/Bravura-OFL.txt/Bravura-OFL.txt'
}
```

And `file.path` has the full path of the file. So appending the file name again will result in double file names.

### Expected Behavior

The build to succeed

### Steps To Reproduce

Here is a simple repro to reproduce this with the latest vite and alphatab versions:
https://github.com/bali182/alphatab-vite-build-bug-repro

And here are the logs of a failed run
https://github.com/bali182/alphatab-vite-build-bug-repro/actions/runs/9906924688/job/27369512708

### Link to jsFiddle, CodePen, Project

https://github.com/bali182/alphatab-vite-build-bug-repro

### Found in Version

1.4 (alpha)

### Platform

Web

### Environment

```markdown
- **OS**: ubuntu latest
- **Browser**: not relevant
- **.net Version**: not relevant
```

**Comment by Danielku15** [comment]
Thanks for the detailed analysis. That's indeed a strange behavior. Seems `fs.path` was deprecated in Node 20.12 in favor of parentPath. See:

https://github.com/nodejs/node/pull/50838
https://github.com/nodejs/node/pull/50976

**Comment by bali182** [comment]
Just to confirm, builds prefectly with vite in `1.4.0-alpha.1085`, thank you for the quick fix!

**Comment by juliandevnguitar** [comment]
Hi, i´ve been struggling with the same error trying to deploy on netlify and vercel. Im using next js, and deployed once with success, then i started working on some minor updates to my app (almost style and ui work, so nothing essential changed with alphatab) then when i did the new commit. I encounter the same issue on the deployment log:  

1:57:44 PM:    Creating an optimized production build ...
1:57:51 PM: unhandledRejection [Error: ENOTDIR: not a directory, copyfile 'node_modules/@coderline/alphatab/dist/font/Bravura-FONTLOG.txt/Bravura-FONTLOG.txt' -> 'public/alphatab/font/Bravura-FONTLOG.txt']

so i think im dealing with the same problem mentioned above. Maybe i could upgrade to 1.4.0 and give it a try? Is there a public version or i have to sign up to a wish list or something? Thank for your time

**Comment by Danielku15** [comment]
The 1.4.0 prerelease versions are also available via NPM: https://www.npmjs.com/package/@coderline/alphatab?activeTab=versions

**Comment by juliandevnguitar** [comment]
Thank you for the quick response as always. Just to update, upgrading the netlify config so that the docker cointainer installs the latest node version worked perfectly, i didnt upgrade alphatab, but the deployment was successfull.
