### ISSUE TITLE
Your contact form doesn't work

### ISSUE THREAD

**Issue by musichopper** [CoderLine/alphaTab#159]
It appears that on your website where you state that showing code in examples of actual use is the best way to see how it can be used and modified to work in a variety of ways happens to be hidden as an included file and called from a script. Checked page source and there is no example code due to this. If I am to use the alphatab I would need it to scroll within its own place on the browser as you do in one of the unreachable examples. I would also need to allow the metronome BPM/playback speed to be changed based on dynamically altered tempo as BPM. Would also be nice to be able to load different song files without reloading entire page. Bonus points if I can change the color of certain tab spots dynamically like on one string for one certain bet or set of notes etc.

I normally just hack around until I can sort these things out from looking at code however as mentioned earlier, you have the code all hidden on a remote file you call to dynamically when the page loads within a script. The documentation I checked back to see still says in progress.

I was hoping to include this tab player in my upcoming website but feeling like I might have to find another way due to the lack of documentation.

Thanks!
Allen

**Comment by gburlet** [comment]
Hi Allen,

First of all, please use the issue template if you would like to report a bug or potential improvement to AlphaTab.

Regarding hidden code, every segment of code on your client web browser is accessible to you so I'm a little confused by your statement. You can `View Source` on any of the demo pages on the AlphaTab website to see exactly what is going on. Further, it's common to include javascript as a separate file rather than pasting the whole thing in an include tag in the HTML. Once you view source you can follow the link to the javascript file and see every line of code. If it happens to be the minified version, AlphaTab is open source on github and you can find the uncompressed version in one of the build folders.

If you want the functionality you ask for you are free to fork the repository and make a pull request yourself, or fill out a proper issue template for the seasoned developers to address.

**Comment by musichopper** [comment]
| <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>AlphaTab - Example Browser</title>
  |  
  | 
  | <script type="text/javascript" src="lib/alphaTab/AlphaTab.js"></script>
  |  
  | 
  | <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  | <script type="text/javascript" src="lib/alphaTab/jquery.alphaTab.js"></script>
  |  
  | 
  | <script type="text/javascript" src="lib/swfobject/swfobject.js"></script>
  | <script type="text/javascript" src="lib/alphaSynth/AlphaSynth.js"></script>
  |  
  | 
  | <script type="text/javascript" src="lib/alphaTab/jquery.alphaTab.alphaSynth.js"></script>
  |  
  | 
  | <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />
  | <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous" />
  | <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.7.2/css/bootstrap-slider.min.css" integrity="sha256-6b+gYy3DG/roKdQiHqp1FJYFQkaZdM6ohUpGyFyUAGk=" crossorigin="anonymous" />
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.7.2/bootstrap-slider.min.js" integrity="sha256-dd5QxcG/E8fb/H/iIQann2y2EDS0nEMVI56yYWFeeW4=" crossorigin="anonymous"></script>
  | <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.10/handlebars.min.js"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/prism.min.js"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/plugins/line-numbers/prism-line-numbers.js"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/plugins/normalize-whitespace/prism-normalize-whitespace.js"></script>
  |  
  | <link rel="stylesheet" href="support/demo.css" />
  | <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism.min.css" />
  | <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/plugins/line-numbers/prism-line-numbers.min.css" />
  | </head>
  | <body>
  | 
  | <nav class="navbar navbar-default navbar-fixed-top">
  | <div class="container">
  | <div class="navbar-header">
  | <a class="navbar-brand" href="">
  | <img alt="alphaTab" src="support/alphaTab.png" />
  | Example Browser
  | </a>
  | </div>
  | <div id="navbar" class="navbar-collapse collapse">
  | </div>
  | </div>
  | </nav>
  |  
  | <div class="container" id="mainContent">
  | <p>
  | We have prepared a huge list of examples to show different alphaTab features by code. Those examples are the easiest way to understand what alphaTab is capable of and how to use it.
  | The samples shown here are focusing on the usage on websites but many of the settings shown in this samples are also valid for the .net version of alphaTab.
  | </p>
  |  
  | <div id="menuContainer">
  | </div>
  | </div>
  |  
  | <div class="container" id="exampleContent">
  | <h1 id="exampleTitle"></h1>
  | <div>
  | <a id="showMenu" href="#">&#8592; Back to menu</a>
  | </div>
  | <div id="loadingIndicator">
  | <i></i>
  | <span></span>
  | </div>
  | <div id="exampleBody">
  | </div>
  | </div>
  |  
  |  
  | <script type="text/x-handlebars-template" id="menuBlock">
  | <div class="menuBlock">
  | {{#if url}}
  | <h1><a href="{{url}}" target="_blank">{{title}}</a></h1>
  | {{else}}
  | <h1>{{title}}</h1>
  | <ul>
  | {{#each children}}
  | <li>
  | {{#if todo}}
  | <a href="#">{{title}} <span class="wip">(work in progress)</span></a>
  | {{else}}
  | <a href="{{url}}">{{title}}</a>
  | {{/if}}
  | </li>
  | {{/each}}
  | </ul>
  | {{/if}}
  | </div>
  | </script>
  |  
  | <script type="text/javascript">
  | $.ajaxSetup({ cache: true });
  | var menu = [
  | {
  | title: 'General',
  | children: [
  | { title: 'Simple initialization', url: 'general/simple.html' },
  | { title: 'Configuring tracks', url: 'general/tracks.html' },
  | { title: 'Use alphaTex', url: 'general/alphaTex.html' },
  | { title: 'HTML5 canvas rendering', url: 'general/html5.html' },
  | { title: 'Visual Element List', url: 'general/elements.html' },
  | { title: 'Advanced Usage', url: 'general/advanced.html' }
  | ]
  | },
  | {
  | title: 'Layouts',
  | children: [
  | { title: 'Page layout', url: 'layouts/page.html' },
  | { title: 'Horizontal layout', url: 'layouts/horizontal.html' },
  | ]
  | },
  | {
  | title: 'Stave Configurations',
  | children: [
  | { title: 'Score and guitar tablature', url: 'staves/scoretab.html' },
  | { title: 'Score only', url: 'staves/score.html' },
  | { title: 'Guitar tablature only', url: 'staves/tab.html' },
  | { title: 'Guitar tablature with rhythm', url: 'staves/rhythm.html' }
  | ]
  | },
  | {
  | title: 'Render Customization',
  | children: [
  | { title: 'Scale tablature', url: 'render/scale.html' },
  | { title: 'Change render size', url: 'render/size.html' },
  | { title: 'Restricting bars', url: 'render/restrictbars.html' },
  | { title: 'Hide song info', url: 'render/hideinfo.html' },
  | { title: 'Hide tuning', url: 'render/hidetuning.html' },
  | { title: 'Hide track names', url: 'render/hidenames.html' },
  | { title: 'Adjust stretch force', url: 'render/stretchforce.html' },
  | { title: 'Force piano fingering', url: 'render/pianofingering.html' },
  | { title: 'Transpose display', url: 'render/transposedisplay.html' },
  | { title: 'Transpose display and playback', url: 'render/transposedisplayplay.html' }
  | ]
  | },
  | {
  | title: 'Player',
  | children: [
  | { title: 'Basic initialization', url: 'player/init.html', todo: true },
  | { title: 'Mute/Solo individual tracks', url: 'player/mutesolo.html', todo: true },
  | { title: 'Change scroll direction', url: 'player/scrolldirection.html', todo: true },
  | { title: 'Change scroll element', url: 'player/scrollelement.html', todo: true },
  | { title: 'Adjust scroll offset ', url: 'player.scrolloffset.html', todo: true },
  | { title: 'Adjust cursor style', url: 'player/cursorstyle.html', todo: true },
  | { title: 'Seeking', url: 'apiplayer/seek.html', todo: true },
  | { title: 'Handle position change', url: 'apiplayer/position.html', todo: true },
  | { title: 'Handle state change', url: 'apiplayer/state.html', todo: true },
  | { title: 'Metronome', url: 'apiplayer/metronome.html', todo: true },
  | { title: 'Control audio volume', url: 'apiplayer/volume.html', todo: true },
  | { title: 'Control playback speed', url: 'apiplayer/speed.html', todo: true },
  | { title: 'Control playback range', url: 'apiplayer/range.html', todo: true },
  | { title: 'Enable auto looping', url: 'apiplayer/loop.html', todo: true }
  | ]
  | },
  | {
  | title: 'API',
  | children: [
  | { title: 'List of all settings and methods', url: 'api/settings.html', todo: true },
  | { title: 'Change file', url: 'api/load.html', todo: true },
  | { title: 'Load score manually', url: 'api/scoreloader.html', todo: true },
  | { title: 'Change layout ', url: 'api/layout.html', todo: true },
  | { title: 'Handling errors', url: 'api/errors.html', todo: true },
  | { title: 'Print dialog', url: 'api/print.html', todo: true },
  | { title: 'Disable lazy loading', url: 'api/lazy.html', todo: true },
  | { title: 'Handle resize', url: 'api/resize.html', todo: true },
  | { title: 'Load event', url: 'api/loadevent.html', todo: true },
  | ]
  | },
  | {
  | title: '.net Samples',
  | url: 'https://github.com/CoderLine/alphaTab/tree/master/Samples/CSharp'
  | }
  | ]
  | var menuBlock = Handlebars.compile($('#menuBlock').html());
  | for(var i = 0; i < menu.length; i++) {
  | $('#menuContainer').append(menuBlock(menu[i]));
  | }
  | $('#menuContainer a').on('click', function(e) {
  | var url = $(this).attr('href');
  | if(url.indexOf("http") === 0) {
  | return;
  | }
  | e.preventDefault();
  | window.location.hash = url;
  | });
  |  
  | $(window).on('hashchange', function(e) {
  | var url = window.location.hash.substring(1);
  | if(url) {
  | var link = $("#menuContainer a[href='"+url+"']");
  | openExample(link.text(), link.attr('href'));
  | }
  | else {
  | $('#exampleBody .alphaTab').alphaTab('destroy');
  | $('#menuContainer').show();
  | $('#exampleBody').html('');
  | $('#exampleContent').hide();
  | }
  | });
  | $(window).trigger('hashchange');
  |  
  | $('#showMenu').on('click', function(e) {
  | e.preventDefault();
  | window.location.hash = '';
  | });
  |  
  | function initExamples(data) {
  | var doc = document.implementation.createHTMLDocument();
  | doc.body.innerHTML = data;
  | data = doc;
  |  
  | $(data).find('.example').each(function() {
  | var html = $(this).find('.html').html();
  | var js = $(this).find('.js').html();
  |  
  | var wrap = $('<div class="exampleSource"></div>');
  | var ul = $('<ul class="nav nav-tabs"></ul>').appendTo(wrap);
  | var tabContent = $('<div class="tab-content"></li>').appendTo(wrap);
  |  
  | $('<li class="active"><a href="#">HTML</a></li>').appendTo(ul);
  | $('<div class="tab-pane active"></div>')
  | .append($('<pre class="line-numbers"></pre>').append($('<code class="language-html"></code>').text(html)))
  | .appendTo(tabContent);
  |  
  | $('<li><a href="#">JavaScript</a></li>').appendTo(ul);
  | $('<div class="tab-pane"></div>')
  | .append($('<pre class="line-numbers"></pre>').append($('<code class="language-javascript"></code>').text(js)))
  | .appendTo(tabContent);
  |  
  | $(this).prepend(wrap);
  |  
  | ul.on('click', 'a', function(e){
  | e.preventDefault();
  |  
  | var parent = $(this).closest('.exampleSource'),
  | li = $(this).closest('li'),
  | index = li.index(),
  | tabs = parent.find('.tab-content')
  | ;
  |  
  | parent.find('li.active').removeClass('active');
  | li.addClass('active');
  | tabs.find('.tab-pane.active').removeClass('active');
  | tabs.find('.tab-pane').eq(index).addClass('active');
  |  
  | });
  | });
  | $('#exampleBody').append(data.body.children);
  |  
  | $('#exampleBody script').each(function() {
  | var code = $(this).html();
  | var newScript = document.createElement('script');
  | newScript.innerHTML = code;
  | $(this).replaceWith(newScript);
  | });
  |  
  | Prism.highlightAll();
  | }
  |  
  | function openExample(title, content) {
  | $('#menuContainer').hide();
  | $('#exampleContent').show();
  |  
  | $('#exampleTitle').text(title);
  | $('#loadingIndicator span').text('Loading example');
  |  
  | $('#exampleContent').addClass('loading');
  |  
  | $.ajax({
  | url: content,
  | dataType: 'html'
  | }).done(function(data) {
  | initExamples(data);
  | }).fail(function(xhr) {
  | var msg = "Sorry but there was an error while loading the example: ";
  | $('#loadingIndicator span').text( msg + xhr.status + " " + xhr.statusText );
  | }).always(function() {
  | $('#exampleContent').removeClass('loading');
  | });
  | }
  | </script>
  | </body>
  | </html>

**Comment by gburlet** [comment]
Okay, so read the code and follow the links to view the HTML for the example:
```
{ title: 'Simple initialization', url: 'general/simple.html' },
{ title: 'Configuring tracks', url: 'general/tracks.html' },
{ title: 'Use alphaTex', url: 'general/alphaTex.html' },
{ title: 'HTML5 canvas rendering', url: 'general/html5.html' },
{ title: 'Visual Element List', url: 'general/elements.html' },
{ title: 'Advanced Usage', url: 'general/advanced.html' }
```

expand `general/simple.html` to [https://demo.alphatab.net/general/simple.html](https://demo.alphatab.net/general/simple.html)

**Comment by musichopper** [comment]
https://demo.alphatab.net/general/advanced.html

**Comment by Danielku15** [comment]
Hi Allen. 

I fixed the broken contact form on the website. I forgot to test it after I moved to my new server lately. 

> Checked page source and there is no example code due to this. If I am to use the alphatab I would need it to scroll within its own place on the browser as you do in one of the unreachable examples. 

I am currently in the progress of writing more advanced samples which are already partly located at https://demo.alphatab.net/ For those samples I provide the source code directly viewable as part of the example instead of requiring a look at the source code. 

It sounds like you need one of the samples which is not yet there: "Change scroll element". With this setting you can control that alphaTab does not trigger a scroll on the whole page, but instead of a custom scrollable container wrapping alphaTab. 

I prepared you a sample with the current version of alphaTab: https://jsfiddle.net/danielku15/124Lhqn1/
As part of the new samples I will also try to simplify each feature with the use of data attributes. 

> I would also need to allow the metronome BPM/playback speed to be changed based on dynamically altered tempo as BPM. 

The metronome is disabled by default but can be enabled via an API call. Also the playback speed can be altered. Refer to the [Player Demo](https://demo.alphatab.net/player.html) for a full featured example. (read the source there to see find out how the UI elements are linked to the API calls). 

> Would also be nice to be able to load different song files without reloading entire page. 

You can change the song every time with different API calls. The one you likely want to use is the `load` call. The `score` call would allow you to directly set a `Score` object if you have one from a different source.

https://jsfiddle.net/danielku15/Lcpqse83/

> Bonus points if I can change the color of certain tab spots dynamically like on one string for one certain bet or set of notes etc.

For this I would need more concrete details on what you want to do. Since the rendered music sheet is rather static. There is no API to highlight certain elements or change colors. 

PS: As @gburlet  pointed out, please  use the provided issue template the next time. Feel free to create multiple issues for different questions, this makes it also easier for others to find particular topics if they have similar questions.
