### ISSUE TITLE
User mouse inputs doesn't work anymore

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#160]
Hi Daniel, I'm back :)

# Your environment

* Version used: master
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome Version 61.0.3163.100 (Build officiel) (64 bits)
* Operating System and version: macOS Sierra 10.12.6

# Expected Results

On the player, clicking in the music sheet should set the cursor position.

# Observed Results

Not working since commit https://github.com/CoderLine/alphaTab/commit/b4d874ea20de2928245ce28c412964b1b67fd685

# Steps to Reproduce (for bugs)

1. Checkout master
2. Open `Samples/JavaScript/player.html`
3. Click somewhere in the score

# Possible Solution

I thought there was something wrong in `jquery.alphaTab.alphaSynth.js`, in the "Click Handling" section. But the file didn't change since https://github.com/CoderLine/alphaTab/commit/a3529a1fc403a9aee8d5281cc7b23d00d1bf407d, where the click handling worked... so I don't now.

**Comment by j4kim** [comment]
Update

The problem is that `context.CanvasElement` is undefined at this line :
https://github.com/CoderLine/alphaTab/blob/master/Build/JavaScript/jquery.alphaTab.alphaSynth.js#L624
Adding `context.CanvasElement = context._canvasElement;` before that line solved the problem.
I'm still not familiar with the API so I don't now what's happening in the "dark side". I wish I could solve it and open a pull request but I think it would be much easier for you to fix it.

**Comment by Danielku15** [comment]
Sorry for the very long delay on this. I didn't have really a lof of time lately to work on alphaTab. The bug came in with some cleanups where come class fields were renamed. I restored the old naming which should solve this issue.
