### ISSUE TITLE
Clarification regarding the rendering watermark

### ISSUE THREAD

**Issue by derekwyatt** [CoderLine/alphaTab#161]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: Whatever works out best
* Browser Name and Version: Android  7+ WebView
* Operating System and version (desktop or mobile): Android
* Link to your project:

# Expected Results

Just need some clarification on the copyright notice.

# Observed Results

First off, this library looks really fantastic and I'm quite grateful that it's been done!

It's not 100% clear (OK, it's pretty damn close, but I'm hopeful) that the "Rendered using alphaTab" watermark at the bottom of the rendering is required.  Would it be acceptable to put the attribution into an _About_ screen or something similar?

Obviously you guys need credit, help, reference to your project, and so forth.  **My concern is that I only plan to show two or three bars of music on a small screen** and I think the watermark is going to double the required pixels in a very cramped space.

Is this already possible, and I just missed it, or is it something that could be negotiated somehow?

(Note that I haven't actually tried integrating this into my app yet so I don't know if it's even going to work properly, but I do know that I can't really afford the screen real-estate.)

# Steps to Reproduce (for bugs)
n/a

# Possible Solution 
n/a

**Comment by Danielku15** [comment]
Hi. 
In general I expect a proper credit of alphaTab. I put a lot of personal effort into this library and provide it for free to anybody. Expecting proper credits is really the minimum I can ask for. 

Of course I am open to negotiate other solutions. In the end it depents on how big the role of alphaTab on the website/the app plays. e.g. if it is an app with all about presenting tabs, basically a tab viewer based on alphaTab, I would prefer a more prominent display of alphaTab (like a powered by alphaTab in the splash screen or as watermark somewhere in the menu). If alphaTab plays the main role in the app like that and also likely the app has some ads which bring money to the developer I expect some more than a 1 line notice in an about dialog that nobody ever opens. 

Here a nice example of a different attribution which actually highlights alphaTab as a kind of brand/viewing mode: https://www.infiniteguitar.com/guitar-lessons?lessonid=2314

Maybe you can send me some screenshots of your app and how you'd like to put the attribution into your app and we can find a good solution for your use case. ;)

**Comment by derekwyatt** [comment]
I totally agree! I haven't used it beyond poking the basic samples in JS, but it looks very promising and it clearly was a lot of effort (effort I'd obviously prefer to not expend :D).

You're open to helping me out, which is fantastic and is all I need for the time being.  At the moment I'm focusing on presenting a fretboard that I think I have a good rendering for, but I hope to include dynamically notated exercises in the next couple of months.  If alphaTab turns out to be the right solution, I'm sure we can work something out so that its contribution is very clear but I don't have to sacrifice my precious pixels in a way that hurts too much.
