### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by webprofusion-chrisc** [CoderLine/alphaTab#166]
# Your environment

* Version used: (master branch)
* Platform used:  C# (Xamarin)
* Rendering engine used: SVG (default), HTML5 or GDI

* Operating System and version (desktop or mobile): Win 10 x64
* Link to your project:
https://github.com/webprofusion/scalex

# Expected Results

Would like to see NuGet packages published for core libraries especially Xamarin.Forms

# Observed Results

None currently published

# Steps to Reproduce (for bugs)

 
1. Search NuGet
2. No results

# Possible Solution 
Create and publish nuget packages

**Comment by Danielku15** [comment]
I plan to move to .net standard and the new csprojs soon. This will should automatically result in NuGet packages. The rather tricky topic is setting up a CI process which increases version numbers and deploys alphaTab.

**Comment by webprofusion-chrisc** [comment]
I understand. The current build is working against .net standard 2.0 OK by the way (in xamarin 2.5, referenced as a dll). https://github.com/webprofusion/scalex

**Comment by webprofusion-chrisc** [comment]
p.s. I'd really like to figure out how to do sound in xamarin, but that's another topic!

**Comment by webprofusion-chrisc** [comment]
p.p.s it works great on XBox One X: 
![20171230_133447_cropped](https://user-images.githubusercontent.com/2445502/34452299-2bcf5ef8-ed77-11e7-8855-cb6651be952e.jpg)

**Comment by Danielku15** [comment]
There are now NuGet packages available on MyGet for the CI builds: https://www.myget.org/feed/coderline/package/nuget/AlphaTab

Official NuGet packages will come with the tagged releases.

**Comment by webprofusion-chrisc** [comment]
Awesome! Great work :)

**Comment by Danielku15** [comment]
NuGet packages are now available https://www.nuget.org/profiles/CoderLine 
they still contain the early access version based on typescript see #356  and https://github.com/CoderLine/alphaTab/issues/311#issuecomment-622565172
