### ISSUE TITLE
Chinese character(GBK)

### ISSUE THREAD

**Issue by koaqiu** [CoderLine/alphaTab#168]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile):
* Link to your project:

GP3、GP4、GP5文件中如果有中文，alphaTab显示会乱码，GPX部分文件会乱码
原因是因为不少文件中的中文使用的是GBK编码。 

# Possible Solution 
我尝试使用https://github.com/ashtuchkin/iconv-lite 处理 中文编码问题
可以部分解决问题
```
    ReadString: function (length){
        var b = new Uint8Array(length);
        this.Data.Read(b, 0, b.length);
        return  iconv.decode(data, 'gbk');
    },

```

[东风破.gp4.zip](https://github.com/CoderLine/alphaTab/files/1561444/gp4.zip)

**Comment by Danielku15** [comment]
Duplicate of #99.
