### ISSUE TITLE
Guitar Pro 7 Support

### ISSUE THREAD

**Issue by YeDaxia** [CoderLine/alphaTab#170]
Please consider supporting guitar pro 7.  Thanks very much.

**Comment by Danielku15** [comment]
Hello. 
I'd kindly ask you to follow the [Contribution Guidelines](https://github.com/CoderLine/alphaTab/blob/master/contributing.md). As far as I know Guitar Pro 7 does not have a new file format, it might have certain new features but still the GPX format should be the same. Please try to describe what is not working by following the issue template.

**Comment by Danielku15** [comment]
I have to revoke my last statement: GP7 files are not GPX files. Arobas finally made the step to use zip as their container. The score.gpif for parsing the structure should be the same.

**Comment by Danielku15** [comment]
Guitar Pro 7 is supported on the latest master and develop builds.

**Comment by rhclayto** [comment]
It might be a good idea to update the README to reflect this change; right now it only lists GP3-5 & 6.
