### ISSUE TITLE
Note not played on Chrome

### ISSUE THREAD

**Issue by ice-blaze** [CoderLine/alphaTab#171]
[smoke_on_the_water.gpx.zip](https://github.com/CoderLine/alphaTab/files/1711342/smoke_on_the_water.gpx.zip)
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: HTML5
* Browser Name and Version: Chrome 64.0.3282.119 (64-bit)
* Operating System and version desktop: Ubuntu 16.04 LTS, OSX 10.13.3, Windows 10

# Expected Results

* Load and execute the gpx file of `smoke on the water` in alphatab
* Expected to hear the song all the notes. 

# Observed Results

The song is played correctly except for the 13th and 25th note. 

# Steps to Reproduce (for bugs)

Use alphatab with the gpx file in the attached file.

# Possible Solution 
It's not a real solution but the only workaround found right now is to use Firefox(Ubuntu, OSX, Windows), Edge (Windows 10) or Safari (OSX)

**Comment by gburlet** [comment]
I'm also experiencing issues with Chrome missing notes.

**Comment by Danielku15** [comment]
Thanks for your report. It's really strange certain notes only are not played on Chrome. I played around with some variants of the file and it always behaves slight different. Even with changes that should not have any impact on the audio, change it:

https://jsfiddle.net/danielku15/nrgqtja6/
https://jsfiddle.net/danielku15/nrgqtja6/5/ (without empty bar, suddenly one note plays)

**Comment by Danielku15** [comment]
That was really a tricky bug to fix. It looks like Chrome changed the sort algorithm for arrays. Actually the sorting of the midi events was not deterministic in case there were multiple midi events at the same time. This changed sorting, caused the "note off" to be added directly after the new "note on". It's fixed now.
