### ISSUE TITLE
Brush down (bd) in combination with chord label (ch) seem to break the whole staff

### ISSUE THREAD

**Issue by bali182** [CoderLine/alphaTab#1718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When rendering multiple bars of chords using AlphaTex, the combination of `{bd 120}` and  `{ch "..."}` seem to break the whole staff, and a single bar is rendered.

### Expected Behavior

To be able to render multiple bars.

### Steps To Reproduce

This is the smallest repro I could do, 1 track, 2 bars, 1-1 chords in each bar, and only the first one is rendering.

```ts
const tex = `\\track "chords" "c" \\instrument "AcousticGuitarSteel"
\\clef Treble \\ts 4 4 \\ks C (3.2 2.3 0.4).1 {bd 120} {ch "C1"} |
(3.2 2.3 0.4).1 {bd 120} {ch "C2"}`

// ... 

api.tex(tex)
```

Which results in this:
![Screenshot 2024-10-24 203234](https://github.com/user-attachments/assets/aaed101f-236e-4275-b706-80cb9e973aac)

If I remove either the `{bd ...}`-s or the `{ch ...}`-s it renders properly without any issues.

### Found in Version

1.4 (alpha)

### Platform

Web

### Environment

```markdown
- **OS**: Windows
- **Browser**: Chrome latest
- **.net Version**: -
```

**Comment by Danielku15** [comment]
The problem in this case is that your syntax is invalid and alphaTab likely reports an [`error`](https://www.alphatab.net/docs/reference/api/error/) that this syntax is invalid. To combine multiple effects on one beat you place them all in a single `{}` block:

![image](https://github.com/user-attachments/assets/9215ae02-c53c-4d35-b625-b17d50995ab9)

```
const tex = `\\track "chords" "c" \\instrument "AcousticGuitarSteel"
//                                                  vvvv--- simply put all effects one after another
\\clef Treble \\ts 4 4 \\ks C (3.2 2.3 0.4).1 {bd 120 ch "C1"} |
(3.2 2.3 0.4).1 {bd 120} {ch "C2"}`

// ... 

api.tex(tex)
```

**Comment by bali182** [comment]
Aaaah, thanks, I didn't know that! There were no errors thrown or reported in the console, so I assumed the syntax was correct 🙈
