### ISSUE TITLE
Firefox Rendering Broken

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#172]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 58.0.2 (64-bit)
* Operating System and version (desktop or mobile): all OS's affected. Desktop only, works on mobile Firefox.

# Expected Results

Should render the sheet music and be playable using AlphaSynth on Firefox.

# Observed Results

Does not render sheet music and therefore can't be played back.

# Steps to Reproduce (for bugs)

Open up this [fiddle](https://jsfiddle.net/danielku15/p047gsnh/) that you made for me some time ago. Looks like it's pulling the latest AlphaTab from master. Works on all browsers except for Firefox.

# Possible Solution 

When I set `useWorker: false` in the AlphaTab parameters the sheet music renders in Firefox but still can't be played back with AlphaSynth. This hack has the unfortunate side effect of turning off workers for all other browsers, however.

**Comment by gburlet** [comment]
Oh, makes sense. I didn't really know where to start because it was a silent error.

Thanks for your time, Daniel. Appreciate your work!

**Comment by Danielku15** [comment]
I changed the default behavior of the worker creation to the "old fashioned" `importScript`. This should work on all browsers.
