### ISSUE TITLE
How to identify crescendo and decrescendo in musicXML

### ISSUE THREAD

**Issue by Code-Lonely** [CoderLine/alphaTab#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to recognize from musicxml

### Expected Behavior

Can identify  crescendo and decrescendo from musicXML
Example：
```xml
<direction-type>
 <wedge default-x="11" default-y="-77" color="#000000" type="crescendo" />
</direction-type>
```

### Steps To Reproduce

1

### Found in Version

1.3

### Platform

Web

### Environment

```markdown
OS: Windows 10 Pro
Browser: Chrome 92.0.4515.159
```

**Comment by Danielku15** [comment]
No proper bug report, and cross posted here https://github.com/CoderLine/alphaTab/discussions/1726
