### ISSUE TITLE
pitch transposition rendering error

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#173]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: All
* Operating System and version (desktop or mobile): All

# Expected Results

When transposing up or down, sharps or flats should be rendered.

# Observed Results

See [this fiddle](https://jsfiddle.net/danielku15/p047gsnh/) you wrote for me some time ago when working on concert pitch vs written pitch. The provided fiddle is fine, however if you change the second score to `data-display-transposition-pitches="[1]"`, and then keep moving the transposition value higher and higher, you'll see that the notes aren't rendered correctly. Try it out for yourself.

# Steps to Reproduce (for bugs)

See the fiddle above and methodology for bug recreation.

# Possible Solution 
Shouldn't be that intricate of a fix. Not sure how many people use the transposition feature, but for me it's a huge issue that affects a large number of my users.

Bounty: will happily donate a couple beers for this one, Daniel.

**Comment by Danielku15** [comment]
Yes, there was really a bug on this. The accidental calculation did not consider the transposition. I added a fix and a basic test that checks the behavior.
