### ISSUE TITLE
Did Support render/play MIDI file?

### ISSUE THREAD

**Issue by imiskolee** [CoderLine/alphaTab#176]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript or C#
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile):
* Link to your project:

# Expected Results

Explain here what is your expected behavior of alphaTab. 

# Observed Results

Explain here how alphaTab is behaving currently. 

# Steps to Reproduce (for bugs)

Explain here the exact steps how to reproduce the problem. Try to provide a
running sample showing the issue. If you have problem with a dedicated input file, 
please provide a download link or attach it to the issue. 
 
1. 
2. 
3.  

# Possible Solution 
If you already know a solution to the problem please provide it here.

**Comment by Danielku15** [comment]
I'm not sure what you are expecting of a request like this.
