### ISSUE TITLE
Can I shrink, scale down the score?

### ISSUE THREAD

**Issue by KenjiOhtsuka** [CoderLine/alphaTab#177]
# Environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): desktop, Windows 10

I'm trying to show the score like this.

```
at.alphaTab({
  layout: {
    mode: 'horizontal'
  },
  staves: 'score',
  additionalSettings: {
    hideInfo: true
  }
})
```

# Expected Results

shrink, scale down the size of score, to fit div tag's height

# Observed Results

I found `scale` value to shrink the score.

```
at.alphaTab({
  layout: {
    mode: 'horizontal'
  },
  staves: 'score',
  additionalSettings: {
    hideInfo: true
  },
  scale: 0.5
})
```

(when I show like above, scale: 0.5, tempo display is not shown well)
![capture](https://user-images.githubusercontent.com/1572810/38842602-de8a5ed2-4225-11e8-819f-c67d6f2f7a02.PNG)

but what i want to do is fit the score to the height of wrapper html tag.

# Possible Solution

in my understanding SVG is scalable, so there's a simple solution, I guess.

**Comment by Danielku15** [comment]
The render output when using scale looks quite strange. The "scale" cam be compared with a "zoom factor". Everything should look relatively bigger or smaller in this case. I will have look at the problem of resulting in such a bad display.  

But also after that: alphaTab cannot fit automatically a given **height**. The height is the result of the layouting and the elements shown in the music sheet. Maybe you can provide the file you used in the screenshot for testing? I know there might be some additional unneeded spacings that could be optimized.

**Comment by Danielku15** [comment]
Several enhancements were made already on the develop branch. The tempo scaling issue should also be solved in the latest commit.
