### ISSUE TITLE
HTML Canvas Rendering Incorrectly on Firefox/Edge

### ISSUE THREAD

**Issue by deju1980** [CoderLine/alphaTab#179]
Version used: (master branch)
Platform used: JavaScript 
Rendering engine used: HTML5
Browser Name and Version: Firefox (latest), Edge (latest)
Operating System and version (desktop or mobile): Windows 10 desktop

**Observed Results**

When rendering using HTML5 engine, some symbols are missing from the rendered file, eg:

![missing notation](https://user-images.githubusercontent.com/32038074/39094307-659eabe6-4625-11e8-9ed9-14c0a65501fb.png)

**Steps to Reproduce (for bugs)**

Use html5 as rendering engine and view in Firefox/Edge browser. This behaviour can be observed on the alphaTab website:

[https://demo.alphatab.net/index.html#general/html5.html](https://demo.alphatab.net/index.html#general/html5.html)

**Comment by Danielku15** [comment]
Looks like there is again a problem with detecting whether the web-font is already loaded.

**Comment by Danielku15** [comment]
Problem should be solved with the latest changes on the `develop` branch. Beside the check that the font is loaded, Firefox also returned additional quotes on the font name which resulted in double-quotes and therefore to an invalid font name.
