### ISSUE TITLE
Problem when change the file to render 

### ISSUE THREAD

**Issue by RicardoCao-Biker** [CoderLine/alphaTab#180]
# Your environment
Version used: (master branch)
Platform used: JavaScript
Rendering engine used: HTML5
Browser Name and Version: Chrome
Operating System and version (desktop or mobile): Windows 7 desktop
# Expected Results
I want to change file to render
# Observed Results
I download the masterbranch file and used the Samples/JavaScript/player.html to render and play the tab.
I find if i change the attr of data-file in <div id="alphaTab" data-file=""> to a new file address like files/canon.gp5,the tab will change to canon.
however,when i write a function and a new button, i click the button to query a new address from database,and change the attr,hope to render a new file,and it failed. 
I wonder how to change the file to render.
```  
$(function(){  
	$("#submit").click(function(){ 
	        $.ajax({ 
	          type:"post",
	          url:"demo.php",
	          dataType:"json",
	          data:{search:$("#text").val()},
	          success:function(feedbackdata)
	            {
	              console.log(feedbackdata);
	              $("#alphaTab").attr("data-file",feedbackdata);
	            }
	        });
	    })
 	 })
```  
# Possible Solution

**Comment by Danielku15** [comment]
I told you already on your other issue: please use the issue template. It is there on purpose: https://github.com/CoderLine/alphaTab/blob/master/contributing.md

**Comment by RicardoCao-Biker** [comment]
Sorry about that and I have use the template ,hope to get your response

**Comment by Danielku15** [comment]
Thanks for updating the defect. Unfortunately this part of the documentation is not yet written. 

There are 2 ways of changing the displayed file: 

1. You can load a file via the `file` function by calling `$('#alphaTab').alphaTab('load', source)`. Source can be many things: 
  - If it is a `string`, it will try to load the file via ajax and display it. 
  - If it is a `ArrayBuffer` or `Uint8Array` it will use the raw binary data to decode the file for display. 

2. If you already have a `alphaTab.model.Score` object from any source (manually generated, manually decoded etc.) you can open it via `$('#alphaTab').score(object)`

Does this answer your question?

**Comment by RicardoCao-Biker** [comment]
yes,it works,thank you so much!

**Comment by Danielku15** [comment]
Okay, closing this issue then 😀

**Comment by twodee** [comment]
Did the `load` option to `alphaTab` get removed? I can't find it in master or develop.
