### ISSUE TITLE
Chinese text display

### ISSUE THREAD

**Issue by RicardoCao-Biker** [CoderLine/alphaTab#181]
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: HTML5
* Browser Name and Version: Chrome
* Operating System and version desktop

# Expected Results

I want alphaTab could display Chinese correct

# Observed Results

when I trying to render a  .gp5 file with chinese ,title and text display wrong.

![qq 20180427171925](https://user-images.githubusercontent.com/29997411/39355222-2add8f86-4a3f-11e8-97fd-2f5efc2792f1.png)

# Possible Solution 
I tried the solution at #99 commented by MetalLee like 
`ReadString: function (length){ var b = new Uint8Array(length); this.Data.Read(b, 0, b.length); var gbkDecoder = new TextDecoder('gbk'); console.log(gbkDecoder.decode(b)); return gbkDecoder.decode(b) }`
but it doesn't works.

**Comment by Danielku15** [comment]
Please do not open duplicate issues if you already find related ones. Comment on the existing one.
