### ISSUE TITLE
Track rendering issues with some files

### ISSUE THREAD

**Issue by phamduchao** [CoderLine/alphaTab#185]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG 
* Browser Name and Version: Mozilla/5.0 (Macintosh; Intel …) Gecko/20100101 Firefox/60.0
* Operating System and version (desktop or mobile): desktop

# Observed Results

Alphtab do not show tab and score on track[2].

# Steps to Reproduce (for bugs) 
1. Input https://drive.google.com/open?id=1R3Wmgrv5jB5z92PIFuM7lfa0jKLB_KVP file
2. Select Track[2] (Fingered Bass) then alphaTab do not show score and tab.
3. I get this error 
[AlphaTab][render] An unexpected error occurred in worker AlphaTab.Platform.Std.Log@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:1555:17
AlphaTab.Util.Logger.Log@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:18357:5
AlphaTab.Util.Logger.Error@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:18352:5
Error@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:1212:9
delegate@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:82:24
OnError@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:16686:13
Render@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:16562:13
RenderMultiple@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:1205:13
HandleMessage@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:1193:17
delegate@http://192.168.1.3/assets/js/alphaTab/Build/JavaScript/AlphaTab.js:82:24
 TypeError: beat.NoteHeads is null

**Comment by kjdion84** [comment]
+1 getting these errors for a ZZ top song (among others): https://guitarprotabs.org/z/zz_top/sharp_dressed_man_20915/download/

The error:

> [AlphaTab][render] An unexpected error occurred in worker Error
>     at Function.AlphaTab.Platform.Std.Log (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:1557:18)
>     at Function.AlphaTab.Util.Logger.Log (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:18336:27)
>     at Function.AlphaTab.Util.Logger.Error (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:18331:26)
>     at AlphaTab.Platform.JavaScript.JsWorker.Error (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:1214:30)
>     at delegate (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:83:29)
>     at AlphaTab.Rendering.ScoreRenderer.OnError (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:16665:13)
>     at AlphaTab.Rendering.ScoreRenderer.Render (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:16541:18)
>     at AlphaTab.Platform.JavaScript.JsWorker.RenderMultiple (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:1207:28)
>     at AlphaTab.Platform.JavaScript.JsWorker.HandleMessage (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:1195:22)
>     at delegate (http://fgpt.local/alphaTab/Build/JavaScript/AlphaTab.js:83:29) TypeError: Cannot read property 'GetNoteX' of null
>     at AlphaTab.Rendering.TabBarRenderer.GetNoteX (AlphaTab.js:17330)
>     at AlphaTab.Rendering.Glyphs.TabSlideLineGlyph.Paint (AlphaTab.js:14627)
>     at AlphaTab.Rendering.Glyphs.TabBeatContainerGlyph.Paint (AlphaTab.js:12260)
>     at AlphaTab.Rendering.Glyphs.TabBeatContainerGlyph.Paint (AlphaTab.js:14224)
>     at AlphaTab.Rendering.Glyphs.VoiceContainerGlyph.Paint (AlphaTab.js:15106)
>     at AlphaTab.Rendering.TabBarRenderer.Paint (AlphaTab.js:10870)
>     at AlphaTab.Rendering.TabBarRenderer.Paint (AlphaTab.js:17472)
>     at AlphaTab.Rendering.Staves.Staff.Paint (AlphaTab.js:16993)
>     at AlphaTab.Rendering.Staves.StaveGroup.PaintPartial (AlphaTab.js:17178)
>     at AlphaTab.Rendering.Staves.StaveGroup.Paint (AlphaTab.js:17173)

**Comment by Danielku15** [comment]
Sorry for the delayed response. The problems were related to some invalid slides in the file. There were shift and legato slides in the file which did not have a target note. For those cases the slides are now removed. 

Fix is available on the `develop` branch

**Comment by phamduchao** [comment]
Thank for your respone.
