### ISSUE TITLE
can not access api documentation? File or directory not found???

### ISSUE THREAD

**Issue by suency** [CoderLine/alphaTab#186]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile):
* Link to your project:

can not access api documentation? Where can I read the api documentation? Anyone got the solution?

**Comment by Danielku15** [comment]
The latest documentation is available on 

https://docs.alphatab.net/develop/ (for master)
https://demo.alphatab.net/ (for develop)

More docs are currently not available
