### ISSUE TITLE
Hide title node?

### ISSUE THREAD

**Issue by kjdion84** [CoderLine/alphaTab#189]
Is there an option I can use to hide the title node entirely? I'd like to use my own UI for the title.

The title node is normally the first `.alphaTabSurfaceSvg`

**Comment by Danielku15** [comment]
Hiding the song info is described here: https://demo.alphatab.net/#render/hideinfo.html
If you also want to hide the tuning there is another setting: https://demo.alphatab.net/#render/hidetuning.html
