### ISSUE TITLE
Percussion tracks does not transpose

### ISSUE THREAD

**Issue by aister** [CoderLine/alphaTab#193]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile):desktop
* Link to your project:

# Expected Results

Percussion tracks transposes automatically and displays the correct percussion notes

# Observed Results

the track (which was saved in Guitar Pro 5) didn't transpose automatically and display notes 1 octave lower. And using data-display-transposition-pitches does nothing. Tried with both data attributes and script init but same results

# Steps to Reproduce (for bugs)

 just load any tracks in gp5 with percussion

# Possible Solution 

In `AlphaTab.Rendering.Utils.AccidentalHelper.prototype.RegisterNoteLine`, the `value` variable doesn't account for the display transposition pitch when the track is percussion, thus why it ignores the setting. I don't know enough of the whole code to figure out the rest, but adding a `+ 12` before the `:` solves the issue for me.

**Comment by Danielku15** [comment]
Thanks for reporting. I will need to have a closer look what you mean by "they are not transposed". Guitar Pro and alphaTab place the note heads at fixed lines. There is no note height that defines the position or can be even transposed. 

But it could be that they are actually transposed even though they shouldn't resulting in an unexpected position. I will have a closer look.

**Comment by Danielku15** [comment]
The behavior is fixed in the latest version of master and develop.
