### ISSUE TITLE
Demo Player's notes unclickable

### ISSUE THREAD

**Issue by aister** [CoderLine/alphaTab#195]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Win 10
* Link to your project: your own demo player

# Expected Results
the note is clickable and the track will go to the note

# Observed Results
notes are unclickable, trying to drag to select a part will result in the note elements got selected instead.

# Steps to Reproduce (for bugs)

just try it on ur demo player

# Possible Solution 

the mouseup, mousemove and mousedown events in `jquery.alphaTab.alphaSynth.js` refers to `context.CanvasElement`. However, the context in `AlphaTab.js` use _canvasElement instead.

This doesn't happen on the github file, only on the website's file.

**Comment by Danielku15** [comment]
Thansk for reporting. The issues are fixed in the latest versions. I finally dared to merge the changes from the develop branch to the master branch. The latest docs and demos are available at https://docs.alphatab.net/
