### ISSUE TITLE
Player not work on Safari 12.0(Updated 18/09/2018)

### ISSUE THREAD

**Issue by phamduchao** [CoderLine/alphaTab#200]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Safari 12.0
* Operating System and version (desktop or mobile): desktop

# Steps to Reproduce (for bugs)
- Press play button then alphaTab do nothing without any error.

**Comment by Danielku15** [comment]
Sounds like Apple introduced the same problems as on iOS now on the desktop version of Safari. It is very likely that the Web Audio context is suspended by default. I will try to attempt a resuming that works for Desktop too. 

It is kind of a "prevent autoplay" feature that the browsers add to overcome this annoying automatic audio of ads when entering a page. In this case it prevents proper audio generation in the background.

**Comment by phamduchao** [comment]
I saw audioContext.state always be 'suspended' instead of 'running'. I think the same thing will happen on chrome in October 2018 (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio). 
P/S: Sorry for my bad English.

**Comment by Danielku15** [comment]
Thanks for the update. I will try to delay the audio context creation to a later point (including some resuming attempts). Hopefully that will fix the issue then

**Comment by Danielku15** [comment]
I added today additional actions to resume the audio context. This should solve the issue in most of the cases.

**Comment by phamduchao** [comment]
Thank Daniel.
