### ISSUE TITLE
The render is not correct for Appoggiatura.

### ISSUE THREAD

**Issue by LYH8112** [CoderLine/alphaTab#202]
The render is not correct for Appoggiatura.
# Your environment
* Version used: master branch
* Platform used: C#
* Rendering engine used: GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile): windows 10
* Link to your project:

# Expected Results
![image](https://user-images.githubusercontent.com/23731747/45857681-9359b100-bd8c-11e8-9cc4-aa7e18ecec67.png),  

# Observed Results
![image](https://user-images.githubusercontent.com/23731747/45857789-0f53f900-bd8d-11e8-95b6-58770ced1bd0.png)

# Steps to Reproduce (for bugs)
1.  open music xml file (test.xml)
2. 
3.  

[test.zip](https://github.com/CoderLine/alphaTab/files/2413703/test.zip)

# Possible Solution

**Comment by Danielku15** [comment]
Thanks a lot for following the template this time 👍 . I fear something might got broken as part of the songbook-style display. I will try to fix this soon.

**Comment by Danielku15** [comment]
I made several fixed and published them on the develop branch. With the changes the MusicXML should show as expected. Here a comparison:

**MuseScore**
![image](https://user-images.githubusercontent.com/674916/46246045-1667b080-c3f8-11e8-829c-cea1e8d1bc67.png)

**AlphaTab**
![image](https://user-images.githubusercontent.com/674916/46246039-03ed7700-c3f8-11e8-885c-9f28d8e05796.png)
