### ISSUE TITLE
Tied notes broken for non-stringed instruments

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#206]
# Your environment

* Version used: `develop` branch
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: All major browsers
* Operating System and version (desktop or mobile): desktop and mobile

# Expected Results

Alphatex:
```
\tuning none\tempo 145.\ks F \ts 3 4 \clef G2 r.4 r.4 r.8 a4.8 | d5.8 a4.4 d5.8 a4.8 d5.8 | a4.8 a4.4 a4.8 a4.8 g4.8 | g4.4 f4.4 d4.4 | r.8 a4.8 -.4  d5.4 a4.8 d5.8 | a4.8 d5.8 a4.4 a4.8 g4.8 | g4.4 g4.4 a#4.8 a4.8 | g4.4 a4.8 d5.8 a4.8 d5.8 | -.8  d5.8 a4.4 a4.8 c5.8 | c5.4{d} g4.8 f4.4 | d4.4 d4.4 -.4  f4.4 | -.4  a4.4 c5.4 | -.4  d#5.4 d5.8 g#4.8 -.8  a4.8 f4.8 -.8  | -.8  e4.8 -.8  d4.4 -.4  c4.4 | a5.4 a5.4 r.8 a5.8 | f5.4 a5.4 a5.8 r.32 f5.16{d} | a5.4 f5.4 d5.4 | -.4  a5.4 a5.4 | -.4  a5.4 a5.4 | r.8 a5.8 a5.4 g5.4 | c5.4{d} a5.16 f5.16 -.16  -.4  a5.4 | -.4  a5.4 a5.4 | -.8  a5.16 f5.16 -.16  -.4  a5.4 f5.4 -.4  | -.4  d5.4 a#4.16 -.16  d5.16 -.8  f5.8 | -.8  d5.8 f5.8 a5.8 d5.4 -.4  | -.4  f4.16 a#4.8{d} a4.8 f4.8 | -.4  r.4 f4.4 | g#4.8 f4.8 -.8  g4.4 r.16 g#4.8{d} | r.8 g#4.8 f4.4 g#4.4 | g4.4 f4.16 g#4.8{d} f4.4 | f4.4 g#4.4 g4.4 | g#4.8 g4.8 f4.16 g#4.8{d} f4.8 g#4.8 | g4.8 f4.16 g#4.16 r.8 g4.8 g#4.8 g4.8 | f4.8 d4.8 f4.4 g#4.8 g4.8 | -.4  g#4.16 f4.16 -.8  g4.8 f4.4 | f4.4 g#4.4 g4.8{d} f4.16 | r.8 f4.16 g4.16 f4.4 f4.4 | g#4.4 g4.4 f4.8 f4.8 | g4.16 f4.8{d} d4.8 f4.8 g#4.8 g#4.8 | g#4.4 f4.2 | c5.4 -.4  e5.4 -.4  g5.4 | g5.8 g5.8 e5.8 c5.8 f5.8 f5.8 | f5.8 f5.16 -.16  g5.16 -.4  a5.4 -.4  | -.4  e5.8 e5.8 -.4  g5.4 | c5.4 e5.8 c5.8 e5.8 g5.8 | f5.4 f5.8 f5.16 -.16  g5.16 -.4  a5.4 | -.2  a#5.8 a#5.8 | -.4  d6.4 a#5.8 c#6.8 c#6.8 c#6.8 | -.8  a#5.8 f5.4 f5.8 f5.8 | g#5.4 d6.2 | a#4.8 -.8  d5.8 g5.8 g5.8 e5.4 -.4  | e5.4 e5.4{d} f5.8 | f5.4 f5.8 e5.8 -.8  d5.4 -.4  | -.4  c5.4 -.4  a#5.4 | a5.4 -.4  -.4  g5.4 | f5.4 -.4  -.4  f5.4 | e5.4 -.4  -.8  d5.4{d} | c5.2 a#5.4 | a5.4{d} g5.4{d} | f#5.2 d5.4 | a#4.2 d5.4 | b4.4 d5.4 c5.4 -.4  | -.4  c#5.4 d5.4 | d5.4 r.8 f5.8 f5.8 d5.16 a#4.16 | r.16 a#4.8{d} e5.16 g5.16 -.32  e5.16{d} r.16 a4.8{d} | a4.16 g4.16 f4.8 d5.4 g4.8 e5.8 | -.8  a4.8 f5.4 r.4 | r.8 f#4.16 g#4.16 f#4.16 g#4.8 f#4.16 g#4.16 f#4.16 -.8  g#4.8 | c#5.8 g#4.8 c#5.8 g#4.8 c#5.8{d} a#4.16 | b4.4 a#4.8 g#4.16 f#4.16 g#4.16 f#4.16 -.8  g#4.8 | f#4.16 g#4.16 f#4.8 -.8  g#4.8 c#5.8 r.16 c#5.8{d} | r.8 a#4.8 a#4.4 a4.16 a#4.8{d} | a#4.16 a4.16 -.8  a#4.8 r.16 c5.8{d} g4.8{d} f#4.16 | g#4.8 f#4.16 g#4.16 f#4.16 g#4.8 f#4.16 g4.16{d} c#5.32 -.8  | c#5.4 g#4.8 a#4.16 a4.16 -.16  -.4  a#4.4 | a#4.4 b4.16 c5.8 g4.16 e4.16 c4.8{d} | c#4.8 c#4.8 a#3.4 e4.8 c#4.8 | r.16 f4.16 e4.8 -.8  r.16 f#4.16 g4.8 c4.8{d} g4.16 | g#4.16 g4.16 -.8  g#4.8 r.16 a#4.16 a4.16 -.16  -.16  a#4.16 -.4  c5.4 | -.4  c5.4 c5.4 | -.4  c5.4 c5.4 | e5.4{d} f5.8 r.16 g#4.8{d} | e4.8 d#4.8 d4.4 c5.4 | g4.4 c5.8 b4.8 c5.4 | c5.4 -.4  c#5.4 e4.8 c#5.8 | -.8  c#4.8 e4.8 c#4.8 c#4.16 e4.16 d#4.8 -.8  | -.16  c5.16 c5.8 c#5.8 e4.8 c#5.4 | c#4.16 e4.16 c#4.8 -.8  e4.16 c#4.16 -.8  e4.8 d#4.8 c5.8 | c#5.8 e4.8 c#4.8{d} c#4.16 e4.8 e4.8 | c#4.16 e4.16 d#4.8 c5.4 a3.8 f#4.8 | a#3.16 c4.8 e4.16 g4.16 c5.16 c#4.8 -.8  c#4.4 | -.4  r.4 a3.4 | a#3.2 -.8 {d} a3.16 | -.8  d3.8 a#3.2 | -.4  a3.8 -.8  a#3.8 -.16  a3.8 f3.16 | d3.4 a#3.2 | a3.4 -.4  -.4  f3.8 d3.8 | a3.2{d} | -.2  -.8  a4.8 | d5.8 a4.8 d5.8 a4.8 d5.8 a4.8 | r.16 a4.16 a4.8 a4.8 g4.8 g4.8 f4.8 -.8  | -.8  d4.8 -.8  -.4  a4.8 d5.8 | a4.8 d5.8 a4.8 d5.8 a4.8 g#4.16 -.16  a4.16 | g4.4 -.4  g4.4 g4.8{d} c5.16 | a#4.8 a4.8 g4.4 a4.8 d5.8 | a4.8 d5.4 d5.8 a4.16 g#4.16 -.16  -.8  a4.8 | -.4  c5.4 c5.4 g4.8 f4.8 | -.8  d4.4{d} d4.4 | f4.4 a4.4 c5.4 | d#5.8 d5.8 g#4.8 a4.8 f4.4 | -.4  r.4 r.4 
```

correctly renders this as of commit 8ad767d56f72468599019a046a878635621df53b:

<img width="1098" alt="screen shot 2018-10-18 at 12 47 05 pm" src="https://user-images.githubusercontent.com/1033190/47177615-1a3f7200-d2d6-11e8-8e47-062690d96044.png">

# Observed Results

Same alphatex as input renders this on latest develop branch:

<img width="908" alt="screen shot 2018-10-18 at 1 02 13 pm" src="https://user-images.githubusercontent.com/1033190/47177656-3f33e500-d2d6-11e8-85f0-6a61842820c9.png">

# Steps to Reproduce (for bugs)

Render the above alphatex on the HEAD of the develop branch.

# Possible Solution 

Tied notes for non-stringed instruments (e.g., vocal music) was implemented in Issue #139. Commit 491d8b2 specifically addressed the issue of tied notes in this context. The last build in which I know that tied notes for non-stringed instruments was working was Commit 8ad767d56f72468599019a046a878635621df53b.

# Current Workarounds

Generate guitar tablature for non-guitar instruments as AlphaTex input, then hide the tab staff.

# Bounty

I'll donate some beers for the cause!

**Comment by Danielku15** [comment]
Even if it might have worked partially before, it was never fully supported to have ties on non stringed instruments. The algorithm is looking for a note on the same string to auto-detect which note to tie with. 

To fully support this following extensions likely need to be made: 

- If a note is marked as tied, and the previous beat has only 1 note, use it as tie origin. 
- Check how GP formats flag the ties for non stringed instruments and add support for it. 
- Explicitely allow marking tie origin and destination in alphaTex

**Comment by gburlet** [comment]
> If a note is marked as tied, and the previous beat has only 1 note, use it as tie origin.

I think this is a good idea to ensure backwards compatibility with older AlphaTex files that have previously used the `-` syntax to render ties 👍 

> Explicitely allow marking tie origin and destination in alphaTex

### Solution 1:
The way that MusicXML does this is with `<tie type="start"/>` on the note that starts the tie and `<tie type="stop"/>` on the same-pitched note that ends the tie. I think this is sufficient because I can't think of a situation where a note would have multiple ties open at the same time on the same pitch.

### Solution 2:
When starting a tie assign a unique ID that must be referenced when ending a tie.

I think Solution 1 allows for more human readable alphatex while Solution 2 is more explicit but unnecessarily verbose.

**Comment by Danielku15** [comment]
I just pushed several improvements regarding tied notes to the develop branch. There are now various ways of specifying ties that should cover all scenarios and also feel natural. 

- When using single notes you can simply use the dash. 
- When using chords the note order is considered. 
- You can also specify the actual note value and annotate the tie separately to achieve a tie with the correct note (previous occurence of the same note height is relevant).

Your example should not also look correct: 
![image](https://user-images.githubusercontent.com/674916/48660769-89d88680-ea67-11e8-9f08-df868619ec1a.png)
