### ISSUE TITLE
Non responsive code

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#208]
# Your environment

https://demo.alphatab.net/index.html#general/advanced.html

# Expected Results

Buttons to remain shown

# Observed Results

Buttons disappear

# Steps to Reproduce (for bugs)

1.  Open Page
2. Reduce size of browser window
3.  Observe disappearing buttons

# Possible Solution 
CSS

**Comment by Danielku15** [comment]
Thanks for highlighting this problem in the samples.

**Comment by nascent** [comment]
It was the .collapse CSS class which I have removed from my example.

I have also noticed that the .alphaTab class for #alphaTab appears to have no use however I do not know where in the code that particular classname is being applied.

Thank you for responding.

**Comment by Danielku15** [comment]
I adjusted the layout of the player sample to use flexbox and be a bit more responsive. Of the sample overall is not perfect but it also should only fulfill the purpose of showing devs how to interact with alphaTab. A proper player that is integrated into a website should bring those features more user friendly to the interface.
