### ISSUE TITLE
Metronome can't be switched off

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#209]
# Your environment

JavaScript Developer library

# Expected Results

Metronome switched off during playback after being switched on

# Observed Results

Metronome cannot be switched off arbitrarily

# Steps to Reproduce (for bugs)

1. Press play
2. Switch metronome on
3. Attempt to switch metronome off

# Possible Solution 

None found

**Comment by Danielku15** [comment]
Looks like something broke lately on the samples to enable/disable the metronome.

**Comment by Danielku15** [comment]
The problem is fixed with the latest changes. There were some wrong checks on whether to only read or only set the metronome value (and others).
