### ISSUE TITLE
Hi Daniel,

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#210]
I found that bug using code from the example page via a local webserver.

The Developer branch of the JavaScript Library works with GP7 files and stave configuration is displayed correctly however some of the notes; while being displayed correctly in GP, are nonetheless pushed down by multiple octaves and playback is incorrect for some notes.

I've also noticed that a file demo.css is unavailable on the web server, for the example provided.

In addition, there are significant responsive code issues, in relation to the Player example (issue has been logged here: https://github.com/CoderLine/alphaTab/issues/208) provided.

Otherwise, thank you for writing such a great library!

Hope that helps.

_Originally posted by @nascent in https://github.com/CoderLine/alphaTab/issue_comments#issuecomment-437559369_

**Comment by Danielku15** [comment]
Please try to file proper individual bug reports using the template like you did on the other reports. This will help a lot to reproduce the problem and get the expectations fulfilled.
