### ISSUE TITLE
Incorrect playback of notes

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#212]
# Your environment

JavaScript Developer library, example site:

https://emotive.productions/alphatab/

# Expected Results

Notes to playback correctly

# Observed Results

Notes C2 and below playback in a lower octave

# Steps to Reproduce (for bugs)

Observe score as rendered and/or press play

# Possible Solution 

None found, use earlier version of Guitar Pro perhaps or modify interpreter

**Comment by Danielku15** [comment]
Not sure what this error was but it seems to be fixed in the latest builds of the develop branch.
