### ISSUE TITLE
Grand Staff Visual Feedback

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#214]
# Description
Visual feedback for note heads on bass clef of Grand Staff unavailable, when playing back music. See: https://emotive.productions/alphatab1/

# Possible Solutions
None identified

# Current Workarounds 
None identified

**Comment by Danielku15** [comment]
Please use the bug template to report misbehaviors and provide all details (more than just a link where I need to derive on my own whats going on).
