### ISSUE TITLE
AlphaTab not working with DOM

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#218]
# Your environment

* Version used: 0.9.3.156
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox Quantum
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

http://acousticremedy.com.au/alphatab3/

# Expected Results

Use standard JavaScript DOM commands from outside of main AlphaTab container

# Observed Results

Playback cannot be stopped, moreover it is restarted when stop is pressed and as well other buttons restart playback rather than perform their designated function when buttons are clicked in a form that is within the AlphaTab main container.

# Steps to Reproduce (for bugs)

1. Press Play
2.  Press Stop

# Possible Solution 

None known, was working with 0.9.3.145 (minified), as per project Demo page

**Comment by Danielku15** [comment]
There is no problem in alphaTab here. It is a problem of your web layout. If you look closely you might realize that your "toolbar" is "behind" alphaTaba and when you try to click any of the buttons, you actually click the alphaTab area which results in a scroll to the clicked position. The button style does not change on click. You made your form "sticky" but forgot to set a `z-index` that ensures it is in front of other elements.
