### ISSUE TITLE
Lyrics not displayed as per .gp file

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#220]
# Your environment

* Version used: (master branch) 0.9.3.156
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome
* Operating System and version Windows 10
* Link to your project:

http://acousticremedy.com.au/alphatab4/

# Expected Results

Lyrics should be displayed as per Guitar Pro file

# Observed Results

Lyrics are placed before first beat

# Steps to Reproduce (for bugs)

View file using AlphaTab in a Web Browser

# Possible Solution 

None identified

**Comment by Danielku15** [comment]
It looks to me that this the file you are using is corrupt and not consistent in its contents. If you check settings of the file in Guitar Pro you see that the lyrics are configured to be shown on bar 1: 
![image](https://user-images.githubusercontent.com/674916/50447850-3edf4800-091e-11e9-9f32-a7267f1ee3ff.png)

Also if you change any character in the lyrics text, it jumps to the display of alphaTab:

![image](https://user-images.githubusercontent.com/674916/50447872-66ceab80-091e-11e9-848f-db73ad9933a3.png)

Or vice versa: If you correctly set the first bar to 12 as expected it is also shown correctly in alphaTab: 
![image](https://user-images.githubusercontent.com/674916/50447903-a2697580-091e-11e9-856c-b7c003d1ba8c.png)

It seems Guitar Pro has a cache in the file regarding lyrics. Beside the real lyrics configuration at the beginning of the file (notice the offset 0 for the lyrics) it also stores already per beat. Which lyrics are to be shown (notice the high beat id): 

```xml
<Lyrics dispatched="true">
<Line>
<Text><![CDATA[can     hav   the  your         see    watch      the                        the         a             where     mu      Get            a           An           the   sic's          With           ev            for                                young        sev              Danc ing        the   beat   from        rine,      oh               hav    your         see    watch          ing                                                     Look          an            for                                young        sev              Danc ing        the   beat   from        rine,      oh               hav    your         see    watch          ing                                    ]]></Text>
<Offset>0</Offset>
</Line>
<Line>
<Text><![CDATA[]]></Text>
<Offset>0</Offset>
</Line>
<Line>
<Text><![CDATA[]]></Text>
<Offset>0</Offset>
</Line>
<Line>
<Text><![CDATA[]]></Text>
<Offset>0</Offset>
</Line>
<Line>
<Text><![CDATA[]]></Text>
<Offset>0</Offset>
</Line>
```



```xml
<Beat id="118">
<Dynamic>FF</Dynamic>
<Rhythm ref="4" />
<TransposedPitchStemOrientation>Upward</TransposedPitchStemOrientation>
<TransposedPitchStemOrientationUserDefined />
<ConcertPitchStemOrientation>Undefined</ConcertPitchStemOrientation>
<Notes>135 136</Notes>
<Properties>
<Property name="PrimaryPickupVolume">
<Float>0.500000</Float>
</Property>
<Property name="PrimaryPickupTone">
<Float>0.500000</Float>
</Property>
</Properties>
<Lyrics>
<Line><![CDATA[can ]]></Line>
<Line><![CDATA[]]></Line>
<Line><![CDATA[]]></Line>
<Line><![CDATA[]]></Line>
<Line><![CDATA[]]></Line>
</Lyrics>
</Beat>
```

I will try to make a fix to use the dispatched lyrics information about the general configuration but please notice that your file is inconsistent and needs an update.

**Comment by nascent** [comment]
Also, I found that turning lyrics off in Guitar Pro, and then saving the file has no effect on what is displayed in the browser.

**Comment by Danielku15** [comment]
Starting with alphaTab 1.1.0-alpha.56 alphaTab will respect the lyrics information which is already applied to the beats by Guitar Pro.
