### ISSUE TITLE
Add slide-ins and slide-outs in alphatex

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#223]
# Description 
This is probably planned already, but nonetheless it would be really nice to be able to add slide-ins and slide-outs to individual notes in alphatex. There is four different kinds of slides that could be added:
 * slide-in from below
 * slide-in from above
 * slide-out towards low notes
 * slide-out towards high notes

Alphatab is awesome by the way ! Thanks for all your hard work.

# Current Workarounds 
None.

**Comment by Danielku15** [comment]
Thanks for reporting this. You are right that it is currently not possible to define this slides in alphaTex, I will add them soon.

**Comment by Danielku15** [comment]
All slide types are now available on alphaTex:

![image](https://user-images.githubusercontent.com/674916/51443657-a8b7fb00-1cec-11e9-80a1-297bc568a6af.png)

```latex
// slides (legato and shift)
3.3{sl} 4.3 3.3{ss} 4.3 |
// slides (into-from-below, intro-from-above, out-up, out-down)
3.3{sib} 3.3{sia} 3.3{sou} 3.3{sod} |
// pick-slides (down and up)
x.3{psd} 3.3 |
x.3{psu} 3.3
```
Docs are also updated: https://docs.alphatab.net/develop/alphatex/note-effects
