### ISSUE TITLE
Add a tapping effect in alphatex

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#225]
# Description 
Hi,
I've combed through the doc, but there doesn't seem to be a way to add a tapping effect in alphaTex. In GP it's indicated by a "T" above the affected note (similar to the slap and pop effects that are already available).

**Comment by Danielku15** [comment]
It seems I totally missed the tap. Slap and Pop effects are there. I'll add it soon.

**Comment by Danielku15** [comment]
Tap effect is now available.
