### ISSUE TITLE
Grace notes are sometimes rendered on the same beat as the note that precedes them

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#227]
# Your environment

* Version used: 0.9.3.162
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 64
* Operating System and version (desktop or mobile): desktop (ArchLinux)
* Link to your project:

# Expected Results
When between two notes, grace notes should have their own space on the tablature.

# Observed Results
While grace notes render properly most of the times, there are some case where they are rendered on the same beat as the note that precedes them. It happens notably when they are inserted between two notes, the first of which is shorter than the second.

For example, the following alphatex snippet renders properly:
```
14.3.8 12.3{gr}{h} 13.3.8
```
![screenshot_2019-01-21 the guitar lick database](https://user-images.githubusercontent.com/46634000/51487768-2c80ee80-1da4-11e9-8d92-e049e1dfab17.png)
But this one, where the first note is half the length of the second, does not:
```
14.3.16 12.3{gr}{h} 13.3.8
```
![screenshot_2019-01-21 the guitar lick database 1](https://user-images.githubusercontent.com/46634000/51487854-605c1400-1da4-11e9-96e1-c72dd5d9774e.png)
The same thing happens even when the notes are on different strings:
```
14.2.16 12.3{gr}{h} 13.3.8
```
![screenshot_2019-01-21 the guitar lick database 2](https://user-images.githubusercontent.com/46634000/51488013-bc269d00-1da4-11e9-90f9-209548e0fd45.png)

# Steps to Reproduce (for bugs)
Create a tab with the following alphatex code:
```
14.3.16 12.3{gr}{h} 13.3.8
```

**Comment by Danielku15** [comment]
Those grace notes always manage to slip trough my positioning logic 💢.  I fear that in this scenario the grace note steals the whole duration of the previous note hence it is positioned at the same location as the first note. 

The whole positioning in alphaTab is based on the timing when notes are supposed to be played. Only this way the alignment is correct in case of multiple voices and tracks being displayed. 

Thanks for the good minimial example that breaks the logic again, I hope I can find a proper fix for this without breaking again some other positioning.

**Comment by Danielku15** [comment]
I improved the positioning in version 0.9.6.282. There was an issue that I considered the wrong beat for calculating how much "time" the beats can steal for positioning.
