### ISSUE TITLE
Grace notes break beams and tuplets

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#229]
# Your environment

* Version used: 0.9.3.162
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 64
* Operating System and version (desktop or mobile): ArchLinux (desktop)
* Link to your project:

# Expected Results
Grace notes shouldn't separate beamed notes:
![example](https://user-images.githubusercontent.com/46634000/51598205-4aae3200-1efd-11e9-8905-a1dd7f84beee.jpg)

# Observed Results
Grace notes inside groups of notes break their beams. They also break tuplets, and it happens with both kinds (before & on the beat):
```
:16 12.3 14.3 13.2 14.2 12.3 14.3 12.2{gr ob}{h} 13.2 14.2
```
![screenshot_2019-01-23 the guitar lick database 1](https://user-images.githubusercontent.com/46634000/51597962-d1164400-1efc-11e9-9916-4741c901a7a9.png)
```
:8 5.3{tu 3} 5.3{tu 3} 4.3{gr}{h} 5.3{tu 3}
```
![screenshot_2019-01-23 the guitar lick database](https://user-images.githubusercontent.com/46634000/51597450-9069fb00-1efb-11e9-98b8-7f3df7b417ff.png)
```
:16 12.3{tu 5} 14.3{tu 5} 12.2{gr ob}{h} 13.2{tu 5} 14.2{tu 5} 12.1{tu 5}
```
![screenshot_2019-01-23 the guitar lick database](https://user-images.githubusercontent.com/46634000/51597721-3289e300-1efc-11e9-9ee6-45bb57d746f7.png)

**Comment by Danielku15** [comment]
Haven't seen such combinations a lot in music notation yet., that's maybe the reason why I missed it. It might be a bit a bigger rework to get the beaming correct and still render everything as it should be but should be doable.

**Comment by cheap-glitch** [comment]
It's not really a huge problem anyway, it's more of a cosmetic and readability issue.

**Comment by Danielku15** [comment]
I still have to do some further tests but so far it looks good with my changes. Your examples are now displayed as expected without break: 
![image](https://user-images.githubusercontent.com/674916/52899672-effeb200-31ec-11e9-8f2f-15e25aa443b2.png)
![image](https://user-images.githubusercontent.com/674916/52899683-060c7280-31ed-11e9-96da-b93788a14aa3.png)
![image](https://user-images.githubusercontent.com/674916/52899689-17ee1580-31ed-11e9-83c0-d1595fa33b14.png)

Also more complex variants are not breaking the tuplets: 
![image](https://user-images.githubusercontent.com/674916/52899713-5b488400-31ed-11e9-9e9b-c0177111b7e6.png)

**Comment by Danielku15** [comment]
I couldn't find any further issues with my changes. Closing this issue as done.
