### ISSUE TITLE
Add shuffle rhythms in alphaTex 

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#230]
# Description 
Currently there is no way in alphatex to indicate a shuffle rhythm at the beginning of a score like in GP. It would be useful to have at least the "triplet shuffle" (two eighth notes are equivalent to a quarter and an eighth in a triplet) and the "dotted shuffle" (two eighths are equal to a dotted eighth and a sixteenth) as those are the most prevalent types of shuffles.

**Comment by Danielku15** [comment]
Yes, this feature is missing. But please for the future try to fill out all sections provided by the template even if you answer them with something like "no known workaround". This keeps consistency among al feature requests. 

Also I always appreciate if people suggest/describe *how* they would like to see a feature in alphaTab.

**Comment by Danielku15** [comment]
Triplet feel can not be specified in alphaTex.
