### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Andis59** [CoderLine/alphaTab#232]
# Question 

When compiling the whole solution on Visual Studio 2017 version 15.9.7 I get this error
`XDG0008	The name "AlphaTab" does not exist in the namespace "clr-namespace:AlphaTab.Platform.CSharp.Wpf;assembly=AlphaTab".	MainWindow.xaml	55		AlphaTab.Samples.Wpf`

The AlphaTab.Samples.Wpf program is working (except the open file icon is not showing)

But the alphaTab\Samples\CSharp\AlphaTab.Samples.Wpf\MainWindow.xaml has an error and will not display anything, which makes it hard to work with.

I have followed the Setup Development Environment instructions in the wiki

**So, what have I missed?**

# Your environment (if applicable)

* Version used: (master branch)
* Platform used:  C#
* Operating System and version (desktop or mobile): Windows 10 Home version 1809, build 17763.253

Edit: Fixed some mistakes...

**Comment by Danielku15** [comment]
Did you notice any compilation error on the AlphaTab.CSharp project? Depending on the workpackages you have installed on your Visual Studio you might be missing some packages to compile the project fully. 

The AlphaTab.CSharp project is multi-targeting netstandard2.0, net472, MonoAndroid8.1 
I could imagine that if something is missing on your machine to compile all targets the overall output is missing. This then leads to a follow-up compilation error on the samples. Try to recompile only the AlphaTab.CSharp project and check the build output for potential errors. 

To be sure I'm currently updating my VS to the latest version but I guess it is more a local thing.

**Comment by Andis59** [comment]
After following your advice I got everything working!

Thank you very much!
