### ISSUE TITLE
Export a tablature generated with alphatex in Guitar Pro format

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#234]
# Description 
It would be useful to be able to export a tab written in alphaTex into the GPX format (or even GP5 as Guitar Pro 6 & 7 can still load them). A function returning some kind of file handle would be nice.

# Possible Solutions

# Current Workarounds 
None.

**Comment by Danielku15** [comment]
Even though it might sound like a nice feature in a first shot, I do not see high importance for it in alphaTab itself.  If you want to provide a GP exporter in your website, I would recommend that you have a look at the [GPIF parser](https://github.com/CoderLine/alphaTab/blob/develop/Source/AlphaTab/Importer/GpifParser.cs) and create a matching XML writer. 

Then you just need to create a zip with the structure: 

* Content/score.gpif (containing the XML structure)
* VERSION (containing "7.0")

**Comment by Danielku15** [comment]
Closing this issue. GP7 export was added in. If additional export formats are needed, we should create new issues for it.
