### ISSUE TITLE
Changing the verbosity level of the log output

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#235]
# Description 
When debugging JS with the dev console, it can get annoying to have to parse through all the output generated by alphatab. It would be nice to have a way to set the verbosity, like `alphaTab('verbosity', 0)` for radio silence, `alphaTab('verbosity', 1)` for errors only and `alphaTab('verbosity', 2)` for everything.

# Possible Solutions

# Current Workarounds 
It seems there are ways in JS to prevent a library from flooding the console log, but they are all a little hacky.

**Comment by Danielku15** [comment]
You can set the log verbosity via the `logging` setting. Simply set it to none, debug, info, warning or error depending on the level you want to have. This setting can be set via data attribute or json setting.

**Comment by cheap-glitch** [comment]
Maybe I'm doing something wrong, but I tried both the JSON and data attribute methods and neither is working.

**Comment by Danielku15** [comment]
Looks like there was a minor issue when sending the log level to the webworker. The logging setting should work now again.
