### ISSUE TITLE
Player sometimes replays the opening note when reaching the end of the score

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#236]
# Your environment

* Version used: 0.9.3.164
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 65.0.1
* Operating System and version (desktop or mobile): ArchLinux
* Link to your project: https://www.theguitarlickdatabase.com/

# Expected Results
The playback should stop cleanly when reaching the end of a score.

# Observed Results
The player replays the first note of a score when it reaches the end, but only if that last note (or notes) has some effect applied to it, like a bend or a vibrato.
You can hear the bug here: https://www.theguitarlickdatabase.com/lick/102
or here: https://www.theguitarlickdatabase.com/lick/104

But when the last note is vanilla, the bug does not occur.
An example here: https://www.theguitarlickdatabase.com/lick/98
another one here: https://www.theguitarlickdatabase.com/lick/57

This is not a new bug btw, it's been here since I first used the playback feature in alphatab (so around 0.9.3.157 or so).

# Steps to Reproduce (for bugs)
Create a tab with a bend or some vibrato on the last note.

# Possible Solution

**Comment by Danielku15** [comment]
This sounds rather like a Firefox bug to me than alphaTab. I fear that Firefox replays some parts of the audio buffer even though that is wrong. 

* Desktop Chrome 72 - working correct
* Mobile Chrome 72 - working correct
- Microsoft Edge - working correct
- Opera - working correct
- Desktop Safari 11.1 - working correct
- iOS 12 Safari - working correct

When the last sample is played of the song, all web audio nodes are stopped and disconnected. There is nothing more that can be done from code to tell the browser that the playback is finished. 

Note: You should add a loading indicator to your website until the player is really ready. For me the download of the soundfont on your server is quite slow (even though I have fast internet). Until the soundfont is loaded and the player is ready, the player controls should not be enabled. It gives the wrong impression to users.
