### ISSUE TITLE
Font's cannot be found

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#237]
# Your environment

* Version used: (develop branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome
* Operating System and version (Windows):
* Link to your project:

http://acousticremedy.com.au/alphatab6/

# Expected Results
Chrome to not generate errors in developer console

# Observed Results
Chrome generates the following errors:

# Steps to Reproduce (for bugs)

1. Open affected page
2. Observe Console errors

# Possible Solution

Edit the following lines of code:

`CreateStyleElement: function(settings) {
		var elementDocument = (js.Boot.__cast(this._api.Container , alphaTab.ui.HtmlElementContainer)).Element.ownerDocument;
		var styleElement = elementDocument.getElementById("alphaTabStyle");
		if(styleElement == null) {
			var fontDirectory = settings.FontDirectory;
			styleElement = elementDocument.createElement("style");
			styleElement.id = "alphaTabStyle";
			styleElement.type = "text/css";
			var this1 = "";
			var css = this1;
			css = css + ("@font-face {" + "\r\n");
			css = css + ("    font-family: 'alphaTab';" + "\r\n");
			css = css + ("     src: url('" + fontDirectory + "Bravura.eot');" + "\r\n");
			css = css + ("     src: url('" + fontDirectory + "Bravura.eot?#iefix') format('embedded-opentype')" + "\r\n");
			css = css + ("          , url('" + fontDirectory + "Bravura.woff') format('woff')" + "\r\n");
			css = css + ("          , url('" + fontDirectory + "Bravura.otf') format('opentype')" + "\r\n");
			css = css + ("          , url('" + fontDirectory + "Bravura.svg#Bravura') format('svg');" + "\r\n");
			css = css + ("     font-weight: normal;" + "\r\n");
			css = css + ("     font-style: normal;" + "\r\n");
			css = css + ("}" + "\r\n");
			css = css + (".alphaTabSurface * {" + "\r\n");
			css = css + ("    cursor: default;" + "\r\n");
			css = css + ("}" + "\r\n");
			css = css + (".at {" + "\r\n");
			css = css + ("     font-family: 'alphaTab';" + "\r\n");
			css = css + ("     speak: none;" + "\r\n");
			css = css + ("     font-style: normal;" + "\r\n");
			css = css + ("     font-weight: normal;" + "\r\n");
			css = css + ("     font-variant: normal;" + "\r\n");
			css = css + ("     text-transform: none;" + "\r\n");
			css = css + ("     line-height: 1;" + "\r\n");
			css = css + ("     line-height: 1;" + "\r\n");
			css = css + ("     -webkit-font-smoothing: antialiased;" + "\r\n");
			css = css + ("     -moz-osx-font-smoothing: grayscale;" + "\r\n");
			css = css + ("     font-size: 34px;" + "\r\n");
			css = css + ("     overflow: visible !important;" + "\r\n");
			css = css + ("}" + "\r\n");
			styleElement.innerHTML = css;
			elementDocument.getElementsByTagName("head").item(0).appendChild(styleElement);
			alphaTab.Environment.CheckForFontAvailability();
		}
	}`

or else provide options via the API to define preferred font format(s).

**Comment by Danielku15** [comment]
I think your expectation here is completely wrong here. AlphaTab is creating a CSS style with the web font it needs automatically. For this alphaTab expects the web fonts to be placed in a "Font" folder beside the script file. The font directory can be changed via: 

1. The `fontDirectory` property on the settings passed during initialization. 
2. A global variable `ALPHATAB_FONT` pointing to the directory. 

It is not expected that you define the alphaTab web font on your own as you do it in your alphaTab.css. If you insist to make your own web font definition, you theoretically can create a custom style tag with the id `alphaTabStyle` to make alphaTab believe the tag was already created. But I would recommend to use the standard behavior to ensure everything is displayed as expected.
