### ISSUE TITLE
Triplet feel indications are displayed twice over tablatures

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#238]
# Your environment

* Version used: 0.9.3.171
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Linux
* Link to your project:

# Expected Results
The indication of a triplet feel should only be displayed once.

# Observed Results
When showing only the tablature, the indications for triplet feels are displayed twice:
![screenshot_2019-02-17 lick 105 the guitar lick database](https://user-images.githubusercontent.com/46634000/52911162-6c060200-32a0-11e9-8129-35638aadc6b8.png)

This does not happen when the classic score is displayed, or both tab and score are:
![screenshot_2019-02-17 lick 105 the guitar lick database 1](https://user-images.githubusercontent.com/46634000/52911174-9c4da080-32a0-11e9-9c2a-d94c7e353645.png)
![screenshot_2019-02-17 lick 105 the guitar lick database 2](https://user-images.githubusercontent.com/46634000/52911177-9eaffa80-32a0-11e9-99be-579e91c79aa8.png)

# Steps to Reproduce (for bugs)
Create a score with some triplet feel and display only the tablature.

# Possible Solution

**Comment by Danielku15** [comment]
The triplet feel effect info was accidentally registered twice for the tab-only layout. The problem should be solved now.
