### ISSUE TITLE
Add a triplet feel indication to the score metadata

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#239]
# Description 
Right now the triplet feel indication is defined as part of the bar metadata, so it will only apply to a single bar. It would be nice if it could also be applied to the whole score by setting it in the score metadata -- in the same way that the tempo can be set both for the whole score and for each bar.

# Possible Solutions

# Current Workarounds 
Defining the same triplet feel for each bar.

**Comment by Danielku15** [comment]
>Right now the triplet feel indication is defined as part of the bar metadata, so it will only apply to a single bar.
This is not true. Whenever a triplet feel is added to a bar, it is valid from this bar on until it is reset with another triplet feel indicator.

**Comment by cheap-glitch** [comment]
Maybe I'm missing something, but the following alphatex:
```
\tempo 120 . \ts 4 4 \tf t8 :8 5.3*8 | 5.3*8
```

will produce this tab, where the triplet feel has been reset on the second bar:
![screenshot_2019-02-17 lick 107 the guitar lick database](https://user-images.githubusercontent.com/46634000/52911618-804cfd80-32a6-11e9-929c-f7c86f99d173.png)

**Comment by Danielku15** [comment]
A fix is available in build 0.9.3.172. It was not intentionally that the triplet feel is only applied to a single bar. Just like in Guitar Pro when you activate it for a bar, it is meant to be valid from that bar on until reset.
