### ISSUE TITLE
How use predefined tunings

### ISSUE THREAD

**Issue by Andis59** [CoderLine/alphaTab#240]
# Question 
There are a number of predefined tunings, e.g. "Guitar Dropped D Tuning", "Guitar Open A Tuning", ..

**How would I go about to use one?**

* Version used: development branch
* Platform used: C#
* Operating System and version (desktop): Windows 10 Home

**Comment by Danielku15** [comment]
The question is not quite clear to me. What do you mean by "using" them? This predefined list is to  show the corresponding name if a file uses one of the known tunings.

Do you use alphaTex to write your notation and want to use them by name for your song?

**Comment by Andis59** [comment]
OK, i see!
You have the notes of the tuning and can get the name of the tuning...

Was thinking the reverse. Well, maybe I add a function....
