### ISSUE TITLE
Triplets made of one quarter note and one eight note don't merge correctly

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#241]
# Your environment

* Version used: 0.9.3.173
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 65
* Operating System and version (desktop or mobile): Linux (desktop)
* Link to your project:

# Expected Results
Triplets containing one quarter note and one eight note should merge together. Example in GP6:
![example](https://user-images.githubusercontent.com/46634000/53248652-841dbd00-36b6-11e9-887c-e6e9e3bc3e6b.png)

# Observed Results
Triplets made of one quarter note and one eight note don't merge correctly:
![screenshot_2019-02-22 the guitar lick database 1](https://user-images.githubusercontent.com/46634000/53248688-9992e700-36b6-11e9-822c-c8e968df0513.png)
![screenshot_2019-02-22 the guitar lick database](https://user-images.githubusercontent.com/46634000/53248683-97c92380-36b6-11e9-8e37-172b5c616117.png)

# Steps to Reproduce (for bugs)
Create a tab with the following alphatex:
```
5.3.4{tu 3} 5.3.8{tu 3}
```

# Possible Solution

**Comment by Danielku15** [comment]
I changed the tuplet grouping behavior in version 0.9.6.291. I cannot promise that the new logic really reflects the way it should be according to music theory. I could not find any good explanation in which precise scenarios a tuplet is considered "complete/full" and gets brackets. 

I took Guitar Pro as reference but could not fully resemble its behavior. Anyhow most usual triplets which make sense from the theoretical definition. The default tuplets with equal durations behave correctly, and also various combinations on mixed duration tuplets seem to work now correctly. 

If you have more examples which are not working, or more theoretical input on how tuplet groups should behave on mixed durations feel free to share the input 😉
