### ISSUE TITLE
Add an option for a countdown before playback

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#242]
# Description 
When trying to play guitar along the playback of a score, it's sometimes hard to start playing at the same time the player is started. It would be nice to be able to specify some kind of countdown before the actual playback starts.

Having it both as a data/JSON option and a toggle setting would be useful (so it can be turned on/off on the fly). Also, being able to choose the number and duration of the clicks would be a plus.

# Possible Solutions

# Current Workarounds 
It's possible to simulate a countdown by inserting an empty bar at the beginning of a score and activating the metronome.

**Comment by Danielku15** [comment]
Might be a nice feature for the future, but for now as a workaround I would recommend that you simply build the countdown on your own in your user interface. 

The change is likely not easy to do in alphaTab. Playing additional audio, which is not part of the actual song, will spoil the whole system to track and notify the audio position. Easiest would be to setup a separate independent audio synthesizer internally to play such "out of song" audio items.
