### ISSUE TITLE
.alphaTab is not a function

### ISSUE THREAD

**Issue by caveandre** [CoderLine/alphaTab#243]
# Question 
Hi! I've got problems in installing alphaTab because I've followed the instructions in this article 

https://ourcodeworld.com/articles/read/399/how-to-display-guitar-pro-tabs-in-the-browser-with-javascript-using-alphatab

but I always got the error $('selector').alphaTab is not a function and I don't know why and how to solve that

Thank you inadvance

# Your environment (if applicable)

* Version used: developer
* Platform used: JavaScript
* Browser Name and Version: Chrome and Firefox Developer Edition

**Comment by Danielku15** [comment]
Hi. 
The information in this article is slighly outdated. I recommend that you grab the latest version from the CI server: https://ci.appveyor.com/project/Danielku15/alphaTab/branch/develop/artifacts

Then follow the instructions here: https://docs.alphatab.net/develop/examples/

**Comment by caveandre** [comment]
Thank you for the suggestion but even with those files I get the same error.

I tried to copy the files you have in the example pages and all work well!

Thank you!
