### ISSUE TITLE
A few questions about soundfonts

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#244]
# Question 

# Your environment (if applicable)

* Version used: 0.9.3.173
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Linux
* Link to your project:

1. I tried using some free guitar soundfonts with alphatab, without success. Is there some kind of configuration required, and if so, what is it? Or are some sounfonts simply incompatible with alphatab?

2. In the default soundfont provided with alphatex, it seems there are a lot of instruments and samples, most of which are probably not used by the player. Is there any way to remove those unused samples in order to make the file lighter? And if so, what are the exact samples used by alphatab?

3. Can alphatab work with formats other than .sf2?

**Comment by Danielku15** [comment]
1. Can you share in more detail what soundfonts you used? In general any soundfont2 file should do the job. Not all SF2 features are supported by the current audio engine which can lead to strange audio output if they are heavily used in the font. I started working on a new more lightweight and stable synthesizer. But also there modulators, chorus and reverb are missing so far as they are not easy to implement. 

2. This statement is not fully valid. You do not know for sure which instruments will be needed or not. This depends on the song/file you will open later. In general alphaTab expects the a soundfont with full general midi instruments inside. The only thing I could think of, is an API that allows you to load soundfonts without replacing any existing loaded patches. This way you can slice down the soundfonts on your own, and pass them in for loading depending on your application requirements. Feel free to file a dedicated feature request on that. 

3. No, SF2 is the only supported file format for now, and I do not have any plans to support anything different. Only SF3 with OGG Vorbis compressed samples is on the roadmap.

**Comment by cheap-glitch** [comment]
1. I tried using several free guitar soundfonts I found on the Internet (here: https://www.flstudiomusic.com/2010/02/49-guitar-soundfonts.html and here: www.flamestudios.org/free/Soundfonts), but none of them worked.

**Comment by Danielku15** [comment]
@cheap-glitch I merged yesterday a new audio synthesis engine into alphaTab. Maybe you can try again using some of the other SoundFonts you wanted to use. 

I'm closing this issue as the questions are more or less answered. If you have some concrete with or problem, feel free to open a new issue covering that topic 😉
