### ISSUE TITLE
AlphaTex, support for markers

### ISSUE THREAD

**Issue by DavidForss** [CoderLine/alphaTab#245]
Hello and thanks for a great library!!

note: I´ve edited the issue to conform to the guidelines, hope it works better now.

# Description 
A Bar Metadata Tag (or whichever solution works best) in alphaTex to use for markers.
I´ve seen chorus, verse and other section markers in the examples, but no way to do them with alphaTex.

# Possible Solutions
Similar to the other Bar Metadata Tags.
Something along the lines of:
\marker Chorus
\marker Verse 1

# Current Workarounds 
None

Thanks in advance / David

**Comment by Danielku15** [comment]
Hello. Thanks for opening this issue. For the future I would kindly ask you to follow the provided issue templates. I think it is clearly described and highlighted everywhere that I expect people to follow this templates to keep the repository organized. 

To your question: Everything that is possible in alphaTex, is already described in the documentation: https://docs.alphatab.net/develop/alphatex/ anything not described there, is also not available yet (unless I accidentally forgot to add it to the docs at least). If you have the need for new functionality not described there, (like lyrics, beat texts, sections etc.) feel free to open feature requests. This is also valid for music notation elements that might not be available at all yet (not even via GuitarPro input).

AlphaTex was not used a lot in the past, at least nobody reported it. That is the reason why not all features of alphaTab can be expressed in alphaTex. It improved quite a bit lately with some feedback and wished from people here, but it is still not "feature complete". If people have the need for certain features in their projects, I'm happy to add them, but if there is no feedback, I focus rather on other topics 😉

**Comment by Danielku15** [comment]
Markers can now be added via alphaTex. I named it rather as "section" because that's how alphaTab names it also internally. The docs are updated: https://docs.alphatab.net/develop/alphatex/bar-meta#sections
