### ISSUE TITLE
Triplet feel during playback

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#246]
# Description 
While it's possible to indicate a triplet feel in alphaTex, it only generates a visual indication. It would be great if the triplet feel was reflected in the actual playback of the score.

# Possible Solutions

# Current Workarounds 
Some kind of parser that would apply the triplet feel directly to the alphaTex code by altering the durations of the notes accordingly, before creating the tab.

**Comment by Danielku15** [comment]
Closing as duplicate of #107
