### ISSUE TITLE
Add anacruses in alaphaTex

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#247]
# Description 
Some way in alphaTex to indicate that a bar is an anacrusis (i.e. in the bar metadata), so that the player jumps directly to the next bar instead of following the time signature of the score.
Also, it would be nice if the playback could be made to ignore an anacrusis at the beginning of the score when looping.

# Possible Solutions

# Current Workarounds 
Create a bar with a shorter time signature at the beginning of the score.

**Comment by nascent** [comment]
I concur however I believe this also occurs in OSMD.
