### ISSUE TITLE
Time signature on tabs isn't vertically centered

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#249]
# Your environment

* Version used: 0.9.3-173
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox (tested on Chromium too)
* Operating System and version (desktop or mobile): Linux
* Link to your project:

# Expected Results
The time signature should be vertically centered on the staff.

# Observed Results
Just a tiny rendering bug: in tab-only mode, the time signature is at the very bottom of the staff instead of being in the middle.
![Screenshot_2019-03-25 Lick #68 (Angus Young) — The Guitar Lick Database](https://user-images.githubusercontent.com/46634000/54920071-8e73e680-4f02-11e9-9e3b-1aaabed6acda.png)

# Steps to Reproduce (for bugs)
Create an empty tab with the option `staves: { id: 'tab', additionalSettings: { rhythm: true }}`

# Possible Solution

**Comment by Danielku15** [comment]
I had a look on the version you mentioned and for me the time signature is aligned not as misaligned as for you. Improvements would be possible but in general it is fine. Can you please update your browsers to the latest versions and check again?  

Firefox
![image](https://user-images.githubusercontent.com/674916/58633682-76955600-82e9-11e9-8576-66b5a411baae.png)

Chrome
![image](https://user-images.githubusercontent.com/674916/58633702-86ad3580-82e9-11e9-87e1-dd3a0d68ff57.png)

**Comment by Danielku15** [comment]
Closed as there was no response. For me the time signature is fine.
