### ISSUE TITLE
Choppy Playing On Mobile Android Devices

### ISSUE THREAD

**Issue by matt15wish** [CoderLine/alphaTab#251]
While playing the demo at https://www.alphatab.net/ I am experiencing choppy playback with my android device. I want to incorperate this into a little react webapp i'm making but I can't get this to work running on a mobile phone.
For reference I have a samsung A5 (2017) version. But I have also tried it on emulators (Android Studio running a WebView) on the pc with the exact same results

**Comment by Danielku15** [comment]
Please follow the issue templates.
