### ISSUE TITLE
Can you add a simple track display? 

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#252]
Can you add umbered musical notation track display? In addition, two tracks of music, one showing six-line spectrum, one showing simple or five-line spectrum?

**Comment by goodgame365** [comment]
1 1 5 5 | 6 6 5 -| 4 4  3 3 | 2 2 1 -|

**Comment by Danielku15** [comment]
Please ensure you use the correct issue template and include all details. I decided to not follow up on issues that do not follow the structure
