### ISSUE TITLE
Seek to Markers/sections

### ISSUE THREAD

**Issue by BorninDusk** [CoderLine/alphaTab#254]
# Description 

I want to be able to quickly seek to specific parts of the song ie Verse 1, Solo, Chorus etc by simply pressing on a button marked by its name.  These sections could be displayed in a long bar at the top of the page and below the current play bar. Songs with lots of sections may look messy but each section bar could display a short name or slightly cut off text depending on the length of the section. I think it would be mainly beneficial to move the play needle to the start of the section although it would be great if you could seek to different bars within the selected section, similar to how ultimate guitar do it.

# Possible Solutions

Ultimate guitar have this and they call the sections popular parts but they are just text created in Guitar Pro. I believe Guitar Pro 7 also has this feature.
https://tabs.ultimate-guitar.com/tab/metallica/nothing_else_matters_guitar_pro_225441 

# Current Workarounds 

Unsure

**Comment by Danielku15** [comment]
Hello, sorry for the quite delayed answer. My private life was very busy the last months and I did not have a lot time for alphaTab. 

I assume you are working with the Web/JavaScript version of alphaTab? In general this functionality is already possible by today and easily achievable with a bit knowledge on what the alphaTab API provides. 

Whenever a file is loaded, you receive a `alphaTab.loaded` event on the element. In this event the whole [data model](https://docs.alphatab.net/develop/api/AlphaTab.Model/) can be accessed. The [Advanced Usage](https://docs.alphatab.net/develop/examples/general/advanced) example uses this data model to build up a track selector. To build a "marker list" you would simply iterate through the `Score.MasterBars` list and collect the sections. 

With the list of sections available, you can tell alphaTab player to seek to the matching midi tick position. 

Here is a working Fiddle that shows this logic: https://jsfiddle.net/danielku15/u9467vft/ I think the code is mostly self-explaining. The important lines are: 

```js
function createSectionSelector(masterBar) {
    const sections = $('#sections');
    
    const section = $('<a href="#"></a>');
    section.text(masterBar.Section.Text);
    section.on('click', function(e) {
      e.preventDefault();
      at.alphaTab('player').set_TickPosition(masterBar.Start);
    });
    
    sections.append(section);
}

at.on('alphaTab.loaded', function(e, score) {
  // collect bars that start a section 
  for(let i = 0; i < score.MasterBars.length; i++) {
      if(score.MasterBars[i].Section != null) {
          createSectionSelector(score.MasterBars[i]);
      }
  }
});
```

**Comment by BorninDusk** [comment]
Not a problem, thanks for taking the time to send a concise answer. I'll see about implementing this soon into my own site.

**Comment by Danielku15** [comment]
Closing this issue as this feature is supported by custom code and will not get a feature within alphaTab directly.
