### ISSUE TITLE
CSS for Voicings

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#257]
# Question 

I would like to know whether it is possible to use CSS for notes and symbols that are contained in different voicings, i.e. 1-4

# Your environment (if applicable)

* Version used: (developer branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Chrome latest: 
* Windows 10 (desktop):

I don't have a link to a project right now, just a general question if I may.

Kind regards

**Comment by Danielku15** [comment]
As of today there exists only a setting to set the color for the 1st voice, and all others. Also for some other elements the color can be changed: 
https://jsfiddle.net/danielku15/h4svmw5j/8/

As of today CSS is not the preferred styling system for alphaTab. This has multiple reasons: 

- CSS is only available for web, but alphaTab has also versions for desktop. We need a unified styling system. 
- CSS is not working well for HTML5 canvas based rendering too. 
- CSS has too much flexibility, all its aspects cannot be considered in the rendering process. 

If you need more precise coloring for each voice individually, please enter a feature request for having a setting to color individual voices. Also feel free to add a second feature request to improve the situation with CSS styling if you like.

**Comment by Danielku15** [comment]
Closing this issue with the information above. CSS coloring of elements is not yet supported. Related defects on CSS styling are: #263 #291

If nothing covers yet your needs, please file a feature request describing exactly what feature you'd like to have.
