### ISSUE TITLE
Error on Resize Before Load

### ISSUE THREAD

**Issue by twodee** [CoderLine/alphaTab#258]
# Your environment

* Version used: master
* Platform used: Javascript
* Rendering engine used: SVG
* Browser Name and Version: Chrome 75
* Operating System and version: macOS 10.12.6
* Link to project: https://twodee.org/deltaphone

# Expected Results

I have a project that generates MusicXML using a blocks programming language and then renders it using alphaTab. When the code editor is resized, this in turn resizes the neighboring alphaTab div. Even if no score has been loaded yet, I expect the alphaTab div to gracefully handle being resized.

# Observed Results

Currently when I resize the div before loading a score, I see this error:

```
Uncaught TypeError: Cannot read property 'length' of null
    at alphaTab.rendering.ScoreRenderer.$hx_exports.alphaTab.rendering.ScoreRenderer.Invalidate (AlphaTab.js:27127)
    at alphaTab.rendering.ScoreRenderer.$hx_exports.alphaTab.rendering.ScoreRenderer.Resize (AlphaTab.js:27152)
    at alphaTab.platform.javaScript.AlphaTabWebWorker.$hx_exports.alphaTab.platform.javaScript.AlphaTabWebWorker.HandleMessage (AlphaTab.js:1917)
    at f (AlphaTab.js:36951)
```

It appears that `this.Tracks` is null if no score has been loaded.

# Steps to Reproduce (for bugs)

Run this minimal reproducible example:

```
<!DOCTYPE html>
<html>
<head>
  <title>...</title>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="alphaTab/Build/JavaScript/swfobject.js"></script>
  <script src="alphaTab/Build/JavaScript/AlphaTab.js"></script>
</head>
<body>

<div id="score" data-player="general_user.sf2"></div>

<script>

$('#score').alphaTab({
  width: -1,
  staves: 'score',
  layout: {
    mode: 'page',
  }
});

$('#score').width(100);
window.dispatchEvent(new Event('resize'));

</script>
  
</body>
</html>
```

# Possible Solution 

Change the code in Invalidate that produces the Javascript line

```
if(this.Tracks.length == 0) {
```

to produce this line

```
if(!this.Tracks || this.Tracks.length == 0) {
```

**Comment by Danielku15** [comment]
Thanks a lot for reproting this and providing the solution. I will try to provide a fix by this weekend.

**Comment by Danielku15** [comment]
Looks like you are using an outdated / wrong version of alphaTab. Please use the `develop` branch. As of today and until the official 1.0 release the master branch cannot be considered stable and up-to-date. 

The bug is already fixed on the develop branch.
