### ISSUE TITLE
Support for Bass Guitar

### ISSUE THREAD

**Issue by chris-saunders** [CoderLine/alphaTab#259]
# Description 
As a user I would like to be able to render bass guitar sheet music from alphatex

# Possible Solutions
A new option alongside guitar and grand staff to display tabs for a bass guitar.

# Current Workarounds 
Currently I think it is possible to render the sheet music for bass guitar, but no tabs

**Comment by Danielku15** [comment]
Hello Chris. 
Did you have any look on the documentation? It is the core of alphaTab to show tabs:
https://docs.alphatab.net/develop/features/guitar-tabs

Not sure what is missing from your expectation.

**Comment by chris-saunders** [comment]
I understand alphatab shows guitar tabs, what I mean is 4 string bass tabs. Something like this
![Screen Shot 2019-07-26 at 9 57 30 AM](https://user-images.githubusercontent.com/22945851/61964815-0a06a280-af8c-11e9-8780-28858f588bfc.png)

**Comment by Danielku15** [comment]
As described in the documentation any kind of string variation is supported. It depends on your input format how many strings are displayed: 
- If you use Guitar Pro input files, it will show the number of strings as the individual tracks report it. 
- If you use alphaTex the `\tuning` metadata defines the number of strings and their tuning. 
https://docs.alphatab.net/develop/alphatex/metadata
- If you use MusicXML the `<staff-lines>` tag defines the number of strings and the `<staff-tuning>` the tuning of them. 
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-staff-lines.htm
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-staff-tuning.htm

**Comment by chris-saunders** [comment]
Thank you very much Daniel! Sorry I missed the options for this. I think it would be helpful to have an example for bass guitar out there for future users so no one else makes the same mistake as me.
