### ISSUE TITLE
Options for automatic scrolling during playback

### ISSUE THREAD

**Issue by chris-saunders** [CoderLine/alphaTab#260]
# Description 
Currently when playing back sheet music the page will automatically scroll to keep the current measure at the top of the page. However if the website has a header this can obscure the current measures. 
I would like it if we had some options in how the page scrolls.

# Possible Solutions
Have an option to disable automatic scrolling when we create the score. Potentially have an argument or parameter that allows us to specify a Y value to adjust the score. Say keeping the top measure 10 pixels down from the top.

# Current Workarounds 
None that I am aware of

**Comment by Danielku15** [comment]
Hi Chris. 
There is a setting to specify an additional x/y offset that is then considered on scrolling. 

Data attributes: 
```html
<!-- Set X/Y offset together -->
<div id="alphaTab" data-player-offset="30"></div>
<!-- Set X/Y offset separately -->
<div id="alphaTab" data-player-offset="[0,30]"></div>
```

JavaScript: 
```javascript
$('#alphaTab').alphaTab({
   playerOffset: 30
});
$('#alphaTab').alphaTab({
   playerOffset: [0,30]
});
```

**Comment by chris-saunders** [comment]
This is exactly what I wanted! Thank you very much. Sorry I didn't see this option
