### ISSUE TITLE
Sample "AlphaTab.Sample.WinForms" crashing on run in VS 2012

### ISSUE THREAD

**Issue by GitterHubber** [CoderLine/alphaTab#271]
I've succesfully built the sample "AlphaTab.Sample.WinForms" in VS2012, however when I try to run it, it crashes on 

![AlphaTab Control Crash](https://user-images.githubusercontent.com/2816034/63523278-789d3880-c517-11e9-82ac-baefc069dcb5.png)

Do I need any other dependencies to get this to work. I have .NET 4.7.2 installed and selected in VS2012.

I could not run your sample project as is since it was created in VS 2017, so I made a new Winforms projects and then added all the sample files into it. and then built it.

# Your environment (if applicable)

* Version used: development branch
* Platform used: C#
* Rendering engine used: SVG (default), Not sure about this
* Browser Name and Version: Running on VS2012
* Operating System and version (desktop or mobile): Win 7, 64 bit, desktop
* Link to your project:

**Comment by Danielku15** [comment]
Thanks for reporting this issue, it should be fixed with the latest version on develop. If you still experience similar issues please also add the full details of the exception to easier catch the issue.

**Comment by GitterHubber** [comment]
Thanks for fixing it, would I need to download the sources or are the binaries fixed too?

**Comment by Danielku15** [comment]
Every change made to alphaTab is directly built on Appveyor and available for download. Or you simply consume the NuGet package from the development MyGet feed and update to the latest version: https://www.myget.org/feed/coderline/package/nuget/AlphaTab

**Comment by GitterHubber** [comment]
So I downloaded v0.9.5.241 but when I try to drag the "AlphaTabControl" component from Toolbox on to my Form I still get errors.

![image](https://user-images.githubusercontent.com/2816034/64479900-786d9000-d1db-11e9-8652-6c364d9cd257.png)
