### ISSUE TITLE
Unable to change tracks

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#277]
# Question 
I am unable to change tracks by clicking on an item in the Tracklist and am wondering why.

# Your environment (if applicable)

* Platform used: JavaScript or C#
* Rendering engine used: SVG
* Chrome/Firefox 
* Operating System Windows 10
* Link to your project: http://acousticremedy.com.au/alphatab1/

The issue might be in the following code:

```js
var tracks=[];
at.on('alphaTab.loaded',function(e,score){
const trackList=$('#tracklist');

// build list item for track
for(var i=0;i<score.tracks.length;i++){
const li=$('<li></li>').data('track',score.tracks[i].index);

// show/hide button and track title
const title=$('<span></span>');
li.append(title);
title.append(score.tracks[i].name);
				
// render new tracks
title.on('click',function(e){
const track=$(this).closest('li').data('track');
tracks=[track];
at.alphaTab('tracks',tracks);
});
```
since I had to change "Tracks" to "tracks" to be able to render a tracklist but this also stopped my being able to click on the tracknames and thus re-rendering isn't possible.

Thanks again for your tireless efforts, it is very much appreciated.

**Comment by Danielku15** [comment]
Sorry, for the long delay, I'm currently quite busy in my private life and do not have much time for alphaTab. 

This indeed looks like a bug in the jQuery plugin. Also the example on our demo site is broken. Unfortunatly a lot of things lately got broken due to a bigger rework on the API layer for the final release of 1.0. I did not yet have the time to do the full regression testing.

**Comment by Danielku15** [comment]
A small update on this topic. It is not really a bug but a breaking change to make the jQuery plugin consistent with the remaining API. 

The `tracks` method is now only for getting the tracks: https://docs.alphatab.net/develop/reference/api/tracks

Use the functions `renderScore` or `renderTracks` to update the tracks that you want to display: 
https://docs.alphatab.net/develop/reference/api/renderscore
https://docs.alphatab.net/develop/reference/api/rendertracks

**Comment by nascent** [comment]
Hi Daniel,

I am able to render a track but it creates new instances in the tracklist, which I will discuss in another post.
