### ISSUE TITLE
How do you even get started?

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#278]
# Question 

# Your environment (if applicable)

* Version used: (master branch)
Master branch
* Platform used: JavaScript or C#
Javascript
* Rendering engine used: SVG (default), HTML5 or GDI
HTML5
* Browser Name and Version: 
Firefox 69.0
* Operating System and version (desktop or mobile):
Desktop

I read through your documentation.  I'm just trying to do something nice and simple like I saw at this site https://docs.alphatab.net/master/examples/general/simple or https://docs.alphatab.net/master/examples/general/alphaTex and just open the HTML locally.  It just never renders.  Do you have documentation somewhere that's a step-by-step guide on how to actually get this working?  Or, do you have an actual example HTML page that people can download and start with?

**Comment by Danielku15** [comment]
It sounds to e that you are quite a beginner in web development. Please note that as of today alphaTab is a library meant for developers to integrate it into their products. It works like most of the other libraries in the market. You create a DOM elements on the page, and use the API to initialize the component on top. Then you use the additional APIs of the library to integrate the features you want to have on your website/app.  

AlphaTab is heavily based on Ajax and Web Workers which do not work when simply opening an HTML file locally. There are tons of browser security restrictions there. You need to use alphaTab on a website running on a proper web server to ensure it is running properly. We do not maintain a documentation for beginners on web development to guide you from 0 to an application that does what you expect, this is simply not maintainable in a reasonable fashion.

**Comment by dgriessler** [comment]
I am most definitely a beginner at web development. I suppose the best thing to do is to find a course on Udemy or similar platform in web development before attempting to use your project? It sounds like I should look into Ajax and Web Workers as well?

**Comment by nascent** [comment]
Hi,

Maybe you could make a start by integrating the JQuery library into a single page, which is available via CDN.

Hope that helps.

**Comment by Danielku15** [comment]
@dgriessler I would recommend a goot start for a beginner is to learn a bit about jQuery in general. alphaTab does not necessarily need jQuery but to understand certain concepts and to "get started" it helps as it makes things a bit easier. 

Then checking out some more other libraries might also help. alphaTab is quite a small library (regarding contributors) and hence all the docs and tutorials are rather limited. But bigger libraries  have amazing docs that even partly start at the very basics. The following libraries should give you a good "hands-on":

- https://datatables.net/ 
- https://d3js.org/
- https://www.chartjs.org

Once you feel a bit more comfortable on the "low-levels" of Web Development I bet it will be really easy to start using alphaTab. The raw reference documentation with the available features to configure alphaTab and interact with it, is the reference documentation: https://docs.alphatab.net/develop/reference/

The [features demo](https://docs.alphatab.net/develop/features/) rather gives an insight about the capabilities regarding the music notation itself. The [examples ](https://docs.alphatab.net/develop/examples/) try to give a bit more a "single-usecase" demo on how to tell alphaTab to do some more common things. And just for completeness: the [alphaTex ](https://docs.alphatab.net/develop/alphatex/) docs explain the built-in language to write music notation. 

For [the future](https://github.com/CoderLine/alphaTab/issues/109) it is planned to provide a bit a more drop-in component for websites and apps that will provide a full setup of alphaTab out-of-the-box. But until then it is rather a low-level API for devs to integrate it in their own fashion to websites and apps.

**Comment by dgriessler** [comment]
Thank you both, @Danielku15 and @nascent for the advice.  I'll look into those other libraries, JQuery, and CDN.
