### ISSUE TITLE
Metronome playing even when metronomeValue is set to 0

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#279]
# Your environment

* Version used: 0.9.5.241 (latest)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox & Chromium (latest versions)
* Operating System and version (desktop or mobile): Linux desktop

# Expected Results
The metronome should not be playing if its volume is set to zero.

# Observed Results
On Chromium, the metronome starts playing over the playback immediately.
On Firefox, the metronome starts to play only the second time, whether the playback is looped or replayed manually.

# Steps to Reproduce (for bugs)

Minimal HTML and JS script :

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<div id="alphatab-container"></div>
		<script src="alphatab-0.9.5.241.js"></script>
		<script src="script.js"></script>
	</body>
</html>
```
```javascript
(function()
{
	let settings = {
		player: 'default.sf2',
	};

	let alphatab = new alphaTab.platform.javaScript.AlphaTabApi(document.getElementById('alphatab-container'), settings);

	alphatab.tex(':8 1.6 2.6 3.6 4.6 1.5 2.5 3.5 4.5 | 1.4 2.4 3.4 4.4 1.3 2.3 3.3 4.3');
	alphatab.isLooping = true;
	alphatab.metronomeValue = 0;

	alphatab.addReadyForPlayback(function() {
		alphatab.play();
	});
})();
```

**Comment by Danielku15** [comment]
Be sure to set the metronome value after it was signaled that it is ready then it should work. 

I think it should be possible to support setting those values before the player is ready, but currently there are some checks in place which might prevent it.
