### ISSUE TITLE
Playback cursor is not shown during playback

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#280]
# Your environment

* Version used: 0.9.5.241 (latest)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox & Chromium (latest)
* Operating System and version (desktop or mobile): Linux desktop

# Expected Results
The playback cursor should appear when playback starts.

# Observed Results
The playback cursor doesn't appear, and the note currently played is not highlighted either.

# Steps to Reproduce (for bugs)
Minimal HTML and JS:
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<div id="alphatab-container"></div>
		<script src="alphatab-0.9.5.241.js"></script>
		<script src="script.js"></script>
	</body>
</html>
```
```javascript
(function()
{
	let settings = {
		player: 'default.sf2',
		cursor: true,
	};

	let alphatab = new alphaTab.platform.javaScript.AlphaTabApi(document.getElementById('alphatab-container'), settings);

	alphatab.tex(':8 1.6 2.6 3.6 4.6 1.5 2.5 3.5 4.5 | 1.4 2.4 3.4 4.4 1.3 2.3 3.3 4.3');

	alphatab.addReadyForPlayback(function() {
		alphatab.play();
	});
})();
```

**Comment by dgriessler** [comment]
A few observations from looking at his example: https://docs.alphatab.net/master/assets/files/player.html
He includes lines of css which style both the bar cursor and the beat cursor on the screen:
    .barCursor { /* Defines the color of the bar background when a bar is played */
        background: rgba(255, 242, 0, 0.25);
    }

    .selectionWrapper div { /* Defines the color of the selection background */
        background: rgba(64, 64, 255, 0.1)
    }

    .beatCursor { /* Defines the beat cursor */
        background: rgba(64, 64, 255, 0.75)
    }
    
    .atHighlight * { /* Defines the color of the music symbols when they are being played (svg) */
        fill: #0078ff;
        stroke: #0078ff;
    }
Even when I added that, I still didn't get the cursor to appear.  Looking further, I saw that at least for my project the cursor is failing to include the css properties that will place it over the starting note.  When I searched in the JavaScript, it looks like he updates the position of the cursor in cursorUpdateBeat.  cursorUpdateBeat is only called from cursorUpdateTick.  cursorUpdateTick won't call cursorUpdateBeat if tracks.length==0 at seen on line 717.  In my project at least, I still have 0 tracks.  Looking at his example posted above with a watch statement, you can see that tracks.length == 1 so the cursor's position is updated.  Verify that you have more than 0 tracks and let me know if that fixes it.  I don't know how to add tracks to mine...

**Comment by cheap-glitch** [comment]
> Verify that you have more than 0 tracks and let me know if that fixes it.

No, pretty sure this is a bug. I tried loading both a GP5 score and some alphatex, and while the playback works fine, there is no cursor nor any highlighting on the notes (even with the CSS styles included).

Btw when inspecting the `tracks` property on the API object, it always is an empty array. Maybe that's the root of the problem.

**Comment by cheap-glitch** [comment]
After some digging, it seems the issue appeared with release 0.9.4.226. The following snippet works as it should with 0.9.4.225, but produces the bug with 0.9.4.226:
```js
(function()
{
	let settings = {
		file: 'score.gp5',
		tracks: [0],

		player: 'default.sf2',
		cursor: true,
	};

	const tab      = document.getElementById('alphatab-container');
	const alphatab = new alphaTab.platform.javaScript.AlphaTabApi(tab, settings);

	tab.addEventListener('alphaTab.playerReady', function() { alphatab.Play(); });
})();

```

**Comment by Danielku15** [comment]
There was an issue internally with initializing the track list. Should be fixed now

**Comment by marriusco** [comment]
I see another thing related to https://docs.alphatab.net/master/assets/files/player.html
If i scroll down the tab towards last lines and click the beat cursor have a tendency to 
offset down few pixels.
