### ISSUE TITLE
Guitar pro sounds (RSE) and soundfonts

### ISSUE THREAD

**Issue by BorninDusk** [CoderLine/alphaTab#281]
# Question 

When I create a track in guitar pro with different instruments and sounds with guitar pro's soundbank, how does Alphatab decide which sound in the soundfont to use? Say I have 3 different distorted guitars in my sound font, 1 for blues, soft rock and metal, how does Alphatab know which one to pick? Is it as simple as changing the name of the preset in guitar pro?

# Your environment (if applicable)

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version:  Chrome latest
* Operating System and version (desktop or mobile): Linux, Ubuntu 18.04
* Link to your project:

**Comment by Danielku15** [comment]
AlphaTab uses the configured midi instrument to decide which instrument to choose from the specified SoundFont. AlphaTab uses SoundFont2 files to render the audio and this file can be configured like the GuitarPro file. 

AlphaTab is fully based on midi programs and does not utilize and RSE related information. 

I hope this answers your question.

**Comment by Danielku15** [comment]
Closing this issue with the following details: 

AlphaTab uses the Midi Program that is stored within the Guitar Pro file. It can be specified when selecting the midi settings in Guitar Pro: 
![image](https://user-images.githubusercontent.com/674916/71283186-c27c1b00-235f-11ea-884f-959307d5c7b3.png)

Guitar Pro 6 and 7 have multiple possible XML tags in the GPIF.xml for this: 

* GPIF/Tracks/Track/Sounds/Sound/MIDI/Program
* GPIF/Tracks/Track/MIDISettings/Program
* GPIF/Tracks/Track/MidiConnection/Program
* GPIF/Tracks/Track/GeneralMidi/Program

Any kind of RSE information is not considered as it is specific to the audio engine and samples available only for of Guitar Pro .
