### ISSUE TITLE
AlphaTab script not working - looking for direction

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#282]
# Question 

How do I get AlphaTab to work correctly since jQuery is loading correctly and I am following an AlphaTab example as closely as I can?

Last time I asked for some guidance and I have covered a lot of basics in HTML and JavaScript.  I returned to the examples that you have posted https://demo.alphatab.net/index.html#general/simple.html.  You had mentioned that it needs to run in a webserver and so I tried both running a local webserver using SimpleHTTPServer but that also failed to work.  I thought maybe Github pages might solve the problem, but I still can't seem to get it to work.  Please excuse my ignorance if I still am not hosting the HTML in the right location and I welcome any and all help that you can provide.

I found a helpful script online that confirms that jQuery is loaded as expected, and I even made sure I had the same jQuery version that you have loaded in your basic example.  I put the scripts in the same order as I saw in the HTML on your example pages as well.  The console reports no errors but only mentions a warning similar to the one you have.  I am not fully comfortable with debugging in JavaScript, but I tried setting some breakpoints in your AlphaTab script but didn't know where to place them and my attempts to understand the process were not successful.

I have attached a link to the github source code which I have been trying to run and the URL for opening the github page.  It's basically a copy of your latest code and index.html which is supposed to actually structure it correctly.  I assume the error is localized in index.html and that I am missing something from the process.

Like I mentioned, I apologize again if I am asking questions that can be answered by having a better understanding of JavaScript and jQuery.  I am still going through a course that will cover more basics and I appreciate any help you can provide, even if that is only pointing me in the right direction.

# Your environment (if applicable)
Github pages
* Version used: (master branch)
master branch
* Platform used: JavaScript or C#
JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
SVG I guess
* Browser Name and Version: 
Firefox 69.0.1
* Operating System and version (desktop or mobile):
Windows x64 Desktop
* Link to your project:
https://github.com/dgriessler/TestHost/tree/gh-pages
https://dgriessler.github.io/TestHost/

**Comment by cheap-glitch** [comment]
Looking at the example you provided, the problem doesn't come from alphatab itself, which is working fine, but from the file you provided. It's not an actual Guitar Pro file, it's just alphatex -- so basically plain text.
So you should either provide alphatab with an actual GP5 file (you can find plenty on the web) or, if you want to render a score using alphatex, look into [this example](https://docs.alphatab.net/develop/examples/general/alphaTex) and [the doc of this method](https://docs.alphatab.net/develop/reference/api/tex).

**Comment by dgriessler** [comment]
I will look into the doc for the method.  When I changed the index.html script to use the example you suggested, all that happens when you load the page is that the text in the alphaTab div is displayed but not rendered by the alphaTab script.

**Comment by cheap-glitch** [comment]
> When I changed the index.html script to use the example you suggested, all that happens when you load the page is that the text in the alphaTab div is displayed but not rendered by the alphaTab script.

Did you make sure to add the attribute `data-tex="true"` on the element containing the alphatex? Otherwise alphatab won't know it's supposed to load it.

**Comment by dgriessler** [comment]
> 
> 
> > When I changed the index.html script to use the example you suggested, all that happens when you load the page is that the text in the alphaTab div is displayed but not rendered by the alphaTab script.
> 
> Did you make sure to add the attribute `data-tex="true"` on the element containing the alphatex? Otherwise alphatab won't know it's supposed to load it.

Yeah, I copied the div element exactly as displayed and included the quoted JavaScript.  I also was trying including the recommended JavaScript from the doc of this method you linked to both before and after the existing call to alphaTab, but I don't see any change in the output, still just the text.

**Comment by dgriessler** [comment]
I got some output this time.  I had accidentally put the suggested javascript code in a block labeled with a type alpha-tex not javascript.  When I made it type javascript, I now get actual output.  The only issue now is that it is having some trouble rendering so I'll need to debug.

**Comment by cheap-glitch** [comment]
> The only issue now is that it is having some trouble rendering so I'll need to debug.

The [logging setting](https://docs.alphatab.net/develop/reference/property/loglevel) might be helpful.

**Comment by dgriessler** [comment]
> 
> 
> > The only issue now is that it is having some trouble rendering so I'll need to debug.
> 
> The [logging setting](https://docs.alphatab.net/develop/reference/property/loglevel) might be helpful.

Great, thank you for the link.  I'll keep trying to figure out what's going on.

**Comment by dgriessler** [comment]
Alright, so now it runs without throwing errors and almost renders the score.  The only thing it is failing to do is load note heads, but it doesn't throw an error.

**Comment by cheap-glitch** [comment]
> and is missing the rest of the general music notation

It's because alphaTab can't find the font it needs to render the musical symbols. This font (Bravura) is shipped with the code, so you just have to place the folder named _Font_ at the location of the alphatab script (that's where it expects the font to be, but you can change that, cf. the doc).

**Comment by dgriessler** [comment]
I moved the Font folder in and it worked as you suggested.  Thank you @cheap-glitch for all your time and help!  I very much appreciate it.  Now to go through the documentation and figure out playback, modification, and everything that it can do...
