### ISSUE TITLE
How to represent Lyrics

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#283]
# Question 

I've got a basic score rendering as expected.  I was reading through the documentation and saw there is a way to add lyrics to a piece of sheet music. From looking at some of the prior issues, it looks like you might have implemented it to parse the Guitar Pro format which includes lyrics.  Is there another way to include lyrics?  What would be the format in the html?  Do you have to import from Guitar Pro format to get lyrics?

# Your environment (if applicable)

* Version used: (master branch)
master branch
* Platform used: JavaScript or C#
JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
SVG
* Browser Name and Version: 
Firefox 69.0.1
* Operating System and version (desktop or mobile):
Windows x64 18362.356 desktop
* Link to your project:
https://dgriessler.github.io/TestHost/

**Comment by Danielku15** [comment]
Currently lyrics in textual form are supported in case they are included in the loaded file itself. Currently there is no second source of lyrics that you can specify or an API to pass it in. But for all supported input formats the lyrics are loaded as of today:
- Guitar Pro files have them embedded. 
- For alphaTex you can use the `\lyrics` meta. I just realized that docs are missing. https://jsfiddle.net/danielku15/5kwgmLuf/1/
- For MusicXML the `lyric` tag is considered. 

If you would like to apply custom lyrics on top of a loaded file, feel free to file a feature request explaining what your wish would be.

**Comment by dgriessler** [comment]
That's exactly what I was looking for, thank you for the help.
