### ISSUE TITLE
Features stoped working with new version.

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#284]
### Your environment
Version used: master
Platform used: JavaScript
Rendering engine used: SVG (default),
Browser Name and Version: Newest Chrome
Operating System and version (desktop or mobile): Windows 10
Link to your project:
### Expected Results
Can not change visible track. Volume change is not working as expected. 
I would like to do something similar to below example created by you some time ago. Unfortunately it is not working with the newest JS version. https://demo.alphatab.net/index.html#general/advanced.html
### Observed Results
I updated JS, to the newest code. Some features stopped working.
1. It is not possible to change track. I used to change track like:
`updateSelectedBar: function (index) {
  var tickCache = at.alphaTab("getTickCache");
  var scope = angular.element(dom.playerFooter).scope();
  var mb = scope.score.masterBars[index];
  var realStart = tickCache.getMasterBarStart(mb);
  at.alphaTab("tickPosition", realStart);
},`
But it is not working anymore.
2. Changing volume works a bit strange. It seems volume from 1-16 is the same and 0 is mute.
###Steps to Reproduce (for bugs)
Try change volume or track for this example - but with newest alphaTab.js
https://demo.alphatab.net/index.html#general/advanced.html
### Possible Solution
Extend API to allow change visible track on fly

**Comment by nascent** [comment]
I believe the problem is incompatibility with the latest version of JQuery.

For myself, I am having the same issues you are having, plus I cannot change playback speed, as well engaging and disengaging the Metronome is unreliable. In addition, muting/soloing individual tracks is no longer possible; not even for a single track.
