### ISSUE TITLE
Staves Configuration

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#285]
# Question 
Is it possible to change staves in fly? I would like to change staves-tab to tab with rytm in fly.

* Version used: (master)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version:  Newest chrome

**Comment by cheap-glitch** [comment]
Yes, it's possible to change the type of score on the fly, see the doc: [https://docs.alphatab.net/develop/reference/property/stavesid](https://docs.alphatab.net/develop/reference/property/stavesid)
Don't forget to call `updateSettings()` and `render()` after any changes to the settings of an alphatab instance to actually render the changes on the page.

**Comment by yaras6** [comment]
Thanks a lot. It is working perfect. Sometimes I have problem to find something in documentation, but I love alphaTab project

**Comment by yaras6** [comment]
First call works fine for me but second throws error
```
Uncaught TypeError: Cannot read property 'index' of undefined
    at alphaTab.audio.MidiTickLookup.$hx_exports.alphaTab.audio.MidiTickLookup.findBeat (AlphaTab.js?11:7927)
    at AlphaTab.js?11:718
    at AlphaTab.js?11:35160
```

My code for that is
```
('[data-staves]').click(function (e) {
    var mode = $(this).data("staves");
    var at = $('#alphaTab');
    var config = {
        id: 'default',
        additionalSettings: {
            rhythm: false
        }
    };
    if (mode === "tab") {
        config = {
            id: 'tab',
            additionalSettings: {
                rhythm: true
            }
        };
    }
    at.alphaTab('settings').staves = config;
    at.alphaTab('updateSettings');
    at.alphaTab('render');
});
```
Any sugestions?

**Comment by yaras6** [comment]
And actually, which is recomended JS library? Master or develop? Switching tabs not working in master, but player seems not be stable in develop, so I am confused a bit.

**Comment by Danielku15** [comment]
Currently the recommended branch is `develop` as described in the readme:
![image](https://user-images.githubusercontent.com/674916/66698758-fb08d400-ece0-11e9-9062-ed05e18773f5.png)

There is no offical stable release of alphaTab at all. Develop is the most latest version and just lately quite some things unintentionally broke. Usually I also try to keep develop as stable as possible but some bigger reworks I was not able to fully re-test yet. 

Regarding the reported problem I'll try to investigate why multiple switching might not work. The code looks fine but there might be an issue with updating the internal caches.

>In my app in develop, tab cursor not working. On your site, example displays nothing:

The cursor problem was reported separately and was fixed today.

**Comment by Danielku15** [comment]
I gave it a try and with the latest version changing the profile works for me without errors: 
https://jsfiddle.net/danielku15/epkud9jv/

Can you try to reproduce the example in a standalone fiddle?

**Comment by yaras6** [comment]
Thanks for fiddle. It works, but unfortunately develop version is really unstable in my opinion. Because of this I will stay in master version for some time.

**Comment by yaras6** [comment]
@Danielku15  your fiddle stopped working. I noticed that property name has been changed.
I am not sure how I can update settings because   **at.alphaTab('updateSettings')** not working anymore.

Could you make this fiddle working again https://jsfiddle.net/danielku15/epkud9jv/, or advice me what should I change in this code: 

`
  $('[data-staves]').click(function (e) {
      var mode = $(this).data("staves");
      at.alphaTab("settings").display.staveProfile = mode;
      at.alphaTab('updateSettings');
  });
`

I have modes like **scoretab** and **tab**

**Comment by Danielku15** [comment]
If you directly interact with the settings object you need to follow the data types of the model otherwise it will break the model integrity. [`staveProfile`](https://docs.alphatab.net/develop/reference/property/display-staveprofile) is an enumeration which is an integer value internally. Filling in values like `scoretab` or `tab` will break it. 

You have 2 possibilities to solve this issue: 

1. Use the numeric values of the stave profile instead of the string values. 
2. Use `settings.fillFromJson({ display: { staveProfile: mode } })` to benefit from the string mapping. 


![image](https://user-images.githubusercontent.com/674916/80867264-a84e3400-8c93-11ea-9c41-f802e4107bea.png)
(https://docs.alphatab.net/develop/reference/property/)

**Comment by yaras6** [comment]
Thanks @Danielku15

Finally, I made it working again 

```
$('[data-staves]').click(function (e) {
    atApi.settings.fillFromJson({
        display: {
            staveProfile: $(this).data("staves")
        } 
       
    });
    atApi.updateSettings();
    atApi.render();
});
```

**Comment by goodgame365** [comment]
$('[data-staves]').click(function (e) {
    atApi.settings.fillFromJson({
        display: {
            staveProfile: $(this).data("staves")
        } 
       
    });
    atApi.updateSettings();
    atApi.render();
});

> 谢谢@ Danielku15
> 
> 最后，我又使它工作了
> 
> ```
> $('[data-staves]').click(function (e) {
>     atApi.settings.fillFromJson({
>         display: {
>             staveProfile: $(this).data("staves")
>         } 
>        
>     });
>     atApi.updateSettings();
>     atApi.render();
> });
> ```

you good,thank

**Comment by goodgame365** [comment]
up to 1.3.0
now  fillFromJson is erro It's :

Uncaught TypeError: at.settings.fillFromJson is not a function

why
