### ISSUE TITLE
How do you place crescendo and decrescendo in music?

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#286]
# Question 

How do you place crescendo and decrescendo in music?  I looked through the documentation and don't see any documentation for it.  It looks like there some mentions of crescendo in the importer though so I assume it is possible.

# Your environment (if applicable)

* Version used: (master branch)
master branch
* Platform used: JavaScript or C#
JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
SVG
* Browser Name and Version:
Firefox 69.0.1 
* Operating System and version (desktop or mobile):
Windows x64 18362.356 desktop
* Link to your project:
https://dgriessler.github.io/TestHost/

**Comment by Danielku15** [comment]
I just double checked and it seems crescendo and decrescendo are only supported with Guitar Pro 6 and 7 files. If you want to specify it with alphaTex (as I assume from your project link) it is not yet supported. Feel free to open a separate feature request for that.

**Comment by dgriessler** [comment]
Alright, I'll open a feature request.  Thanks
