### ISSUE TITLE
Adding crescendo and decrescendo using alphaTex

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#288]
# Description 

I would like to be able to add crescendo and decrescendo markings using alphaTex.

# Possible Solutions

The user places the notation by specifying a start beat, call it x, in a measure and an end beat, call it y, with the requirement that y > x.  AlphaTab would interpret the input, check that y > x, then use the start and end beats for placement.  I'm not entirely familiar with how you place the notes, but if you can get the x position of a certain beat on the page then you should be able to set the width of the crescendo/decrescendo marking so that its just above the staff over the start and end beat specified.

# Current Workarounds 

You allow importing of crescendo and decrescendo through guitar pro 6 and 7 files which already contain them.  You might also be able to replicate how they embed them.  It is currently not possible to import them through alphaTex.

**Comment by Danielku15** [comment]
The feature is now available in version 0.9.6.286 
2 new beat effects were added `cre` and `dec`. 
https://docs.alphatab.net/develop/alphatex/beat-effects#simple-effects
