### ISSUE TITLE
Player not working in Safari 13.0.1+

### ISSUE THREAD

**Issue by atolle** [CoderLine/alphaTab#290]
# Your Environment
* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: HTML5
* Browser Name and Version: Safari v13.0.1+
* Operating System and version (desktop or mobile): iOS v10.14.6 (desktop) and iOS v13.1.3 (iPad)
NOTE: I also was able to reproduce this in the iOS Simulator on the desktop above all the way back to v11.3, but I'm not sure if this is a legitimate result.
* Link to your project: alphatab.net

# Expected Results
Player plays tab 

# Observed Results
The player stops after attempting to play the first note of the song (or so it seems). I'm not seeing any errors in the console.

# Steps to Reproduce (for bugs)
This is reproducible on the home page demo on alphatab.net. Just press play.

**Comment by atolle** [comment]
I reported this because I found this issue in my implementation of alphaTab, then reproduced it on the home page demo of alphatab.net. Looks like both my implementation and that demo are on an older version - I'm updating to the developer branch build and I'll test it out to see if the issue still occurs.

**Comment by Danielku15** [comment]
To be honest: The version on the home page of alphaTab wasn't updated quite a while 😅 I just checked on BrowserStack the latest examples on https://docs.alphatab.net/develop/examples/ and the player seems to be working. I cannot confirm the actual audio playback as BrowserStack does not transmit to my local PC while testing. And I do not have a Mac to test it live. 

Can you maybe verify that on the following sample you really cannot play anything? 
https://docs.alphatab.net/develop/assets/files/player/player.html

**Comment by Danielku15** [comment]
I was able to reproduce the issue on BrowserStack. The PlayPause() method was missing the activation of the WebAudio context. This is needed nowadays in most browsers. It seems Safari is a bit more strict on this activation than other browers.
