### ISSUE TITLE
Notes can't have both slide-ins and slide-outs

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#292]
# Your environment

* Version used: latest (develop)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox (latest)
* Operating System and version (desktop or mobile): Linux (desktop)
* Link to your project:

# Expected Results
Slide-ins and slide-outs should be combinable, i.e. a note should be able to have both notations at the same time. Example in GP6:
![screenshot-1573593566](https://user-images.githubusercontent.com/46634000/68711898-e8f9aa00-059a-11ea-9887-c85d8e2352d1.png)

# Observed Results
The following alphatex snippet
```
r (8.2{sib sod} 9.3{sib sod})
```
produces this result:
![Screenshot_2019-11-12 The Guitar Lick Database](https://user-images.githubusercontent.com/46634000/68711991-15adc180-059b-11ea-925c-1ed88cea2f11.png)
The slide-in from below has been overwritten by the slide-out.

# Steps to Reproduce (for bugs)
Create a tab with the following alphatex:
```
1.1{sib sod}
```

**Comment by Danielku15** [comment]
This is indeed an issue which I did not consider so far. The internal data model of alphaTab does not foresee to have slides in and out. But obviously it should 😉

**Comment by Danielku15** [comment]
Version 0.9.6.279 has now support for combiend slide-ins and -outs.
