### ISSUE TITLE
loadSoundFont doesn't work

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#293]
# Your environment

* Version used: 0.9.5-243
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Arch Linux desktop

# Expected Results
The function `loadSoundFont` should load the specified soundfont.

# Observed Results
If a soundfont is specified when creating a new instance of alphatab, it will be loaded properly. But when an instance is created without a soundfont and one is loaded later with `loadSoundFont`, nothing happens. Setting the `player` setting to `true` and calling `updateSettings` doesn't change anything either.

# Steps to Reproduce (for bugs)
Create a page with the following code:
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>alphaTab test app</title>
	</head>
	<body>
		<div id="alphatab"></div>
		<script src="alphatab-0.9.5-243.js"></script>
		<script src="script.js"></script>
	</body>
</html>
```
```javascript
(function()
{
	const settings = {
		// player: 'default.sf2',
		layout: 'horizontal',
		cursor: true,

		logging: 'warning',
	};

	let alphatab = new alphaTab.platform.javaScript.AlphaTabApi(document.getElementById('alphatab'), settings);

	alphatab.addSoundFontLoad(function(e)
	{
		console.log(`Loading soundfont... (${(e.loaded / e.total) * 100}%)`);
	});
	alphatab.addReadyForPlayback(function()
	{
		console.log('Player ready for playback');
		alphatab.play();
	});

	alphatab.tex('1.1 1.2 1.3 1.4');
	alphatab.settings.player = true;
	alphatab.updateSettings();
	alphatab.loadSoundFont('default.sf2');
})();
```

**Comment by chris-saunders** [comment]
Running into a similar problem exclusive to Firefox when creating an alphatab div and setting the soundfont with `data-player=[soundfont]`.
It works if you have the file locally, but if it is in another location (like on the cloud) it fails to load the soundfont.
This works fine in chrome with both a local soundfont and a remote (cloud based) soundfont

**Comment by Danielku15** [comment]
@cheap-glitch 
I investigated a bit deeper and the reported "bug" is actually a non-existing feature. It is not supported/possible to dynamically enable/disable the player feature. It currently must be enabled from the beginning so that alphaTab initializes all related components. Can you please explain what the real use case behind your report is? Why don't you simply activate the player from beginning? 

I will check what it would mean to support dynamic activation/deactivation of the player feature but for now as a workaround I'd recommend to use the classical recommended approach of alphaTab and simply activate it from beginning. 

@chris-saunders I think your issue is quite different from what is reported in this issue. Can you please open an own bug report where you precisely describe what you are doing (with corresponding examples)? To me it rather sounds that you are trying to load soundfonts from location where the [CORS policies](https://developer.mozilla.org/de/docs/Web/HTTP/CORS) prevent the download which results in errors. This has nothing to do with alphaTab but is a general web security feature of browsers.

**Comment by cheap-glitch** [comment]
> I investigated a bit deeper and the reported "bug" is actually a non-existing feature.

Oh OK, makes sense. You should probably correct the doc then: https://docs.alphatab.net/develop/reference/api/loadsoundfont

> Can you please explain what the real use case behind your report is? Why don't you simply activate the player from beginning?

My use case is pretty specific: I have a page that can display a lot of very short tablatures, and enabling the playback in each of them proves to be quickly overwhelming for the browser.

But I still want the user to be able to listen to those tabs, so I made a simple workaround where each tab is destroyed and reloaded with the player enabled upon selection. It works fine, but I'd rather do things cleanly and I thought `loadSoundfont` could work. In the future it would be nice if it were possible, but right now that workaround is very much adequate :)

**Comment by Danielku15** [comment]
> You should probably correct the doc then:

Jup, true. The reference docs are still quite new and not covering all details in 100% and the example in this case is not really correct. 

> My use case is pretty specific: I have a page that can display a lot of very short tablatures, and enabling the playback in each of them proves to be quickly overwhelming for the browser.

Thanks for the insight. in such cases it definitly makes sense to dynamically enable-disable the player. I will quickly check, maybe I can still provide it by today.

**Comment by Danielku15** [comment]
With the changes I added following sample with enabling/disabling the player dynamically works. Everything gets properly initialized and destroyed on request. 
```html
<button type="button" id="enable">Enable</button>
<button type="button" id="disable">Disable</button>
<div id="alphatab"></div>

<script>

const settings = {
	layout: 'horizontal',
	logging: 'warning',
};

let alphatab = new alphaTab.platform.javaScript.AlphaTabApi(document.getElementById('alphatab'), settings);

alphatab.addSoundFontLoad(function(e)
{
	console.log(`Loading soundfont... (${(e.loaded / e.total) * 100}%)`);
});
alphatab.addReadyForPlayback(function()
{
	console.log('Player ready for playback');
	alphatab.play();
});

alphatab.tex('1.1 1.2 1.3 1.4');

document.getElementById('enable').onclick = function() { 
	const settings = alphatab.settings;
	settings.enablePlayer = true;
	settings.enableCursor = true;
	alphatab.updateSettings();
	alphatab.loadSoundFont('soundfonts/default.sf2');
}
document.getElementById('disable').onclick = function() { 
	const settings = alphatab.settings;
	settings.enablePlayer = false;
	settings.enableCursor = false;
	alphatab.updateSettings();
}
</script>
```
