### ISSUE TITLE
Repeat measures fail to play properly, renderer can crash browser

### ISSUE THREAD

**Issue by chris-saunders** [CoderLine/alphaTab#294]
# Your environment

* Version used: Develop Branch
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Mac OSX 10.14.6

# Expected Results
When the player reaches the end of a repeated segment, the cursor moves back to the start and plays the segment again however many times is specified in the AlphaTex

# Observed Results
Player frequently does not repeat at all, and when it does it does not repeat the given number of times. There is also no indication above the repeat lines specifying how many times to repeat a given section.

In addition repeats can cause the renderer to use so much memory google chrome crashes. I see 150% CPU utilization when trying to render some AlphaTex with repeats

# Steps to Reproduce (for bugs)
Using the sample AlphaTex provided for repeats, the first repeat does not happen, and the second repeat (set to repeat 3 times) only repeats once.
```
\ro 1.3 2.3 3.3 4.3 |
5.3 6.3 7.3 8.3 |
\rc 2 1.3 2.3 3.3 4.3 |
\ro \rc 3 1.3 2.3 3.3 4.3 |
```

Using the same AlphaTex above but changing the repeat amounts causes the memory/render issue which crashes Chrome
```
\ro 1.3 2.3 3.3 4.3 |
5.3 6.3 7.3 8.3 |
\rc 3 1.3 2.3 3.3 4.3 |
\ro \rc 3 1.3 2.3 3.3 4.3 |
```

**Comment by Danielku15** [comment]
Sounds like a nasty endless-loop somewhere inside the audio generation which piles up a lot of data until the browser crashes.
