### ISSUE TITLE
Announcement: Limited availability

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#295]
Hi everybody. 

I appreciate that you all are using alphaTab and are eager to get bugfixes and new features. 👍 

Unfortunately I am currently very busy in my private and work life so that alphaTab suffers a bit from the time it would deserve. 😭  I want to highlight that alphaTab is not dead and I plan to tackle all open points reported and get it back to a stable state for a proper release 1.0. Until then feel free to report your findings. This will help me get things fixed faster once I have time for alphaTab development again. 

I am also happy to accept bugfixes via pull requests if you manage to get things fixed 😉

**Comment by gburlet** [comment]
Thanks for your hard work on this library. Happy holidays Daniel 😄Rock on

**Comment by cheap-glitch** [comment]
Hey man don't worry, we can all appreciate how much time an OS project as ambitious as this demands. Take care of yourself and don't worry about us, we can wait!

**Comment by nascent** [comment]
Hi Daniel,

It's a great library but how does one obtain an older version?

Regards

**Comment by cheap-glitch** [comment]
@nascent: just look in the "History" panel on the AppVeyor page (https://ci.appveyor.com/project/Danielku15/alphatab/history)
