### ISSUE TITLE
Note beams sometimes overlap rest symbols

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#296]
# Your environment

* Version used: latest (develop)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Linux desktop

# Expected Results
Note beams should not overlap rests. Example in GP6:
![screenshot-1575741833](https://user-images.githubusercontent.com/46634000/70378736-58f21a80-1924-11ea-9095-53d2697057bd.png)

# Observed Results
There is a small visual bug in alphatab where the beams sometimes overlap the rests:
![Screenshot_2019-12-07 The Guitar Lick Database](https://user-images.githubusercontent.com/46634000/70378758-83dc6e80-1924-11ea-9ba6-6f449a529eb8.png)

# Steps to Reproduce (for bugs)
Create a tablature with two notes separated by a rest, e.g.:
```
15.2.16 r.8 12.3
```
Result:
![Screenshot_2019-12-07 The Guitar Lick Database(1)](https://user-images.githubusercontent.com/46634000/70378814-167d0d80-1925-11ea-9de7-656f56183b1d.png)

**Comment by Danielku15** [comment]
AlphaTab has currently no mechanism for "collision detection" of music notation elements hence this would be rather a new feature / enhancement than a bug. 

For rests it should be possible rather simple to avoid collisions compared to other areas like with slurs and ties.

**Comment by Danielku15** [comment]
Rests are now considered properly during beaming: 
![image](https://user-images.githubusercontent.com/674916/103480966-1d9c7680-4dd8-11eb-99ea-d86248367ec0.png)
