### ISSUE TITLE
Issues with AlphaTab, Metronome and Tracklist

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#297]
# Question 
I am having some trouble with some aspects of AlphaTab, namely the Metronome and rendering from the Tracklist.

Regarding the Metronome, it is very sporadic and only works when pressed prior to pressing play.

I looked in the documentation but it seems that `MetronomeValue` should be used instead but changing `MetronomeVolume` to `MetronomeValue` resulted in an error.

Also, playback stops when rendering a track in place of a previously rendered track and I'd like to know if there is a method to avert this situation, as was the case previously.

Thank you

# Your environment (if applicable)

* Version used: (develop latest)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome/Firefox
* Operating System and version Windows 10 desktop

**Comment by Danielku15** [comment]
Thanks for the report. 

> Regarding the Metronome, it is very sporadic and only works when pressed prior to pressing play.

Do you have a minimal reproducible example or at least some more details on that problem? Here some questions towards finding the problem: 

- Is it not working in general or does it stop working at some point? 
- Is it happening on particular files? If yes, is it happening on the same area of the song that the metronome stops working?
- Is there some sequence of actions that leads to this issue? 
- If you can reproduce it, can you enable some detailed logging and provide the browser logs? 
- Are there some errors in the console? 

> I looked in the documentation but it seems that MetronomeValue should be used instead but changing MetronomeVolume to MetronomeValue resulted in an error.

Can you point me to the correct location where you got this information from? In the latest docs I cannot find any reference to a `MetronomeValue` only `MetronomeVolume` is mentioned. Also from a code perspective `MetronomeVolume` would be correct. 

> Also, playback stops when rendering a track in place of a previously rendered track and I'd like to know if there is a method to avert this situation, as was the case previously.

Could be a performance issue, I lately saw some issues there due to the latest reworks. If you can point me to a concrete example where you can see this issue I can try optimizing it. 

Unfortunately the playback still has to be done in the UI thread of the browser via ScriptProcessorNode. The ScriptProcessorNode was deprecated already but the AudioWorklet which could replace it is not yet properly available in browsers to replace it.

**Comment by nascent** [comment]
Hi Daniel,

Thank you for your responses and questions.

Regarding the documentation, it is here:

https://docs.alphatab.net/develop/reference/api/metronomevolume

As for your questions regarding the metronome, my answers are as follows:

Is it not working in general or does it stop working at some point?

The metronome does work, but it must be engaged prior to commencing playback, or else playback must be stopped (paused) prior to attempting to (re)engage the metronome; otherwise the metronome must be engaged _before_ playback is started.

Is it happening on particular files? If yes, is it happening on the same area of the song that the metronome stops working?

It happens on any or all files that I have tried.

Is there some sequence of actions that leads to this issue?

Press play, mentronome cannot be engaged unless playback is stopped or paused.

If you can reproduce it, can you enable some detailed logging and provide the browser logs?

`[Info][AlphaTab][Rendering] [alphaTab] Font API signaled available null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Player] Will use webworkers for synthesizing and web audio api for playback null
alphatab-0.9.5.243.js:23559 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
open @ alphatab-0.9.5.243.js:23559
alphaTab.platform.javaScript.AlphaSynthWebWorkerApi @ alphatab-0.9.5.243.js:23714
createWorkerPlayer @ alphatab-0.9.5.243.js:35155
setupPlayer @ alphatab-0.9.5.243.js:575
alphaTab.AlphaTabApi.$hx_exports.alphaTab.AlphaTabApi @ alphatab-0.9.5.243.js:316
alphaTab.platform.javaScript.AlphaTabApi.$hx_exports.alphaTab.platform.javaScript.AlphaTabApi @ alphatab-0.9.5.243.js:24116
init @ alphatab-0.9.5.243.js:1910
exec @ alphatab-0.9.5.243.js:1902
jquery.fn.alphaTab @ alphatab-0.9.5.243.js:6547
(anonymous) @ (index):653
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Rendering] [Arial] Font API signaled available null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Rendering] [Georgia] Font API signaled available null
(index):1142 Activated:  ServiceWorker {scriptURL: "http://localhost/_interact/worker/cache/home_cache.js", state: "activated", onerror: null, onstatechange: null}
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Loading score from 26410 bytes using 5 importers null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Importing using importer Guitar Pro 3-5 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Guitar Pro 3-5 does not support the file null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Importing using importer Guitar Pro 6 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 6] Loading GPX filesystem null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Guitar Pro 6 does not support the file null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Importing using importer Guitar Pro 7 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] Loading ZIP entries null
age_stave_cache.js:10 Cache open.
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] Zip entries loaded null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] Start Parsing score.gpif null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] score.gpif parsed null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] Start Parsing BinaryStylesheet null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] BinaryStylesheet parsed null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] Start Parsing Part Configuration null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Guitar Pro 7] Part Configuration parsed null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLoader] Score imported using Guitar Pro 7 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][AlphaSynth] Start loading Soundfont from url /_files/_resources/sf2/alphasynth.sf2 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][AlphaTab] Generating Midi null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Midi] Begin midi generation null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Midi] Midi generation done null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][AlphaSynth] Loading midi from model null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][AlphaSynth] Midi successfully loaded null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][AlphaSynth] Loading soundfont from bytes null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Rendering] Rendering 1 tracks null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Rendering] Track 0: Piano null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Rendering] Rendering at scale 1 with layout PageView null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][ScoreLayout] Creating score info glyphs null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 0 to 4 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 5 to 10 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][AlphaSynth] soundFont successfully loaded null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 11 to 18 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 19 to 27 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 28 to 34 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 35 to 41 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 42 to 49 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 50 to 57 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 58 to 64 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 65 to 70 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][PageView] Rendering partial from bar 71 to 71 null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][Rendering] Rendering finished null
alphatab-0.9.5.243.js:2087 [Info][AlphaTab][rendering] Rendering completed in 678ms null
age_stave_cache.js:13 Cached:  (13) ["/support/offline/", "/notation/age-of-extinction/stave/", "/_files/_resources/_xml/menu.xml", "/_files/_resources/_fonts/otf/banner.otf", "/_files/_resources/_fonts/woff2/open-sans-v15-latin-regular.woff2", "/_files/_resources/_fonts/woff2/lato-v14-latin-regular.woff2", "/_files/graphics/vectors/logo.svg", "/_files/graphics/apple-touch-icon.png", "/_files/graphics/vectors/safari-pinned-tab.svg", "/_files/graphics/android-chrome-192x192.png", "/_files/graphics/mstile-150x150.png", "/_files/graphics/favicon.ico", "/_files/notation/staves/age.gp"]
home_cache.js:10 Cache open.
The resource http://localhost/_files/_resources/_fonts/woff/bravura.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
home_cache.js:1 Uncaught (in promise) DOMException: Cache.addAll(): duplicate requests (http://localhost/_interact/worker/cache/home_cache.js)`

Are there some errors in the console?

Only a warning that the AudioContext must be started via a user action in Google Chrome. Firefox has no errors or warnings. AlphaTab seems to work in iOS and Android, as well Safari functions also as far as I could test.

Regarding playback stopping when rendering a new track, I understand the change in the API, however it would be nice if a method was available that allowed playback to continue, irrespective of rendering but at this stage; I am merely glad that new tracks can be rendered.

In the first instance, it would be nice if AlphaTab could simply pick up from where it left off in terms of playback of the song so I am not sure that there is a bug in this case and I may have to submt a new issue.

As for the metronome, I was concerned there may be a z-index problem but I don't believe this to be the case in this instance.

Thank you, and all the best

**Comment by Danielku15** [comment]
Thanks for pointing me to the correct location, I fixed the docs. Somehow Notepad++ couldn't find it due to wrong search settings. Now the page is corrected to the expectations of `MetronomeVolume`

While testing today I found a channel volume related issue which matches your description. If you activated the metronome on-the-fly it did not start playing, if it was activated before playing it was working. 

> Regarding playback stopping when rendering a new track, I understand the change in the API, however it would be nice if a method was available that allowed playback to continue, irrespective of rendering but at this stage; I am merely glad that new tracks can be rendered.

I also found this issue and fixed it, it was not really on purpose that the playback stops on track changes.  Due to some logic-unification the midi was regenerated on all render requests which is not needed. Now it is only regenerated if the score changes which should resolve the issue. 


Please check again with the latest build 0.9.5.245 if it resolves your issues.

**Comment by nascent** [comment]
Metronome issue is fixed in 0.9.5.245 and playback doesn't stop upon rendering of new tracks however I have identified a new issue in relation to note highliting (or lack thereof), which I will create an issue report for.

Thank you very much for giving your time to comment.
