### ISSUE TITLE
Make muted strings and metronome work properly with guitar-only soundfonts

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#298]
# Description 
Since the audio engine was rewritten, alphatab can play most guitar soundfonts out of the box, which is great! :+1:

But guitar-only soundfonts have trouble with muted strings: instead of a "click" they produce a very low sound. The same problem appears when activating the metronome: instead of discrete clicks there is a continuous low note playing.

I guess these sounds are supposed to be played by another instrument, like some kind of percussion -- so it's not really a bug in itself, but it does make these soundfonts pretty much useless.

# Possible Solutions
Having a way to specify a second soundfont to play the percussion sounds would be awesome. Ideally it'd be a sounfont solely made for that purpose so it could stay lightweight, but I know nothing about the sf2 format so I don't know if this is at all possible.

**Comment by Danielku15** [comment]
Sounds like a bug report to me. Can you please fill out the template for a bug report so that I have all information I need to understand your issue?

**Comment by cheap-glitch** [comment]
Closed and reopened as bug report issue #302.
