### ISSUE TITLE
Add support for multiple soundfonts

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#302]
# Your environment

* Version used: 0.9.5.245 (latest develop)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Arch Linux desktop

# Expected Results
Muted strings and metronome clicks should be played correctly when using a guitar-only soundfont.

# Observed Results
Guitar-only soundfonts have trouble with muted strings: instead of a "click" they produce a very low sound. The same problem appears when activating the metronome: instead of discrete clicks there is a continuous low note playing.

# Steps to Reproduce (for bugs)
Create a tablature with the following soundfont:
[soundfont.zip](https://github.com/CoderLine/alphaTab/files/3978135/soundfont.zip)

# Possible Solution 
Having a way to specify a second soundfont to play the percussion sounds would be awesome. Ideally it'd be a soundfont solely made for that purpose so it could stay lightweight, but I know nothing about the sf2 format so I don't know if this is at all possible.

**Comment by Danielku15** [comment]
Sounds like a good idea to support loading of multiple soundfonts individually to tailor the output better. Supporting it should not be a big deal but rather a topic for 1.x . 

Implementation Notes: 
Internally we hold a list of presets that are derived from the soundfont. from this patches we try to find a matching one. Wrapping up the patches into a SoundFont container and extending the patch selection logic should be fairly easy.

**Comment by Danielku15** [comment]
Multiple SoundFonts can now be loaded.

New APIs:
https://www.alphatab.net/docs/reference/api/loadsoundfont/ (new parameter)
https://www.alphatab.net/docs/reference/api/resetsoundfonts/ (new call)

Guide: 
https://www.alphatab.net/docs/guides/multiple-soundfonts
