### ISSUE TITLE
Unable to access alphatab docs for the develop branch

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#310]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript or C#
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: Firefox
* Operating System and version (desktop or mobile): Arch Linux desktop
* Link to your project:

# Expected Results
The docs for the develop branch should be accessible.

# Observed Results
https://docs.alphatab.net/develop returns a 403 Forbidden Access error. https://docs.alphatab.net/master works fine though.

# Steps to Reproduce (for bugs)
Go to https://docs.alphatab.net/develop.

**Comment by Danielku15** [comment]
Looks like the last deploy of the docs today failed. I triggered a new build, lets see if the next one works.

**Comment by cheap-glitch** [comment]
Docs are back online, thanks for your quick response!
