### ISSUE TITLE
Product Announcements

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#311]
As we're currently not really having a proper channel for making product level announcements like breaking changes or feature development that is ongoing I'm starting this issue where I'll try to keep you up to date about the things ongoing in alphaTab. 

I'm not really a fan of social media portals as you might have realized on the FB and Twitter accounts of alphaTab 😅 

I will leave the issue for now open for discussion as I do not expect so much noise and it gives room for questions on the announcements.

**Comment by Danielku15** [comment]
# Announcement 2019-12-20

There were major breaking changes introduced as part of #307. This PR reorganizes the whole settings data model in preparation of the v1.0 stable release. This breaking change is indicated by the version change from 0.9.5 to 0.9.6. 

Be aware of this change when upgrading to the latest version. The docs will cover the changes on [this page](http://docs.alphatab.net/develop/reference/breakingchanges-95-96).

**Comment by chris-saunders** [comment]
Could we get the CSS breaking changes listed here too?

**Comment by Danielku15** [comment]
# Announcement 2020-05-01

The release 1.0 is coming closer and I am trying to wrap up all the things needed to get it done. 
The overall work items until the official 1.0 release can be checked here: https://github.com/orgs/CoderLine/projects/1

## AlphaTab goes TypeScript

The last weeks I spent on migrating alphaTab to TypeScript to be more future-proof for extensions and new developments. The new TypeScript version will provide the same feature set as currently the C# based version. You can follow the progress [here](https://github.com/CoderLine/alphaTab/pull/356). For now the new version should be backwards compatible on the Web version while there are quite some breaking changes for the .net version which I will try to minimize. 

The biggest change is that I deprecated the `add<EventName>` / `remove<EventName>` methods to subscribe to events. The new subscription mechanism is via `eventName.on` / `eventName.off`.

The .net folks do not have to worry, alphaTab will still be provided as .net version. I developed a new custom compiler which translates the alphaTab TypeScript codebase to C#. This will also be the base for future targets like Kotlin and Swift which are a major target for the version after 1.0.0. 

## New Website and extended documentation

One biggest pain point of alphaTab currently is the lack of a proper guide to get started. You need to have quite a bit of knowledge about development and dig deep into the reference docs to make alphaTab working for you. The new website and docs will try to solve this gap. Beside the low level API reference and the feature demo, there will be some proper Getting Started guide and even tutorials on how to build up a full player component from scratch. This should help people adopting alphaTab for their projects. 

The WIP can be viewed here: https://www2.alphatab.net/
The repo for the new website is at https://github.com/CoderLine/alphaTabWebsite so anybody can make contributions if they like. 

## New CI/CD with NPM and MyGet packages

With the new TypeScript version a new CI / CD pipeline was needed. AlphaTab was using AppVeyor before and I migrated it over to GitHub actions. 

NPM Packages are now deployed as alpha pre-releases to npmjs.com: https://www.npmjs.com/package/@coderline/alphatab

MyGet packages were available already before, but now they are separated into a .net Standard version and a new .net core version for windows usage (WPF/WinForms): 
https://www.myget.org/feed/Packages/coderline

Both packages follow the same versioning and share always the same feature set. Be aware that these packages are based on the TypeScript version which is not yet final! There is still a bit of work and improvement to do on the new version. Especially proper performance and regression testing is needed. 

This means: **Do not upgrade to 0.9.8 for your productive environments**. You can of course have an early view to it already and report potential issues.

**Comment by Danielku15** [comment]
# Announcement 2020-07-16

We're getting closer and closer to the stable release 1.0. All features are implemented, all planned bugs fixed. Currently I am trying to finish the new website with all the tutorials, reference docs etc. 

The new website is now reachable via the main domain https://www.alphatab.net/ It is still not 100% complete and some more content and style adjustments are to be expected for 1.0. 

The TypeScript branch has been integrated to develop and will be the future main code base for any development. Our builds are now on GitHub Actions and not AppVeyor anymore and are available via NPM.js and NuGet.org. They are now on 1.0.0 (pre-release versions). 

**1.0.0-alpha.26**
https://www.npmjs.com/package/@coderline/alphatab
https://www.nuget.org/packages/AlphaTab/
https://www.nuget.org/packages/AlphaTab.Windows/

I would recommend that everybody upgrades now to the latest packages. For migration follow this guide: 
https://www.alphatab.net/docs/guides/breaking-changes-097-098

For the future I plan to make more smaller releases, always as soon as some features are ready again.

**Comment by Danielku15** [comment]
# Announcement 2020-07-21

Beside some polishing of the website and final checks the release 1.0 is ready to be released. 

As preparation for the next releases I tried to setup a more concrete roadmap on what features I will work in which release. I tried to group all the open feature requests into some themed releases. The order of the releases is not necessarily fixed like this but gives an initial outline. The order of the release contents might swap depending on my preferences and newly reported things. 

https://github.com/orgs/CoderLine/projects

Feel free to drop again a comment into the scheduled issues to inform me about the relevance of them for you. If many people ask again for certain features by commenting in the related issues, I might focus on them first. And don't forget to request new features which would fit into the roadmap if you have ideas on what could be useful for you. 😉

**Comment by Danielku15** [comment]
# Announcement 2020-11-27

The last issues of alphaTab 1.1 have been closed today. This means the next minor release of alphaTab is on it's way. I will just need to finish up the usual release testing and then 1.1 can already be published. After that I will re-check the priorities of the next releases and finish up the scope for the 1.2 release. As last time I would recommend that you vote or comment in the issues what would be most important for you to have.
