### ISSUE TITLE
AlphaTab rendering, but not playing back; ignoring settings

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#313]
# Question 
I recently updated to the latest version, i.e. 0.9.5.259 and nothing works.

The last version that is working is 0.9.5.256.

To begin, it seems my settings are ignored, e.g. the title of the song, track name and Standard Guitar Tuning are all shown, when in the options for the file; they are turned off.

# Your environment (if applicable)

* Version used: (0.9.5.259 develop branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome/Firefox
* Operating System and version (desktop and mobile):
* Link to your project:

https://emotive.productions/notation/age-of-extinction/stave/

**Comment by Danielku15** [comment]
I bet you ignored: https://github.com/CoderLine/alphaTab/issues/311#issuecomment-568042709

**Comment by nascent** [comment]
Hi Daniel,

That I did ignore https://github.com/CoderLine/alphaTab/issues/311#issuecomment-568042709 and blindly upgraded.

I have managed to get the score looking right but I don't know how to specify the .gp file location.

My apologies if this is a silly question but I'm keen to get it working for version 1.0 and I can see that what you have done is beneficial for the platform as a whole but don't want to remain stuck on an old version.

All the best

**Comment by Danielku15** [comment]
Great to here that I did not fully mess up 😉  

In case of doubts how things changed I recommend having a look at the updated player sample which shows now a bit cleaner how to use certain features. 
https://docs.alphatab.net/develop/assets/files/player/player.html

**Comment by nascent** [comment]
I had to enable the player to actually work.

Thanks again Daniel, bring on 1.0!
