### ISSUE TITLE
How to add dynamics using AlphaTex?

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#319]
# Description
A user should be able to specify dynamics of the music in AlphaTex which is not currently supported.

# Possible Solutions
Add another field similar to /tempo or /ts but call it /dynmaic and allow for symbols like f, ff, fff, p, pp, ppp etc. to specify a new dynamic level. Draw said dynamic using the method you currently use to default to forte on the generated AlphaTex.

# Current Workarounds
You don't currently support any through AlphaTex and so I can't show the change in dynamics through the sheet music.

**Comment by Danielku15** [comment]
As of today dynamics cannot be specified in alphaTex. This means your question is actually a feature request. It would be great if you can update this issue from the feature request template providing the details from there. 

In most cases of alphaTex if it is not documented, it means it is not yet supported and hence a new feature to support it. 😉

**Comment by dgriessler** [comment]
Thanks for the reply! I have changed it to a feature request as asked.

**Comment by Danielku15** [comment]
Dynamics support is available in 0.9.4.276
https://docs.alphatab.net/develop/alphatex/beat-effects#dynamics
