### ISSUE TITLE
How can I create a midi file from score in C#

### ISSUE THREAD

**Issue by daaneshfar** [CoderLine/alphaTab#322]
Hello.
I want to create a **midi file** from my score object (gp5 file) in C# and save it to local path and play that midi with windows media player.

It's my C# code :

```
var FilePath = "D:\\1.gp5";
var score = ScoreLoader.LoadScoreFromBytes(FilePath, new AlphaTab.Settings());
            var midiFile = new MidiFile();
            var midiFileHandler = new AlphaSynthMidiFileHandler(midiFile);
            var setting = new AlphaTab.Settings();
            var generator = new MidiFileGenerator(score,setting, midiFileHandler);
            generator.Generate();
```

Now , how can I save it as **midi file** ?
thanks.

**Comment by Danielku15** [comment]
Please follow the issue templates. I do not follow up on topics not following the templates.
