### ISSUE TITLE
convert score object to a midi file

### ISSUE THREAD

**Issue by hdaneshfar** [CoderLine/alphaTab#323]
### Your Environment
- Version used : (master branch)
- platform used: C#
- Operation System : Windows 10

### Question
How can I convert score object to a midi file and write to the disk ( ex : D:\myGpFile.mid ) ?
Is there any sample code or document for C#?

### My C# code
```
var FilePath = "D:\\1.gp5";
var score = ScoreLoader.LoadScoreFromBytes(FilePath, new AlphaTab.Settings());
var midiFile = new MidiFile();
var midiFileHandler = new AlphaSynthMidiFileHandler(midiFile);
var setting = new AlphaTab.Settings();
var generator = new MidiFileGenerator(score,setting, midiFileHandler);
generator.Generate();

// here , I want to write midiFile object to a midi file on the disk and play that midi file with Windows Media Player.
```

**Comment by Danielku15** [comment]
As a start I would recommend using the develop branch. The master branch is very old and not actively maintained until the next stable release. 

Considering the develop branch: The state of today is that your request is not really an officially supported workflow. The midi generation is optimized for the usage within alphaTab itself but the MidiFile data structure it would contain a simple list of all Midi Events which could be serialized to a .mid file. There is some starting code in place within alphaTab (`MidiFile.ToBinary()`) but this code is not tested an maintained. TBH: I didn't remember this code exists until I checked it now 😅 

I see 2 possibilities as follow up to this question:

1. You could check the official midi file specification to write correctly the midi file to disk. 
https://www.midi.org/specifications/item/the-midi-1-0-specification
http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html
http://somascape.org/midi/tech/mfile.html
2. Open another issue in this repository with the feature request template. It shouldn't be a big deal to add the binary serialization, but priority wise this feature would be below some other topics.
