### ISSUE TITLE
Export a mid file from Score object

### ISSUE THREAD

**Issue by hdaneshfar** [CoderLine/alphaTab#326]
### Your Environment

- Version used : (master branch)
- platform used: C#
- Operation System : Windows 10

### Expected Results

Export a midi file from Score object in C# and write to the disk ( ex : D:\myGpFile.mid )

### Current Codes 

```
var FilePath = "D:\\1.gp5";
var score = ScoreLoader.LoadScoreFromBytes(FilePath, new AlphaTab.Settings());

// Here , I want to write midiFile object to a midi file on the disk and play that midi file with Windows Media Player.
```

**Comment by Danielku15** [comment]
Can you please tidy up this issue to fit the shape of a proper request? 

1. If you have a feature request like discussed in #323 please use the corresponding template. 😕 
2. Fill out the details asked in the template properly so it is understandable what you want. Speak in full sentences. We're humans and not robots. 🤖 
3. Do not delete parts of the template unless it is mentioned that the section is optional. It is important to understand your concern and what problem you try to solve. Just copy pasting the same text over and over will not bring us further.
