### ISSUE TITLE
Issue with respect to multi-stave rendering

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#328]
# Your environment

* Version used: (0.9.6.274)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): W10
* Link to your project:

http://emotive.productions/notation/fairy-tale-of-deceit/stave/

# Expected Results
Render all notes as they are playing

# Observed Results
Rests and some notes rendering but not all.

# Steps to Reproduce (for bugs)
Press play

# Possible Solution 

Not sure as to a solution but it's working better than past versions.

**Comment by Danielku15** [comment]
From your description I do not really understand what the issue is. Can you please more precisely explain what the effect is. What notes are missing?

**Comment by nascent** [comment]
Hi Daniel,

I have never seen notes being highlighted in the bass clef prior to the current version, and now that some are; I am wondering why all are not.

Regards

**Comment by Danielku15** [comment]
Looks like you're asking for note highlighting on grand staffs. See https://github.com/CoderLine/alphaTab/issues/318 and https://github.com/CoderLine/alphaTab/issues/216 for further details. You already opened a bug for that topic. 😉
