### ISSUE TITLE
Start Bar breaks on ties

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#332]
# Your environment

* Version used: (master branch)
develop branch
* Platform used: JavaScript or C#
JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
SVG
* Browser Name and Version: 
Chrome 79.0.3945.130
* Operating System and version (desktop or mobile):
Windows 10 Desktop
* Link to your project:
https://music-assistant-fit.web.app/

# Expected Results

When you specify a start bar, AlphaTab should be able to render starting at that bar.

# Observed Results

When you try and render a bar which has a tie to a previous measure, AlphaTab throws an error:
Uncaught Cannot cast null to {
	__name__ : [alphaTab,rendering,ScoreBarRenderer], 
	paintSingleBar : <function>, 
	StaffId : score, 
	SharpKsSteps : 1,4,0,3,6,2,5, 
	FlatKsSteps : 5,2,6,3,7,4,8, 
	LineSpacing : 8, 
	StemWidth : 1.3
}

# Steps to Reproduce (for bugs)

1.  Create some sheet music with a tie between measures
2.  Try and render the second measure which has a tie to the previous measure

# Possible Solution 

Either disallow starting at measures with a tie to a preceding measure thereby reducing functionality or ignore the tie in the AlphaTex and render as expected without throwing the error.

**Comment by Danielku15** [comment]
fixed in 0.9.6.288 😉
