### ISSUE TITLE
Allow for doted rests

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#334]
# Description 

I would like to be able to specify dotted rests in AlphaTex.  For example, I'm doing a song with a 6/8 time signature and they frequently use a dotted quarter rest.  My workaround is a quarter rest followed by an eighth rest which is functionally the same but not the same aesthetically. 

# Possible Solutions

I'd imagine you would handle it the same way you handle dotted notes.

# Current Workarounds 

My workaround is a quarter rest followed by an eighth rest which is functionally the same but not the same aesthetically.

**Comment by gburlet** [comment]
@dgriessler I’m pretty sure we use dotted rests in our sheet music, specified in alphatex and it renders properly.

**Comment by dgriessler** [comment]
Ah, cool. How do you add it then?  When I do r{d}.4 it throws an error

**Comment by gburlet** [comment]
`r.4{d}`

**Comment by dgriessler** [comment]
Makes sense, should've tried that first. Thanks @gburlet !!
