### ISSUE TITLE
AlphaTex dynamics specified remain in effect until changed

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#340]
# Description 

Dynamics are able to be added to AlphaTex by specifying {dy mp} for example to get mezzo piano.  This only lasts for the note that I specify it on and then AlphaTab switches it back to forte. It is very frustrating to have to copy paste it for every note that follows it.  I would like to specify the start note for the dynamic level and have it remain until I change it elsewhere in the AlphaTex.

# Possible Solutions

Remember the last dynamic level specified or forte by default and use that until a new value is specified.

# Current Workarounds 

Copy pasting the dynamic on every note that follows the first dynamic level in the AlphaTex.

**Comment by Danielku15** [comment]
Available in 0.9.6.289 😁
