### ISSUE TITLE
General Question regarding AudioContext and AlphaTab

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#344]
# Question 

Google Chrome tries to automatically start the AudioContext but it is refused. I thought with the latest version of AlphaTab that this situation would be negated since resume is now assured on PlayPause.

# Your environment (if applicable)

* Version used: (0.9.6.293)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by Danielku15** [comment]
Hi there. Yes, by default most browsers nowadays keep an AudioContext in suspended state and a resume is only possible upon user interaction with the page. AlphaTab has various mechanisms to attempt a context resume (global click handler, as part of the player interaction handlers) to catch a user interaction for resuming the context. 

The PlayPause method was missing it while some other places already had it in place. 

What is your exact question in this regards? Do you need some insight in how alphaTab attempts the context resume? Are you facing some issues with the playback on your side?

**Comment by nascent** [comment]
Hi and thank you for responding to my question.

I am not having any problems specifically but I have noticed that the latest version of Microsoft Edge (chromium) that it does not try to start the AudioContext automatically, whereas Google Chrome does.

The behavior seems to occur on refresh and I am just wondering why this may be the case and whether it has anything to do with AlphaTab.

Kind regards

**Comment by Danielku15** [comment]
In general browser manufacturers seem to have different levels of strictness when it comes to the activation/resume of the audio context. This is dependent on whether they want to treat certain actions as trusted and real user interaction. Safari is also very strict on this while chrome seems to be still quite open. Goal is to avoid that websites can just start videos and ads spamming the user with audio. There were quite scam systems that utilize this. They had synthesized voices scaring users with messages of viruses and stuff. Hence the browsers attempt to only allow audio on explicit user interaction. AlphaTab has 2 systems to activate the audio context for playback: after creation, when the context is not active, a global click handler is registered. When the user is already interacting with the page, it might activate the contect already. The second thing is on API methods that interact with the player. AlphaTab hopes that there is a play button somewhere on the UI that the user clicks and by this activates the audio context. 

I should do some compat tests with the new edge to see if there could be more triggers to kickstart alphaTab.

**Comment by Danielku15** [comment]
Is your question answered with my latest comment?

**Comment by nascent** [comment]
Hi Daniel,

Thank you for responding, and I do appreciate your information, insight and historical detail.

It was mainly the fact that in Google Chrome the AudioContext seems to want to start automatically and I was hoping there would be a way to stop this from occurring so that it could only be started manually, i.e., via suspend/resume script commands.

Kind regards

P.S. I am currently not using the most up-to-date version so I will implement and test that as soon as I can.

**Comment by Danielku15** [comment]
If you would like alphaTab not to auto create and start an AudioContext there would be various solutions to this. The simplest is to only activate the player on demand by changing the corresponding setting dynamically: https://docs.alphatab.net/develop/reference/property/player-enableplayer

Also alphaTab could do the audio context initialization more dynamically. Feel free to open a feature request with some more insight why this would be beneficial.
