### ISSUE TITLE
Not able to mute individual tracks

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#345]
# Your environment

* Version used: (master branch)
develop branch
* Platform used: JavaScript or C#
JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
SVG
* Browser Name and Version: 
Chrome 80.0.3987.116
* Operating System and version (desktop or mobile):
Desktop
* Link to your project:
music-assistant.com

# Expected Results

api.changeTrackMute([0], true) only mutes the first track

# Observed Results

I have multiple tracks and whether I had them all rendered or only some of them rendered, when I called api.changeTrackMute([0], true) it muted all of the tracks and unmuting it using the same call unmuted all of the tracks.  I saw from your demo that you can mute specific tracks https://demo.alphatab.net/player.html, but my method isn't working.

# Steps to Reproduce (for bugs)

1. Create some tracks using api.tex()
2. Call api.changeTrackMute([0], true)
3. Test out playing the tracks

# Possible Solution 

I'm not sure what the correct solution is. I read in your documentation that "If the track shares the channels with another track, all tracks will be muted as during playback they cannot be distinguished. " but are you saying then it's impossible to mute specific tracks?

**Comment by Danielku15** [comment]
I could not reproduce the issue with your proposed steps: https://jsfiddle.net/danielku15/3qcdb5ro/
Can you maybe point out what is missing to reproduce what you see? When I play the song only the first track is muted. 

Each track gets unique channels within alphaTab hence they can be individually muted. In GuitarPro you can decide to put multiple tracks on the same midi channels, only then the mentioned point of the docs applies.

**Comment by dgriessler** [comment]
I have no idea what I'm doing wrong.  I looked at your example that you posted, and it obviously works and looks almost identical to what I'm doing and mine isn't working.  I'll try and pull the latest from the development branch again and, if it still doesn't work, post a more specific example.

**Comment by Danielku15** [comment]
@dgriessler : Were you able to identify what is causing the issue on your side?

**Comment by dgriessler** [comment]
I was not able to find what was going wrong. I'm fine closing this issue for now and reopening it if I can't figure out what's going on later. Thanks for all your support and for building this project!
