### ISSUE TITLE
Play musicsheet on mobile devices

### ISSUE THREAD

**Issue by hdaneshfar** [CoderLine/alphaTab#347]
# Question 
Why does alphatab get stuck at times ? often on mobile devices with firefox and chrome browsers.

# Your environment (if applicable)

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Firefox 68.1.1  , Chrome 77.0.38
* Operating System and version (desktop or mobile): Android 9 ( Samsung S8+ )
* Link to your project: https://github.com/hdaneshfar/TestOnSamsungS8.git

**Comment by Danielku15** [comment]
It depends on the performance of the device whether it gets stuck or not. alphaTab needs to do some CPU intense operations for the audio generation and cursor positioning.  

In your example video it is the "smooth" scrolling that seems to be mainly cause the hangs. You might want to consider setting the [scrollSpeed](https://docs.alphatab.net/develop/reference/property/player-scrollspeed) setting depending on desktop or mobile platforms. 

I would need to check there are some tricks to make scrolling smoother and less CPU intense on mobile devices.

Smooth scroll to seems available on some more modern browsers: 
 https://developer.mozilla.org/de/docs/Web/API/Window/scrollTo  but there is no control on the actual speed.

**Comment by hdaneshfar** [comment]
Thank you Daniel.
