### ISSUE TITLE
Dynamically disable seek by click

### ISSUE THREAD

**Issue by chris-saunders** [CoderLine/alphaTab#349]
# Description 
I would like an API point to be able to toggle the users ability to seek by clicking on the score.
I see that in the master branch there used to be a setting to disable seeking, but it seems that has since been removed.

# Possible Solutions
Add a setting to enable/disable seeking, that we can then update with the update settings call.

# Current Workarounds 
None that I am aware of

**Comment by Danielku15** [comment]
Yes, I lately simplified the logic within alphaTab regarding the click handling and by this removed the setting. I decided to connect the cursor setting with the availability of user interaction. 

But if you need this feature, I can easily bring it back.

**Comment by chris-saunders** [comment]
Thank you very much it would be appreciated. 
Would you also be able to add an event for when a user seeks? Or would that be a separate feature request?

**Comment by Danielku15** [comment]
>Would you also be able to add an event for when a user seeks? Or would that be a separate feature request?

Technically yes. But I might get it wrong so to clarify: 

You want to disable the default selection and seek-on-click behavior (initial request).
But you want to capture (with this default behavior disabled) that a user clicked on a beat/bar to handle it on your own? 

Or is your second request that you want to capture the default "seek-on-click" if it is activated?

**Comment by chris-saunders** [comment]
> You want to disable the default selection and seek-on-click behavior (initial request).
Correct. A setting or some option to disable seek on click would be fantastic.

> Or is your second request that you want to capture the default "seek-on-click" if it is activated?

That is more what I was thinking of. Personally for my use case it would be excellent to be able to tell when a user seeks by clicking, and do things based on them seeking. 

Sorry for the lack of clarity, and thank you!

**Comment by Danielku15** [comment]
Okay, I will check how to add this feature best. Maybe I will just add a "beat clicked" event which handles both scenarios. If the default user interactions are enabled, the beat click will request a seek on the player, if it is disabled, the event can still fire and the developer could decide what to do. 

The main thing that made it confusing for me was that you ask for an option to disable the default seek-on-click feature, but then at the same time you want to have it active and get an event. 

But I simply guess there are some conditions on your site to decide whether the seek-on-click should be active or not (maybe even dynamic).

**Comment by Danielku15** [comment]
The option and events are added in version 0.9.7.302.
Setting to configure the seek on click and selection: [Player.EnableUserInteraction](https://docs.alphatab.net/develop/reference/property/player-enableuserinteraction)
Events related to click on beats: 
- [BeatMouseDown](https://docs.alphatab.net/develop/reference/events/beatmousedown)
- [BeatMouseMove](https://docs.alphatab.net/develop/reference/events/beatmousemove)
- [BeatMouseUp](https://docs.alphatab.net/develop/reference/events/beatmouseup)

I hope with this you can realize your needs.
