### ISSUE TITLE
Not working with Unity

### ISSUE THREAD

**Issue by smakarov** [CoderLine/alphaTab#351]
Hi there! I'am using latest c# version for .net2.0 with Unity 2019.2
My code
`Score score = ScoreLoader.LoadScoreFromBytes(File.ReadAllBytes($"{Application.streamingAssetsPath}/test.gp5"));`
But i got this error
`NullReferenceException: Object reference not set to an instance of an object
AlphaTab.Importer.Gp3To5Importer.ReadScore () (at <3371ad0add004371adefaa18a99a453b>:0)
AlphaTab.Importer.ScoreLoader.LoadScoreFromBytes (System.Byte[] data, AlphaTab.Settings settings) (at <3371ad0add004371adefaa18a99a453b>:0)
AlphaTab.Test.Test+<StartAsync>d__4.MoveNext () (at Assets/Scripts/Test.cs:46)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:150)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:104)
`

**Comment by smakarov** [comment]
solved

**Comment by rhclayto** [comment]
Hi @smakarov ,

I am running into this issue as well. Can you tell me how you solved it?

**Comment by Danielku15** [comment]
@rhclayto  I haven't used unity before with alphaTab but one guess is that you pass in a settings object to the reader:

```cs
Score score = ScoreLoader.LoadScoreFromBytes(File.ReadAllBytes($"{Application.streamingAssetsPath}/test.gp5"), new Settings());
```

The API is misleading here due to the optional parameter. The settings object became mandatory at some point but the loader API was not updated yet.

**Comment by rhclayto** [comment]
@Danielku15 
That seems to have been the problem. Thanks! I still haven't gotten it fully working in Unity, but at least this hurdle has been cleared.
