### ISSUE TITLE
Staves - overlapped text

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#353]
# Question 
When I render tabs without scores, sometimes I have situation like bellow. Is there a way to fix it?

![image](https://user-images.githubusercontent.com/25822217/80599804-d3cee580-8a2b-11ea-97ab-7742a06aa6e6.png)

# Your environment (if applicable)

* Version used: master
* Platform used: JavaScript 
* Rendering engine used: SVG (default)
* Browser Name and Version:  Chrome 81.0.4044.129 
* Operating System and version Windows 10:
* Link to your project:

**Comment by Danielku15** [comment]
The example looks like it has multiple "voices" and the secondary voices are filled with rests. Secondary voices are rendered slightly transparent. But to be sure I would need an example file to check if this is really the case. 

The Guitar Pro behavior is also to show rests for the secondary voices in case the standard notation is hidden. It seems to suffer from the same issue. 
![image](https://user-images.githubusercontent.com/674916/80606622-d5e97200-8a34-11ea-9615-666388af183c.png)

For standard notation Guitar Pro has this feature of shifting the rests up: 
![image](https://user-images.githubusercontent.com/674916/80607034-485a5200-8a35-11ea-929a-57afb630956b.png)

alphaTab does not have yet any functionality to prevent collisions in such scenarios. Feel free to open a new issue with the "Feature Request" template to request such a functionality.
