### ISSUE TITLE
Scroll not working on mobile at all

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#354]
# Your environment

* Version used: develop
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome Latest
* Operating System and version Windows/Android:
* Link to your project: https://tab.tuneguitar.net/

# Expected Results
Player should scroll on mobile.
# Observed Results
Player scrolls properly only on desktop. Auto scrolling not working on mobile at all.

# Steps to Reproduce (for bugs)
Here you can try how works auto scroll on desktop, and do not work on mobile: Auto scroll not working on mobile simulator as well
https://tab.tuneguitar.net/jimi-hendrix/izabella-live-at-woodstock

# Possible Solution 
I tried to experiment data-player-scroll-element, but nothing helps. Today I successfully migrated from **master** to **develop**, but I have no idea how to fix auto scroll feature. Thanks a lot in advance.

**Comment by yaras6** [comment]
Note: When I commented bellow lines, scrolling started working on mobile (Android) as well. I am not sure how it will be with iOS because I have not device to test that.

![image](https://user-images.githubusercontent.com/25822217/80637253-faf2da80-8a5e-11ea-95ee-6d013ce06928.png)

**Comment by yaras6** [comment]
PS: Example which I pasted in first post is now working, because of above changes, But if you will have this change on mind, it would be good.

**Comment by yaras6** [comment]
Hm... When I commented this line scrolling in Chrome (Android) started working, but scrolling in **Android WebView** stopped working. Would be great to find a compromise, and make it working on both, because I have associated mobile app and now auto scroll stopped working there

**Comment by Danielku15** [comment]
This issue seems related to https://github.com/CoderLine/alphaTab/issues/205 where it was reported differently. At the time I fixed it there I tested it on various mobile devices via BrowserStack and it was working fine on the available iOS and Android devices. 

I see some potentials for a workaround but I'll need to test them first. Keep you up to date

**Comment by Danielku15** [comment]
I changed again the element that is used to something very promising: `document.scrollingElement` this should pick always the right element for scrolling. I tested it on the following browsers but I have no Android WebView available for testing. Let me know if the fix works for you: 

✔️  Chrome for Android (Samsung Galaxy S20 - Android 10, Pixel 4 - Android 10)
✔️ Samsung Internet ( Samsung Galaxy S20 - Android 10)
✔️ Firefox for Android (Pixel 4 - Android 10)
✔️ Safari (iPhone 11 Pro - iOS 13)
✔️ Chrome 81 (Windows)
✔️ Firefox 75 (Windows)
✔️ Edge 81 (Windows)
✔️ Safari 13 (Mac OS Catalina)

**Comment by yaras6** [comment]
Great job. I tested it on Android Web View, Chrome Windows and Chrome Mobile and all seems to be working. Thank you.
