### ISSUE TITLE
Recognize track type 

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#358]
# Question 
Is there a way to recognize is a track a guitar/keyboard/bass/percussion/other?

![image](https://user-images.githubusercontent.com/25822217/80866923-ae431580-8c91-11ea-8715-4facb0ac136e.png)

# Your environment
* Version used: develop
* Platform used: JavaScript
* Link to your project: https://tab.tuneguitar.net

**Comment by Danielku15** [comment]
You can fully rely on the midi information to identify whether a track is a percussion tab and which instrument it is.

From a playback perspective the midi channel value 9 [is considered](https://en.wikipedia.org/wiki/General_MIDI#Percussion) the percussion channel. A small detail might be that the channels are 0 indexed, meaning that channel value 9 is the 10th channel and by this a percussion channel. 

The program defines the midi instrument. See lists like on Wikipedia for details to map them to instrument groups: https://en.wikipedia.org/wiki/General_MIDI#Program_change_events

The `staff.isPercussion` is more for the visual aspect of rendering drum tabs while the playback information defines how it sounds on playback. Of course usually `isPercussion == true` and `playbackInformation.program == 9` are the same from the input files.

**Comment by yaras6** [comment]
Thanks, this sample works perfect

**Comment by MrDrone-ru** [comment]
The question arose, how to map MIDI program value to a standart General MIDI instrument name.
A good option is:
[github.com/jazz-soft/JZZ-midi-GM](url)
