### ISSUE TITLE
How can we toggle loop

### ISSUE THREAD

**Issue by sushicodeur** [CoderLine/alphaTab#359]
# Question 

I try to toggle various parameters of AlphaTab, for example the loop

But if I call `at.alphaTab('loop', false);` it has no effect, once loop has been activated once, can't go back.

It appears that your source code does that :

```js
	,loop: function(element,context,loop) {
                 console.log('this is hit whatever loop parameter is')
		if(context.Player == null) {
                     return false;
		}
		if(!(!loop)) {
                         console.log('this is never hit when loop is false')
			context.Player.set_IsLooping(loop);
		}
		return context.Player.get_IsLooping();
	}
```

the test on !(!false) makes that `context.Player.set_IsLooping(loop);` is never called. I tried with various values (false, 0, -1, 'false')...

I can set the loop on, but can't set it off.

# Your environment (if applicable)

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: chrome
* Operating System and version (desktop): osx desktop
* Link to your project: still private

**Comment by Danielku15** [comment]
The master branch is not maintained. I recommend that you upgrade to the `develop` version where these features are working. 

https://docs.alphatab.net/develop/examples/general/advanced
https://docs.alphatab.net/develop/assets/files/player/player.html

**Comment by Danielku15** [comment]
Closing this issue due to stale discussion. Feel free to reopen it if you face issues with the latest version.
