### ISSUE TITLE
Unity heavy GC allocation on Render

### ISSUE THREAD

**Issue by smakarov** [CoderLine/alphaTab#361]
# Question 
I'am try to loading just 4kb .gp5 file, which results in output .png 96kb.
My setup
`var settings = new Settings();
settings.Core.Engine = "skia";
settings.Core.LogLevel = LogLevel.None;
Score score = ScoreLoader.LoadScoreFromBytes(Encoding.ASCII.GetBytes(testTab), settings);`

LoadScoreFromBytes()
https://i.imgur.com/LObmSWy.png
As you can see, logger was not deactivated + additional GC

RenderTracks()
https://i.imgur.com/NXIGgti.png
2mb GC.

1)Does it possible to disable logging at all?
2)Does it possible to reduce GC allocation?
3)Does it possible to run this in the separate thread? Seems, yes.
4)Does it possible to omit description(name, tuning, bpm) in rendered file?

# Your environment (if applicable)

* Version used: .net master
* Platform used: Unity 2019.2, C#
* Rendering engine used: SVG
* Operating System and version (desktop or mobile): Windows 10

**Comment by Danielku15** [comment]
You have to consider that having a final PNG encoded has a lot of **raw** image processing inbetween. 

> 1)Does it possible to disable logging at all?

Disabling the logging will disable the output but of course cannot disable the call to the function which will check if the logging is active. This is normal for any logging framework, you call the log functions from your code and the logging framework decides based on the configuration if it should be printed or not. 

Did you notice that the output is actually printed despite having it disabled? Can you drill deeper to find actually which allocated this is supposed to be? If the logging is disabled there should not be any allocates happening within this method calls. 

> 2)Does it possible to reduce GC allocation?

What do you mean by "GC allocation"? alphaTab needs to create an object graph for the data model and the rendering tree. There is no way of reducing the memory actually needed for this operation. In your case where you are maybe just doing a one time PNG conversion this might be an overhead but normally alphaTab is more long-lived as control. You might use the score model to also fill some other UI elements. The rendering pipeline is reusable for resizing of the UI. 

If you convert a Score to PNG and scrap the whole objects the GC will simply need to cleanup all of this. Every symbol alphaTab renders is an object to reposition and re-render it in case of resizing. 

> 3)Does it possible to run this in the separate thread? Seems, yes.

Yes it is possible. The normal UI controls already off-load the whole rendering process to a background thread. As you are using the `ScoreRenderer` directly you will need to move it to a thread on your own which should be easily possible. Once alphaTab completes the rendering and hands over the final `SkImage` it will not access this image anymore. No need for thread synchronization on this object.

> 4)Does it possible to omit description(name, tuning, bpm) in rendered file?

This is documented here: https://docs.alphatab.net/develop/reference/property/

**Comment by smakarov** [comment]
Thanks for answer!
Here the logger stack
https://i.imgur.com/0RQsFF3.png

Could you advice how to create or get main Logger?
And how to hide notes and remain only tabs?

**Comment by Danielku15** [comment]
I just noticed that the main logger is internal and not public. I just quickly patched the logger to be public so you should be able to set it now via `AlphaTab.Logger.LogLevel = LogLevel.None`

Give it a try with: 
https://www.myget.org/feed/Packages/coderline
https://ci.appveyor.com/project/Danielku15/alphatab/builds/32727035

**Comment by smakarov** [comment]
@Danielku15 
I installed AlphaTab.0.9.7.354, net48 folder, AlphaTab.dll 4,623kb. But Logger object is still not available.

**Comment by Danielku15** [comment]
Seems to be an issue on your side. The class is definitely public. I grabbed the latest nuget package from Appveyor and checked it with DotPeek: 
![image](https://user-images.githubusercontent.com/674916/81407353-89d8b480-913b-11ea-9407-881cf1ba6a1a.png)
![image](https://user-images.githubusercontent.com/674916/81407444-b2f94500-913b-11ea-9d8a-081fb2c97712.png)

Double check your references and clean+rebuild your project. Sometimes if the file cannot be found in the HintPath that is specified in the csproj, Visual Studio / MSBuild somehow magically finds it at another place (like the build output) and you might be using a wrong DLL you would actually like to use.

**Comment by smakarov** [comment]
I didn't work because i used "AlphaTab.Logger.LogLevel = LogLevel.None" instead of "AlphaTab.Util.Logger.LogLevel = LogLevel.None;".

AlphaTab with all libraries: libEGL, libGLESv2,libSkiaSharp is about 13bm. But min.js version of AlphaTab is only 1mb. May be it's somehow possible to reduce size for c#?

**Comment by Danielku15** [comment]
Sorry, my bad with providing the wrong the namespace. 

>AlphaTab with all libraries: alphatab, SkiaSharp, libSkiaSharp is about 12mb. But min.js version of AlphaTab is only 1mb. May be it's somehow possible to reduce size for C#?

Lets dissect this number to clarify where these sizes come from. 

The main DLL of alphaTab is 4.48MB. This includes the alphaTab code a 3.31MB soundfont and a 632KB TTF Font for the symbols. So the actual code of alphaTab takes up 0.54MB. So the .net version of alphaTab takes 0.54MB while the minimized JS version needs 1.07MB. The JS version still loads the SoundFont and WebFont into the memory of the browser making the JS version 0.5MB less efficient than the .net version. 

So let's talk about possible optimizations: 

**alphaTab DLL**
The TTF font is mandatory to do any kind of rendering so the minimum of the alphaTab core library is still 1.16MB. I can take it up for the upcoming TypeScript based version to move the SoundFont from the core library to the windows specific control library. Giving you 1.16MB for alphaTab. 

alphaTab is currently not using all glyphs from the font, so theoretically we could try to minimize the font to only contain the symbols used making an alphaTab optimized Bravura font. There are 3227 glyphs in the font and alphaTab is using 93 of them😅. Assuming an equal number of KB per symbol, the font could be shrinked to 18KB (20KB more realisticly). This would result in 0.54MB for the core library. Feel free to open a dedicated feature request for this optimization.

**SkiaSharp**

You are using Unity, and Unity does not provide any built-in mechanism to render images so it must rely on a 3rd party library to do this Job. 

You can ask over at the SkiaSharp repo if there are better ways to minimize the size of the library but we do not have much control over that: https://github.com/mono/SkiaSharp

If you find a more lightweight library for rendering images on Unity, feel free to open a feature request to provide a rendering backend for it. 

> Does it possible to get byte[] or Color[] from SKSurface? I want to use it in UI like Sprite.

This is more a question to SkiaSharp and the documentation there. In general: yes it is possible to get the raw bytes and raw pixel colors.

**Comment by Danielku15** [comment]
With the latest changes on the typescript version the SoundFont will be only part of the Windows specific package and the core package only ships the normal TTF Font. 

I also adjusted a bit the logger interface to potentially allow injecting an own logger implementation. This should close all open points of this issue related to alphaTab. Feel free to open new issues dedicated to concrete findings.
