### ISSUE TITLE
Render accidentals as annotated in Guitar Pro

### ISSUE THREAD

**Issue by WolfgangD** [CoderLine/alphaTab#365]
# Description 
Accidentals (b, #) sometimes render differently than annotated in Guitar Pro.

In this file:
[flats_sharps.gp.zip](https://github.com/CoderLine/alphaTab/files/4717987/flats_sharps.gp.zip)
you can see that each annotated flat is rendered as sharp.

# Possible Solutions
Accidental information can be read from the GP file and handled the same way as in Guitar Pro. Ideally the same accidental that is annotated in Guitar Pro is rendered in alphaTab.

# Current Workarounds 
I'm not aware of any current workarounds for this.

**Comment by Danielku15** [comment]
Thanks for the request, I will consider it for v1.1 to add this feature. It seems since a while GP contains a bit more information regarding the visual representation and I will try to utilize this information and only "auto-calculate" it if needed.

**Comment by Danielku15** [comment]
@WolfgangD The accidentals are now considered as noted in the Guitar Pro 7 files. I had to do quite a big rework of the accidental handling and the related positioning of note heads. You might want to double check your own test suite if the new system has some mistakes. 

The alphaTab test suite and manual tests showed the same display like in Guitar Pro for all tested scenarios. 

Available in [1.1.0-alpha.37](https://www.npmjs.com/package/@coderline/alphatab/v/1.1.0-alpha.37)
