### ISSUE TITLE
Multibend Support for alphaSynth

### ISSUE THREAD

**Issue by WolfgangD** [CoderLine/alphaTab#367]
# Description 
If two or more bends should happen at the same time (Multi Bend) it currently choose one of the bend values to bend both notes. If the bend value is different then alphaSynth is not able to output the correct sound. 

As far as I understand it, this is rooted in alphaSynth having 2 channels. One for normal notes and one for bended notes. The bending is then controlled on the 2nd channel.

# Possible Solutions
I can imagine setting an upper limit of bend channels. E.g. 6 (for each string 1) and keeping track of available and used channels.

If a bend is needed use the next available channel. Mark it as used and set up the bend. If the bend is over mark it as available again.

I'm missing a lot of knowledge on how alphaSynth works so I don't know if this is feasible.

# Current Workarounds 
No working around available if two bendings are required at the same time with different bend values.

**Comment by Danielku15** [comment]
I lately had a look at the midi 2.0 standard and the best solution for this would be to generate a message like the new per-note pitch bend message and extend the synth to support it (either via midi 2.0 or custom midi 1.0 message): 
![image](https://user-images.githubusercontent.com/674916/84564160-13922800-ad61-11ea-9115-7605c4cad4b6.png)

The idea is that additionally to the channel which defines the base pitch, midi instrument etc. the note number/key is added in this message. Internally in the synth each currently played note has it's own "voice" where we could store the per-note pitch and consider it then when the overall note pitch is calculated.

**Comment by Danielku15** [comment]
I adjusted the midi file generation for various note based effects to use a new midi 2.0 inspired per-note pitch bend message. Now each note-key per channel can have an own pitch bend which allows multi-bends like the following to sound correctly: 
![image](https://user-images.githubusercontent.com/674916/88457877-203e8b80-ce8a-11ea-9888-e268bc05ce68.png)

Available in version 1.1.0-alpha.35
