### ISSUE TITLE
Export MIDI in multi-track format (type 1 or 2)

### ISSUE THREAD

**Issue by thoun** [CoderLine/alphaTab#368]
# Description 
Currently, MIDI export generates a type 0 midi file (all events in 1 track). Midi can handle multi-track files on type 1 or 2 midi files, and these files allows volume control for each track (in case we want to mute one track, for example).

# Possible Solutions
Generate one midi-track per score-track

# Current Workarounds 
No

**Comment by thoun** [comment]
I can help on this one when the TS version of the project is done

**Comment by Danielku15** [comment]
Can you elaborate more on how you are currently using alphaTab and where exactly you would need type 1/2 SMF generation? alphaTab with its own synthesis engine also supports volume control and muting. This is rather done on **channel** base than on **track** base and this works quite well so I do not see direct value when adding type 1 / 2 generation to the internal setup.

If you are using an external synth engine in your project, you could already today implement an own `IMidiFileHandler` and generate a SMF type 1/2 compatible data structure together with the `MidiFileGenerator`. This also might make it easier to pass on the generated midi to your own synth engine. The `MidiFileGenerator` already generates per-track events. You will as first parameter of most `IMidiFileHandler` methods the track index for which the events are generated.

**Comment by thoun** [comment]
Thanks for your answer.
I was using the generated JS version, so I didn't see this interface. I searched and see the TS branch, I will use this.
