### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by t7g00** [CoderLine/alphaTab#369]
# Missing Files

the files "js/jquery.alphaTab.js" and "js/jquery.alphaTab.alphaSynth.js" are missing here. can anyone upload it?

**Comment by Danielku15** [comment]
https://github.com/CoderLine/alphaTab/blob/develop/README.md#downloads
![image](https://user-images.githubusercontent.com/674916/85458707-b2105b80-b5a1-11ea-8eab-16b26fcd1938.png)

![image](https://user-images.githubusercontent.com/674916/85458775-c3f1fe80-b5a1-11ea-9647-0be3b3b99741.png)

**Comment by shuja706** [comment]
> # Missing Files
> the files "js/jquery.alphaTab.js" and "js/jquery.alphaTab.alphaSynth.js" are missing here. can anyone upload it?

hello, I'm shuja who is working on your project, need to ask something ?
