### ISSUE TITLE
How do you play the song at a specific time?

### ISSUE THREAD

**Issue by christofolo** [CoderLine/alphaTab#371]
I'd like to "sync" a youtube video to my alphaTab score. But the song in the video (my video) doesn't start right away. I'd like to call an alphaTab api method to start playing (and stop). Am I able to do that?

**Comment by Danielku15** [comment]
![image](https://user-images.githubusercontent.com/674916/85458775-c3f1fe80-b5a1-11ea-9647-0be3b3b99741.png)
