### ISSUE TITLE
Change Instrument icon ?

### ISSUE THREAD

**Issue by LeadGuitarMx** [CoderLine/alphaTab#374]
# Question 
Is it possible to change the icon instrument depending on the instrument track?
Thanks so much for your amazing work : )

# Your environment (if applicable)

* Version used: alphaTab v1.0.0-alpha.27 (develop, build 27)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Google Chrome
* Operating System and version: Windows 10
* Link to your project:

**Comment by Danielku15** [comment]
The information about the instrument of a track is in the `score.track[index].playbackInfo.program` which contains a general midi instrument. See https://github.com/CoderLine/alphaTab/issues/358 for more details on how to map it potentially to an "instrument type". 

The rest is up to your development skills as the UI around is not part of alphaTab. :wink: The playground demos and tutorial result are meant as reference examples but not as fully featured controls.

**Comment by LeadGuitarMx** [comment]
Thanks so much!! : )
