### ISSUE TITLE
Add Support for Capella File Format

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#375]
# Description 
Capella is quite a popular software for writing music notation. Their file format is CapXML which is XML based and publicly documented. Unfortunately a lot of notation elements are added as graphical annotations and do not have a direct element in the data model. Basic support should be possible quite quickly but detecting all the features of alphaTab might be quite abit of effort. 

https://www.capella-software.com/

**Comment by n-ice-ch** [comment]
Please find a Capella example attached in various formats (CapellaXML, PDF, musicXML compressed and uncompressed).
Goal is to present the notation similar to the PDF as this would help the singers to see the current note and text.

For most of singers it is very handy if they can hear their own voice and maybe the upper voice (called "Jodel") but not others. Therefore the alphaTab could a great help.
[capella_jodellied.zip](https://github.com/CoderLine/alphaTab/files/5020421/capella_jodellied.zip)

Cheers from Switzerland!

**Comment by Danielku15** [comment]
Does this file contain all kind of annotations that you will need for an initial Capella support? I found out that many annotations (vibratos, dynamics, etc.) are just textual annotations and are not explicitly part of the data model. Therefore a textual detection needs to be added for those. 

The more example files with different annotations you can provide for the usage on your side, the more likely it is to have them all available earlier than later 😉
