### ISSUE TITLE
Volume, Panning and Cursor control?

### ISSUE THREAD

**Issue by LeadGuitarMx** [CoderLine/alphaTab#384]
# Question 
**1. There is a way of setting up the volume of each track type on alphatab load?**
Thanks to your previous response now I can identify the track type and change the icon.
But now I would like to set the volume for each type of tracks because some tracks are always louder and the player doesn't sounds good like that. : |

**2. AlphaTab supports track panning?**

**3. There is an option for move the cursor?**
    With this code I can use the space key on my keyboard for play/pause the player.
```
     	document.body.onkeyup = function(e){
		if(e.keyCode == 32){
			api.playPause();
		}
	}
```

Now I would like to use the left and right arrows of the keyboard for moving the cursor 1 compas left or right.
Is that possible?

Can you show me the way ? :D

Thanks a lot for all your work. Cheers : )

# Your environment (if applicable)

* Version used: alphaTab v1.0.0-alpha.27 (develop, build 27)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Google Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by Danielku15** [comment]
1. "There is an API call for that" :wink: https://alphatab.net/docs/reference/api/changetrackvolume/ 
2. Yes it does, but it mostly takes this information out of the input file format. Guitar Pro stores some pan informaion which is filled into the `track.playbackInformation.balance` property. This propery will be considered on midi generation and playback. Dynamic changes during playback (automations) or programmatic changes are currently not supported. Feel free to file a feature request for that. 
3.  There is nothing built in like that. But it also does not make a lot of sense to have a direct API for it. Anyhow you can use a combination of the data model and the player related events/properties to achieve your wish. 
```js
let currentBeat = null;
api.playedBeatChanged.on(e => { currentBeat = e.beat;});
function nextBeat() { if(currentBeat && currentBeat.nextBeat) { api.tickPosition = currentBeat.nextBeat.absolutePlaybackStart; } )
function previousBeat() { if(currentBeat && currentBeat.previousBeat) { api.tickPosition = currentBeat.previousBeat.absolutePlaybackStart; } )
```

**Comment by LeadGuitarMx** [comment]
Hello, thanks for answering.
I'm not so good at javascript 😅. 
But if I understand.. for using the api I need to give the array of tracks?
But how can I know which track is the [0], [1], etc...? 
If I already have the code where I know the track type:
`function getTrackType(track) {
    const pi = track.playbackInfo;
    if(pi.primaryChannel === 9) {
        return 'Percussion';
    } else if(pi.program <= 7) {
        return 'Piano';
    } else if(pi.program <= 15) {
        return 'ChromaticPercussion';
    } else if(pi.program <= 23) {
        return 'Organ';
    } else if(pi.program <= 31) {
        return 'Guitar';
    } else if(pi.program <= 39) {
        return 'Bass';
    } else if(pi.program <= 47) {
        return 'Strings';
    } else if(pi.program <= 55) {
        return 'Ensemble';
    } else if(pi.program <= 63) {
        return 'Brass';
    } else if(pi.program <= 71) {
        return 'Reed';
    } else if(pi.program <= 79) {
        return 'Pipe';
    } else if(pi.program <= 87) {
        return 'SynthLead';
    } else if(pi.program <= 95) {
        return 'SynthPad';
    } else if(pi.program <= 103) {
        return 'SynthEffects';
    } else if(pi.program <= 111) {
        return 'Ethnic';
    } else if(pi.program <= 119) {
        return 'Percussive';
    } else if(pi.program <= 127) {
        return 'Soundeffects';
    }
    return 'Unknown';
}`

I can't put something there for change the volume? : )

About the panning.. I think I know where is the problem, 🤔 When 2 guitars are doing the same and are panned 1 left and 1 right (like when we record 2 rhythm guitars and they sound in stereo) with midi they are the same and for that reason they sound Mono (in the middle) and louder. That's why the panning will work only when guitars are doing different things. :D

So.. I think that can make a bit complicated to implement a panning control on Alphatab no? 🤔

And about the currentBeat, it's for moving the cursor by note, right?  I wanted to move a whole bar (compas) like we do on the Guitar Pro software.

But if it's complicated maybe I'll let it  like that 😁 is already amazing all what you archived to do for displaying and playing the tabs. 

Thanks so much for all. Have a good one 🍻 cheers!

**Comment by LeadGuitarMx** [comment]
I understand, no worries 🙂 thanks so much for responding 👍
