### ISSUE TITLE
Play midi using custom instruments sounds

### ISSUE THREAD

**Issue by nikolayrantsev** [CoderLine/alphaTab#393]
# Question

Dear all,

Apologies if this is already answered question, but - it might be interesting for the community as well -
I'm wondering if it's possible to play midi using custom synth - like sound banks in the Guitar Pro or instruments as the external midi-plugins?
The general purpose is to extend the sound palette of the instruments, tune effects, etc,

Thanks for any feedback in advance!

**Comment by cheap-glitch** [comment]
Yes, alphatab can load any soundfont in the SF2 format:
https://www.alphatab.net/docs/reference/api/loadsoundfont/
https://www.alphatab.net/docs/guides/multiple-soundfonts

**Comment by nikolayrantsev** [comment]
This is very helpful, 
Thank you!
