### ISSUE TITLE
Vibrato settings implementation question

### ISSUE THREAD

**Issue by nikolayrantsev** [CoderLine/alphaTab#395]
# Question 

Hi everyone, 

Appreciate any help with the vibrato [settings](https://www2.alphatab.net/docs/reference/settings/player/vibrato#vibrato-settings),
I'm trying to reduce the amplitude/depth  of the vibratio  - make it more 'plain', e.g. very slightly vibrato - over the basic [sample](https://www2.alphatab.net/docs/tutorial-web/player#final-file):

<img width="775" alt="AlphaTab Tutorial 2020-08-29 04-38-48" src="https://user-images.githubusercontent.com/59288233/91625639-96666e80-e9b1-11ea-9d2f-50e838c8ee59.png">

To do that, vibrato settings added to _player_ object.

I've changed the values of the vibrato settings from 1 to 10000(!). Unfortunately, there is no difference. Where might be the issue?

Thank you!

      const settings = {
        file: "https://www.alphatab.net/files/canon.gp",
        player: {
          enablePlayer: true,
          soundFont:
            "https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/soundfont/sonivox.sf2",

            beatSlightAmplitude:  3,
            beatSlightLength: 240,

            beatWideAmplitude: 3,
            beatWideLength: 240,

            noteSlightAmplitude: 2,
            noteSlightLength: 480,

            noteWideAmplitude: 2, 
            noteWideLength: 480,

            songBookDipDuration: 150,
        },
      };

# Your environment 

* Version used: https://www2.alphatab.net/docs/tutorial-web/player#final-file
* Platform used: JavaScript 
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS 10.15.1 (19B88)
* Link to your project: local

**Comment by cheap-glitch** [comment]
My guess is that your values are not taken into account because they aren't in the `vibrato` sub-property, e.g.:
```
const settings = {
    player: {
        vibrato: {
            noteSlightAmplitude: 2,
            // [...]
        }
    }
}
```

**Comment by Danielku15** [comment]
I would also say that the issue is coming from the missing nesting to the `vibrato`. I just made locally a test with the right structure and the settings are working.

**Comment by nikolayrantsev** [comment]
Thanks a lot, 
Clear now, works fine
