### ISSUE TITLE
Metronome bug

### ISSUE THREAD

**Issue by LeadGuitarMx** [CoderLine/alphaTab#400]
# Your environment

* Version used: alphaTab v1.0
* Platform used: JavaScript 
* Rendering engine used: SVG (default)
* Browser Name and Version: Microsoft Edge, Google Chrome, Firefox
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

# Expected Results

Play the tab and activate the metronome while playing.

# Observed Results

The metronome take a random sound instead the metronome sound.

# Steps to Reproduce (for bugs)

It happens only when you activate the metronome while already playing the tab.
Same problem on the alphatab.net website

# One more thing
I would like to know how can I use the resizeRender() function on a: onclick function :D
I'm working on this template with a hideable sidebar, but when I toggle the sidebar I want that AlphaTab take the free space.
I did a little video for you with the metronome issue and my template : )
[https://youtu.be/uBhjkQGyzrE](https://youtu.be/uBhjkQGyzrE)

Thanks for all 🙂🍻 cheers

**Comment by Danielku15** [comment]
Regarding your question on the resize() function: alphaTab listens to the resize events of the main window to trigger a resize related rendering. You can just fire off a resize event and alphaTab should do the rest: 
https://stackoverflow.com/questions/1818474/how-to-trigger-the-window-resize-event-in-javascript

**Comment by Danielku15** [comment]
The metronome should now activate properly again. Just grab the next version which will be published in few minutes
