### ISSUE TITLE
Alpha 1.1.0 soundFonts other than the default one not playing any sound

### ISSUE THREAD

**Issue by MDoder97** [CoderLine/alphaTab#411]
# Your environment

* Version used: alphaTab - alpha version
* Platform used: JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: Google chrome
* Operating System and version (desktop or mobile): Windows

# Expected Results
Playing of the different soundFonts, goal is to load multiple.
I loaded them like this on initialization
```
player: {
        enablePlayer: true,
        soundFont: downloadUrl
      }
```

# Observed Results
Tried with 2 different soundfonts, no sound playing for any. Only for the default one.

# Steps to Reproduce (for bugs)
I imported alphaTab like this `<script src="https://cdn.jsdelivr.net/npm/@coderline/alphatab@alpha/dist/alphaTab.min.js"></script>`
Tried playing, player runs but no sound is played.

Download link for one of the soundfonts not being played - https://firebasestorage.googleapis.com/v0/b/tabster-17296.appspot.com/o/Guitarra%20Acustica.SF2?alt=media&token=a8857021-b19d-4e34-8aab-991aebc79b10

Sidenote - have you considered opening a discord server? It's more lightweight and popular than Gitter.

**Comment by Danielku15** [comment]
Yes, I tried a lot of different soundfonts and did not run into any core issues. Only the lack of some SoundFont2 feature support might lead to slightly different audio than on other synths like FluidSynth. Also the font you provided is working fine. The sepecial thing you have to consider is: The file contains only 1 definition for the midi instrument number 15 which is actually Dulcimer and not Acoustic Guitar as described: 
![image](https://user-images.githubusercontent.com/674916/96765766-73b56c80-13da-11eb-8369-4c318a4317d6.png)

AlphaTab will search for matching presets within the loaded soundfonts, if no preset is found, nothing is played. 


Regarding Discord I had a look when searching for the future chat solution but rather decided against it. You need a separate account there and the platform is rather for gaming. Gitter allows you to login with your GitHub account which I thought is a better fit for alphaTab. I also think that once GitHub Discussions are public, people will rather drop there messages for discussions.

**Comment by Danielku15** [comment]
@MDoder97 any feedback on this topic? Otherwise I would close this issue.

**Comment by MDoder97** [comment]
Didnt get chance to test it out, but i believe i can get it working with the feedback u provided. Should i edit the soundfont in Polyphone etc. To match presets?

You can close it otherwise

**Comment by Danielku15** [comment]
I can recommend Polyphone to adjust soundfonts, it's a easy-to-use tool for such tasks. 😉 
Let me know if you need more help or if you have a good idea on how to make such soundfonts easier to use, feel free to open a feature request for your idea.
