### ISSUE TITLE
how can I display the one tarck is tab the othe track is score in multitracks rendering?

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#415]
# Question 
 Hello,
I find the staveProfile Settings  is change all the tracks .But I want this effect, the first track shows Tab, the second track shows the  score, How can I do it，Thank.

 
# Your environment (if applicable)

* v1.1.0-alpha.44 (develop, build 44)
* JavaScript
* SVG
* Chrome
* Windows 10 desktop

**Comment by goodgame365** [comment]
Like this
![alhpatab](https://user-images.githubusercontent.com/17884664/96359862-173c1e00-114a-11eb-9c69-4ce8f2579a0e.jpg)

**Comment by Danielku15** [comment]
As of today there is no setting controlling the staff profile per track. What you could try as a workaround is to change the data model to indicate that only certain staves are shown. https://github.com/CoderLine/alphaTab/blob/develop/src/model/Staff.ts#L67
Some GuitarPro files indicate which staves should be shown, that's why this "hidden" gem exists. 
Just hook into the [`scoreLoaded`](https://alphatab.net/docs/reference/api/scoreloaded/) event and [adjust the data model](https://alphatab.net/docs/reference/score) as you need it. 

Otherwise feel free to open a feature request will all details on what you would need and how it should work.

**Comment by goodgame365** [comment]
thank very much,I I seem to understand，Although I don't know the syntax of aphatab's data model very well, I believe it will be solved after research,thank.

**Comment by goodgame365** [comment]
thank，I seem to understand，  But I don't know what the data model structure syntax of aphatab，
I found a stupid way
 like this
![未命名-2](https://user-images.githubusercontent.com/17884664/96907618-0c78e480-14ce-11eb-83d5-41cd714a34f9.png)
When I press this score button ,I set a global variable tc      =this,track.index
But I don't know why this variable tc didn't come over 

------------------------
     for (var s = 0; s < n.staves.length; s++) {
                                var h, c = void 0;
                             
                                if (s == tc) {
                                  
                                    c = t.StaveProfile.Score;
                                }
                                else {
                                    console.log(tc);
                                    if ((h = n.staves[s]).isPercussion) c = t.StaveProfile.Score;
                                    else if (this.renderer.settings.display.staveProfile !== t.StaveProfile.Default) c = this.renderer.settings.display.staveProfile;
                                    else if (h.showTablature && h.showStandardNotation) c = t.StaveProfile.ScoreTab;
                                    else if (h.showTablature) c = r ? t.StaveProfile.TabMixed : t.StaveProfile.Tab;
                                    else {
                                        if (!h.showStandardNotation) continue;
                                        c = t.StaveProfile.Score
                                    }
                                }
                                for (var u = 0,
                                    l = Xh.staveProfiles.get(c); u < l.length; u++) {
                                    var p = l[u];
                                    p.canCreate(n, h) && e.addStaff(n, new Zo(i, h, p))
                                }
                            }

**Comment by goodgame365** [comment]
Front post is wrong，Right should be
if ((h = n.staves[s]).isPercussion || this.renderer.tracks[i]==tc) c = t.StaveProfile.Score;

**Comment by goodgame365** [comment]
Thank Very Much,Although I don't know anything about data models，But I noticed that the track of percussion instruments can only show staff, so I think the current version can be implemented，I've noticed what you mentioned #358 ，so  I try to write like this on your control.js

------
    const tabButton = trackItem.querySelector('.at-track-tab');

    const scoreButton = trackItem.querySelector('.at-track-score');

    scoreButton.onclick = function (e) {
         
      
        track.staves[0].isPercussion = true;
        
         scoreButton.classList.toggle('active');
        at.changeTrackMute([track], muteButton.classList.contains('active'));

        
    };
-----
When I press the button, I force it to be a percussion instrument  （track.staves[0].isPercussion = true;）
![1](https://user-images.githubusercontent.com/17884664/97589804-ef499600-1a38-11eb-868d-684dfc745bba.png)
![Uploading 2.png…]()

**Comment by goodgame365** [comment]
![2](https://user-images.githubusercontent.com/17884664/97590005-261fac00-1a39-11eb-815e-39cfdcfd0960.png)

**Comment by goodgame365** [comment]
sorry ,The front is wrong

track.staves[0].isPercussion = true; is wrong

Right should be ：
 track.staves[0].showTablature = false;

**Comment by goodgame365** [comment]
![3](https://user-images.githubusercontent.com/17884664/97592799-02aa3080-1a3c-11eb-895f-495868b2bcf4.png)

**Comment by goodgame365** [comment]
![5](https://user-images.githubusercontent.com/17884664/97593178-616faa00-1a3c-11eb-8e81-8a589f32639f.png)

**Comment by goodgame365** [comment]
![66](https://user-images.githubusercontent.com/17884664/97640575-08276b00-1a7c-11eb-9a62-9ccbfd585ed5.png)

**Comment by Danielku15** [comment]
@goodgame365 It seems the formatting of your comment did quite get messed up. It is hard to extract from it your concrete questions. Can you adjust your post to have the code properly wrapped with the [markdown block for code](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). I hope you understand that I cannot give you personal consulting for the things you would like to develop. I am happy to give any input on things you do not understand from alphaTab side but building the solution on top is up to you 😉

**Comment by goodgame365** [comment]
Sorry, I don't know how to use GitHub，and English is poor, too！

My  test web is  http://goodgame365.qicp.io/play.html  
 
Now it has been realized I warnt I need

**Comment by Danielku15** [comment]
I fear from your comments I cannot extract what you need. If you have some open dedicated questions please try to state them in a shape I can understand. Try to narrow down your concrete obstacles and then ask the specific questions. From a huge code piece of your overall solution and no clear questions I cannot help you. 

Feel free to re-open this issue if you managed to shape your request understandable. I am not speaking any Chinese either and the world of development (including this library) is rather in English.
