### ISSUE TITLE
Uncaught TypeError: this.onResize / _this.triggerResize is not a function

### ISSUE THREAD

**Issue by kyledecot** [CoderLine/alphaTab#417]
# Your environment

* Version used: Latest NPM
* Platform used: JavaScript 
* Rendering engine used: SVG
* Browser Name and Version: Brave Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): MacOS Catalina 10.15.7 (19H2)
* Link to your project: Not Publicly Accessible

# Expected Results

When using the following boilerplate I expect to get a basic "Hello World"

```
<!doctype html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/alphaTab.js"></script>
  </head>
  <body>
    <div id="player"></div>
    <script>
      alphaTab.AlphaTabApi(document.getElementById('player'), {
        file: "https://www.alphatab.net/files/canon.gp",
      })
      </script>
  </body>
</html>
```

# Observed Results

Two separate but similar errors are raised:

```
Uncaught TypeError: this.onResize is not a function
    at Object.AlphaTabApiBase (alphaTab.js:21443)
    at Object.AlphaTabApi (alphaTab.js:24226)
    at index.html:9
```

```
Uncaught TypeError: _this.triggerResize is not a function
    at alphaTab.js:21428
```

<img width="1248" alt="Screen Shot 2020-10-20 at 7 01 24 AM" src="https://user-images.githubusercontent.com/192464/96577782-23d38a00-12a2-11eb-8892-25b95d79cbd8.png">

# Steps to Reproduce (for bugs)

1. Save Provided Markup to `index.html`
2. Open `index.html` in browser
3.  Open Chrome Developer Tools

# Possible Solution 

Unknown

**Comment by Danielku15** [comment]
I would recommend that you follow the tutorial in https://alphatab.net/docs/tutorial-web/introduction
alphaTab is an Object Oriented Library, meaning that you need to create a new instance of the API class with `new` and not just call the function. If you call the function without `new` no instance scope `this` is created for the class and it will result in your explained problem.

**Comment by kyledecot** [comment]
Wow–I must've looked at that code snippet a dozen times and didn't see that I had omitted `new` 🤦. Thank you for your prompt response and all of the hard work that you've done on this project.
