### ISSUE TITLE
Error on yarn build (npm run build)

### ISSUE THREAD

**Issue by wassertim** [CoderLine/alphaTab#423]
build command gives an error:

```sh
[!] (plugin dts) TypeError: Could not load /Users/wassertim/dev/alphaTab/dist/types/alphatab.d.ts: ts.isNamedTupleMember is not a function
TypeError: Could not load /Users/wassertim/dev/alphaTab/dist/types/alphatab.d.ts: ts.isNamedTupleMember is not a function
    at DeclarationScope.convertTypeNode (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:766:16)
    at DeclarationScope.convertMembers (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:711:22)
    at DeclarationScope.convertTypeNode (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:754:25)
    at Transformer.convertVariableStatement (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1176:19)
    at Transformer.convertStatement (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1078:25)
    at new Transformer (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:995:18)
    at transformFile (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1315:29)
    at Object.load (/Users/wassertim/dev/alphaTab/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1370:33)
    at /Users/wassertim/dev/alphaTab/node_modules/rollup/dist/shared/rollup.js:18720:25

error Command failed with exit code 1.

```

Is it only me? Or it is a known bug?

# Your environment

* Version used: (master branch)
* Platform used: NPM / Typescript
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: Chrome 86
* Operating System and version (desktop or mobile): Mac OS X 10.15.7
* Link to your project: (there is no project yet)

# Expected Results
build is successful

# Observed Results
yarn build gives an error: 
[!] (plugin dts) TypeError: Could not load /alphaTab/dist/types/alphatab.d.ts: ts.isNamedTupleMember is not a function

# Steps to Reproduce (for bugs)

1. yarn
2. yarn build

or

1. npm install
2. npm run build

# Possible Solution 
I could investigate, but I need to know if it is only me who has this error

**Comment by Danielku15** [comment]
I would say it is not a general issue. It works at least fine on my multiple machines and also on the CI environment. From the error message I could imagine that it has something to do with the TypeScript version. If you have already the latest TypeScript version installed (globally?) on your system it could maybe conflict with the 3.9.x currently used by alphaTab. I would have imagined that `rollup-plugin-dts` uses the typescript version installed in the current working dir but maybe it's using some global version. 

I planned to upgrade to TS4 soon but it will likely take some more time until it will come. I would give it a try to ensure TS3.9 is used on your system/working dir and it should solve the issue.

**Comment by wassertim** [comment]
I removed global typescript and this did not help. I can take over the task with upgrading to TS4 (it has already came). What do you think?

**Comment by wassertim** [comment]
Ok, I figured this out. The problem is with this library:
`"rollup-plugin-dts": "^1.4.8"`. This setting caused on my maschine downloading of the most recent minor version, which is: `1.14.13` and is not compatible with typescript `3.9.6`. 

Just try changing in it in package.json on your computer and you can reproduce it:
`"rollup-plugin-dts": "^1.4.13"`

Setting `"rollup-plugin-dts": "^1.4.8"` to `"rollup-plugin-dts": "1.4.10"` fixes the problem.

`"rollup-plugin-dts": "1.4.10"` seams is the latest version compatible with TS: 3.9.6


Should I create a PR for that?

**Comment by Danielku15** [comment]
> For that you should make me a contributor. I would love to contribute actually. I see a lot of potential in this project.

I am happy to accept contributions. You can contribute by simply pulling a Fork of alphaTab into your personal account, prepare any changes in a new branch and open a pull request once you're done. If you are new to this workflow there are quite some good guides around the topic how to contribute to projects on GitHub: 

https://github.com/firstcontributions/first-contributions
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/
https://www.dataschool.io/how-to-contribute-on-github/
