### ISSUE TITLE
Disable automatic responsive resizing

### ISSUE THREAD

**Issue by rhclayto** [CoderLine/alphaTab#430]
# Question 
Is it possible to disable automatic resizing/responsive design of the rendered score, & instead call the api.render() method from other code when needed? I'm trying to use this in a Vue.js component, where other resize events are going on, & the automatic responsive resizing of AlphaTab & the other resizing logic are conflicting. I looked at the settings object but didn't find any seemingly related setting.

# Your environment (if applicable)
* Version used: latest dev branch from npmjs
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox & Chrome, latest
* Operating System and version (desktop or mobile): Windows 10

**Comment by Danielku15** [comment]
There is no way to disable the resizing logic, but also it is not really needed for your usecase. The setting was removed at some point. AlphaTab computes the available size from the parent element, you can simply ensure via CSS that the width of the parent element is fixed. At any point you can decide to resize the parent container and via a call to `render` trigger a new rendering. 

If you hook into the `postRenderFinished` you can load the new width and maybe apply it to your parent container as fixed size. Then based on your preferred resizing logic, at any time you change the width of the parent container and trigger a re-render manually.

**Comment by rhclayto** [comment]
Thanks for your advice. I will close this since you've answered my question superbly.
