### ISSUE TITLE
Manually show & advance cursor

### ISSUE THREAD

**Issue by jxmorris12** [CoderLine/alphaTab#433]
# Question 

I'd like to manually show the cursor on the first beat of a tab, and then advance it beat by beat - for example, as the user click a button. I imagine this should be possible since it's automatically done during playback. But I want to show and advance the cursor, on demand, outside of playback. Is there an easy way to do this?

**Comment by Danielku15** [comment]
I would recommend to read through the discussion here: https://github.com/CoderLine/alphaTab/issues/401 Your request sounds similar . Simplified said you would simply activate the player, but do not call `play`. When you then change the `tickPosition` the cursor will adjust to the position. Does this help you further?

**Comment by jxmorris12** [comment]
yes, changing the tick position worked! Thank you!
