### ISSUE TITLE
TypeError: Cannot read property 'beat' of null

### ISSUE THREAD

**Issue by kyledecot** [CoderLine/alphaTab#435]
# Your environment

* Version used: 1.0.1
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Brave Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): MacOS Catalina 10.15.7 (19H2)
* Link to your project: N/A

# Expected Results

No Errors

# Observed Results

When clicking on any part of the rendered tablature in my NextJS/React application I am receiving the following error:

```
TypeError: Cannot read property 'beat' of null
```

# Steps to Reproduce (for bugs)

1. Create a NextJS/React application w/ the following `Player` component:

```
import { createRef, Component } from "react"

require("@coderline/alphatab")

require("@coderline/alphatab/dist/font/Bravura.ttf")
require("@coderline/alphatab/dist/font/Bravura.woff")

import Sonivox from "@coderline/alphatab/dist/soundfont/sonivox.sf2"

class Player extends Component {
  constructor(props) {
    super(props)
    this.player = createRef()
  }

  componentDidMount() {
    this.api = new alphaTab.AlphaTabApi(this.player.current, {
      fontDirectory: "_next/static/fonts/",
      file: "https://www.alphatab.net/files/canon.gp",
      soundFont: Sonivox
    });
  }

  render() {
    return (
      <div ref={this.player}>We have alphatab!</div>
    )
  }
}

export default Player
```

2. Open the application in the browser and click any part of the rendered tablature.

<img width="1451" alt="Screen Shot 2020-11-13 at 9 19 43 AM" src="https://user-images.githubusercontent.com/192464/99081831-603c9200-2591-11eb-8de2-d03059e58cc4.png">

# Possible Solution 

Unknown

**Comment by Danielku15** [comment]
Can you check if the error still exists on the latest 1.1 alpha? I remember fixing some things in this area. I am a bit wondering why the click handlers are active. They should only be active if you also activate the player. This might be the root cause but I will have to check this in detail.

**Comment by Danielku15** [comment]
Closing this bug due to inactivity, feel free to re-open it in case there is something left.
