### ISSUE TITLE
JSON conversion looses Chords Map

### ISSUE THREAD

**Issue by thoun** [CoderLine/alphaTab#438]
JSON conversion doesn't support Map, which are used for Staff Chords. A JSON converted back to score will not render if he had chords.

# Your environment 

* Version used: develop
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: All
* Operating System and version (desktop or mobile):All
* Link to your project:

# Expected Results
Chords are maintained through JSON conversion

# Observed Results
Chords are converted to `{}` on JSON strings

# Steps to Reproduce (for bugs)
```
const JsonConverter = alphaTab.model.JsonConverter;
console.log(result, JsonConverter.scoreToJson(this.data.gpSong));
```

# Possible Solution 
Option 1 : Use a pair array on Staff Js Object instead of Map using theses methods : https://2ality.com/2015/08/es6-map-json.html
Option 2 : Patch JSON.stringify, if possible, the same way it has been done here https://github.com/CoderLine/alphaTab/blob/646c2e326ba960cffddbe795d0b6caec551d44e8/src/model/JsonConverter.ts#L48
functions : https://stackoverflow.com/questions/29085197/how-do-you-json-stringify-an-es6-map

**Comment by Danielku15** [comment]
It seems you closed this bug report already but just to take statement: The map serialization/deserialization should work fine. 

Notice the serialization: 
https://github.com/CoderLine/alphaTab/blob/7c969374b8605730168490ce5cea95af5a6cd41c/src/model/JsonConverter.ts#L105-L109

And the deserialization:
https://github.com/CoderLine/alphaTab/blob/7c969374b8605730168490ce5cea95af5a6cd41c/src/model/JsonConverter.ts#L318-L322

If this is really for you still an issue feel free to re-open this bug and try to provide a fiddle showing the issue you're facing, there might be something special in your setup to consider.

**Comment by thoun** [comment]
It works fine as long as you dont go through JSON. I suppose the internal use with webworker user objects and not JSON, so it's not really a bug, and my need doesn't justify a new dev on the project. I found another way so I closed the issue.
