### ISSUE TITLE
AlphaTab - music not visible

### ISSUE THREAD

**Issue by Gitaartabs** [CoderLine/alphaTab#44]
Hi Daniel,

After the new install that you recommended I still have the same problem that the sheetmusic is not visible. Is it me doing something wrong?

http://www.gitaartabs.nl/guitar-pro/the-common-linnits/calm-after-the-storm-solo

thanks already
Jan

**Comment by Danielku15** [comment]
The "calm-after-the-storm-solo" file can be loaded with the latest build. I will close this defect but added a new #70 for tracking the overall GPX file format support.
