### ISSUE TITLE
Support per track volume from Guitar Pro 7 file format

### ISSUE THREAD

**Issue by jordanske** [CoderLine/alphaTab#446]
# Description 
Currently when using .gp files from Guitar Pro 7 all track volumes are the default (15). 
Alphatab does not use the track volumes set in Guitar Pro 7.

This works fine with .gp5 files but fails to do so with .gp.

**Setting in Guitar Pro 7:**
![track volumes in Guitar Pro 7](https://i.imgur.com/mROfa2R.png)

**Exported as .gp5:**
![track volumes in AlphaTab with .gp](https://i.imgur.com/MOplIkl.png)

**Exported as .gp:**
![track volumes in AlphaTab with .gp](https://i.imgur.com/YTAY10S.png)

# Possible Solutions
Modifying the gpif importer to support this.
I already created a pull request with a possible solution: #445 

# Current Workarounds 
Using .gp5

**Comment by Danielku15** [comment]
Thanks for this finding and your planned contribution. Funny I never realized that the volume components are missing when read. It seems that also other parts like the balance are missing, would be good to add them too.

**Comment by Danielku15** [comment]
Closed with #445
