### ISSUE TITLE
No sounds on IPhone

### ISSUE THREAD

**Issue by pratamishus** [CoderLine/alphaTab#456]
Hi!

The alphatab.js player does not sound at all on IPhone. Even the example on alphatab.net home page does not make any sounds when played. It's very weird as it works fine on any other devices. 

What could be the reason? Thanks.

**Comment by Danielku15** [comment]
The usage of templates is mandatory as indicated by all the comments and contribution guidelines. Issues not following the templates are closed without follow up.
