### ISSUE TITLE
Metronome, Tracklist functions and playback speed not working

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#457]
# Your environment

* Version used: 1.1.0
* Platform used: JavaScript (JQuery)
* Rendering engine used: SVG
* Browser Name and Version: MS Edge Chromium
* Operating System and version (desktop or mobile): Windows 10, Desktop
* Link to your project: https://emotive.productions/notation/through-the-looking-glass/stave/

# Expected Results

Metronome should function and tracklist should be retrievable, in addition playback speed should be able to be altered as a percentage

# Observed Results
Metronome cannot be switched on, tracklist isn't visible with one or multi-track files and playback speed only works at 100%

# Steps to Reproduce (for bugs)

1. Press play
2. Pause play or stop
3.  Press play after playback has stopped and attempt to engage metronome, click tracklist or try to adjust playback speed

# Possible Solution 
Use pre 1.0 Alphatab library

**Comment by Danielku15** [comment]
Can you please try to provide a minmal example on what you are doing and what is not working? Also please try to open one bug report per problem with a clear steps to reproduce **from alphaTab perspective**. I hope you can understand that I cannot dig into all the details of your particular implementation/integration. 

On high level: 
- The metronome is still using the [`metronomeVolume`](https://www.alphatab.net/docs/reference/api/metronomevolume) setting to get activated/deactivated. There were various bugfixes in 1.1 regarding the metronome but it should still work like before. In general the metronome is working like we can see on the [main alphaTab website](https://www.alphatab.net/)
- Loading tracks also works like before via [`score`](https://www.alphatab.net/docs/reference/api/score) or [`tracks`](https://www.alphatab.net/docs/reference/api/tracks)
- Also the [`playbackSpeed`](https://www.alphatab.net/docs/reference/api/playbackspeed) works like before. 

I grabbed the 1.1 released tag, launched the [`playground`](https://github.com/CoderLine/alphaTab/blob/v1.1.0/playground-template/control.js) and for me all features were working as before. 

You mention that you are using a pre 1.0 library. Have you noted all the breaking changes and that you need to upgrade your code? 

https://www.alphatab.net/docs/guides/breaking-changes-095-096
https://www.alphatab.net/docs/guides/breaking-changes-097-098
https://www.alphatab.net/docs/reference/api/scoreloaded/

I just peeked into your code and it seems most of the code you wrote is outdated needs to be updated.

**Comment by Danielku15** [comment]
@nascent Any update here? Otherwise I will close this issue.

**Comment by Danielku15** [comment]
Closing this issue after no response. feel free to re-open it in case there is still an actual open issue.
