### ISSUE TITLE
Not able to get Hammer-on notes to render correctly

### ISSUE THREAD

**Issue by andulv** [CoderLine/alphaTab#46]
I have only tested this with the GDI renderer in WPF control.

I am not sure if I do something wrong, or if there are bugs / missing features related to rendering hammer-on notes.

I am building my own model (from RockSmith 2014 files), but I also noticed that no hammer-ons were rendered when I imported a simple .GP5 file.

I have tried various combinations of properties, but nothing seems to work.

I believe the correct syntax when building the model should be something like this:
note1.isHammerPullOrigin = true;
note2.isHammerPullDestination = true;
note2.hammerPullOrigin = note1;
(note1 belongs to beat1, note2 belongs to beat2. Beats are added sequentially to the same voice.)

The only way I am able to see any result in the renderer is by setting note2.hammerPullOrigin=note2, which leads to a hammer-on line being drawn from note2 to nowhere.

**Comment by Danielku15** [comment]
I didn't encounter any problems in the latest C# version. I'll close this issue.
