### ISSUE TITLE
AlphaSynth output pitch too high for combined bends (bend following a bend)

### ISSUE THREAD

**Issue by WolfgangD** [CoderLine/alphaTab#470]
Happy to provide more details if needed, but here is what we've heard testing latest version on alphaTab.

### Expected Results
Pitch output correctly (e.g. compare Guitar Pros output) for combined bends.

### Observed Results
Pitch is too high (mostly 2 half tones higher) on a combined bend.

See for annotated errors. +2/2 means 2 half tones too high. +1/2 means 1 half tone too high.
<img width="1030" alt="Screen Shot 2020-12-16 at 18 50 59" src="https://user-images.githubusercontent.com/1220328/102764548-984aa800-437b-11eb-8ecc-6c270ebbb905.png">

### Steps to Reproduce
1. Load Notation_Legend.gp
2. play bending bars #3-18

**Version**
- [ ] 1.2 (develop, 72512ceb863027c6919e74c4fe0c4bc55d6e53ab)

**Flavor**
- [X ] JavaScript 

**System**
- Mac OS Big Sur, Safari

```
options = {
                file: filename,
                core: {
                    engine: "svg"
                },
                player: {
                    soundFont: "FluidR3GM.sf2",
                    enableCursor: true,
                    enablePlayer: true,
                    enableUserInteraction: false
                },
                notation: {
                    elements: {
                        ScoreTitle: false,
                        ScoreSubTitle: false,
                        ScoreArtist: false,
                        ScoreAlbum: false,
                        ScoreWords: false,
                        ScoreMusic: false,
                        ScoreWordsAndMusic: false,
                        ScoreCopyright: false,
                        GuitarTuning: false,
                        TrackNames: false,
                        EffectMarker: false,
                        EffectTempo: false
                    },
                    notationMode: 'songbook'
                }
```

**Comment by Danielku15** [comment]
Thanks for reporting this. I thought I have tested the bends quite extensively and validated the right audio. But I fear the combined scenarios might be buggy. I will need to check if it is caused by the midi generation (which I hope) or if it is a side effect within the synth engine.

**Comment by Danielku15** [comment]
Found the buggy parts. There were some left-over paths where for individual notes full beat-bends were generated. This resulted in double bends (beat+note).
