### ISSUE TITLE
Accidentals added to the wrong note after tie

### ISSUE THREAD

**Issue by WolfgangD** [CoderLine/alphaTab#472]
### Expected Results
Accidentals after a tie follow this rule.
![Untitled 3](https://user-images.githubusercontent.com/1220328/102767954-a9e27e80-4380-11eb-96ce-40dde63237fd.jpg)

In the below example, they are expected to show up for the note corresponding to 6,6 tabs in bar 135.

### Observed Results
The accidental is added to the tie target note and could be confuseded with accidentals that apply to the whole bar.
<img width="422" alt="Screenshot 2020-12-21 at 11 37 09" src="https://user-images.githubusercontent.com/1220328/102768136-ef06b080-4380-11eb-8c33-e8d5d67dc5a0.png">

### Steps to Reproduce
1. Load Notation legend bars 134, 135

#### Version
- 1.2 (develop, 72512ce)

#### Flavor
- JavaScript

#### System
- Mac OS Big Sur, Safari

options = {
                file: filename,
                core: {
                    engine: "svg"
                },
                player: {
                    soundFont: "FluidR3GM.sf2",
                    enableCursor: true,
                    enablePlayer: true,
                    enableUserInteraction: false
                },
                notation: {
                    elements: {
                        ScoreTitle: false,
                        ScoreSubTitle: false,
                        ScoreArtist: false,
                        ScoreAlbum: false,
                        ScoreWords: false,
                        ScoreMusic: false,
                        ScoreWordsAndMusic: false,
                        ScoreCopyright: false,
                        GuitarTuning: false,
                        TrackNames: false,
                        EffectMarker: false,
                        EffectTempo: false
                    },
                    notationMode: 'songbook'
                }

**Comment by Danielku15** [comment]
I added some small improvements regarding this case. My Notation Legend (version 10) only has 127 bars, do you maybe already have an updated one?

**Comment by WolfgangD** [comment]
Yes, we do. Forgot to attach here it is: 
[Notation_legend_12.gp.zip](https://github.com/CoderLine/alphaTab/files/5757639/Notation_legend_12.gp.zip)
