### ISSUE TITLE
Data transposition

### ISSUE THREAD

**Issue by bbevren** [CoderLine/alphaTab#482]
### Expected Results

Want to display transposed sound and view
### Observed Results

Ignoring the data attribute data-transposition-pitches 
### Steps to Reproduce

```
<div class="at-viewport">
    <div class="at-canvas" id="alphaTab" 
    data-transposition-pitches="[12]" 
    data-layout-hide-info="true" 
    data-file="/tabs/x.gp5" 
    data-player-scrolloffsetx="-10" 
    data-notation-notationmode="songbook" 
    data-player-enableplayer="true" 
    data-player-soundfont="font/sonivox/sonivox.sf2" 
    data-layout-hide-info="true">
    </div>
</div>
```

### Your environment

**Version**
- [ ] 1.0 
- [ x] 1.1
- [ ] 1.2-alpha.## 

**Flavor**
- [x ] JavaScript 
- [ ] .net 

**System**

**Comment by Danielku15** [comment]
It seems you are missing the `notation-` prefix on your transposition setting. `data-transposition-pitches` should be `data-notation-transposition-pitches`

Reference: https://www.alphatab.net/docs/reference/settings/notation/displaytranspositionpitches/
Working sample: https://jsfiddle.net/danielku15/6e3wbpfg/ 

Hope this helps
