### ISSUE TITLE
Single Bar Rests are handled wrong for MusicXML. 

### ISSUE THREAD

**Issue by brusand** [CoderLine/alphaTab#495]
i create a quater 60BPM score file with musescore in musicxml format (15 pause mesures) and  alpha tadb display 15 measure of sigh 
### Expected Results

15 pause mesures
### Observed Results

15 sigh mesures
### Steps to Reproduce

i create a quater 60BPM score file with musescore
and export in musicxml format
set the file in test-data/audio folder and change the file in playground/control-template.html

### Your environment

**Version**
- [ ] 1.0 
- [ ] 1.1
- [ ] 1.2-alpha.## 
last clone github repo today
**Flavor**
- [ x] JavaScript 
- [ ] .net 

**System**

mac os

**Comment by Danielku15** [comment]
Can you please provide all precise the file you used for reproducing the issue you are experiencing? Also try to provide the exact error you see. From your explanation I do not know what exact error you mean. I have not heard of a term like "sigh mesures" or "pause mesures". 

My best guess is: If you refer to the fact that MuseScore might show [multi measure rests](https://en.wikipedia.org/wiki/Rest_(music)#Multiple_measure_rests) and alphaTab not, this is not a bug and also not specific to MusicXML. alphaTab does not have any feature yet to render multi-measure rests. In MuseScore this grouping is activated dynamically with the shortcut <kbd>M</kbd> when the music sheet is rendered. If this is the case please open a feature request via `Discussions` and explain in a proper fashion what you need and why.

**Comment by brusand** [comment]
here is the photo of the issye [https://www.zonerama.com/chezbruno/Album/6919254](url)

![alphatab copie](https://user-images.githubusercontent.com/1648561/103824184-b3076700-5073-11eb-9187-b684b16e1da7.jpg)
![musescore copie](https://user-images.githubusercontent.com/1648561/103824188-b4d12a80-5073-11eb-9e55-deba19a92e62.jpg)

how to send the musescore file ?

**Comment by brusand** [comment]
here is the file

Le mer. 6 janv. 2021 à 22:14, Daniel Kuschny <notifications@github.com> a
écrit :

**Comment by Danielku15** [comment]
@brusand From the display the issue looks valid. But I'll have to check in detail what is actually written in the MusicXML file to verify if it is an alphaTab import or MuseScore export issue. 

The file upload dialog is right below the textbox when adding new comments to the issue. Or just drag&drop it to the box. https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests. You just need to zip the files because GitHub does not allow all formats. 

Your attempt to send the file via E-mail did not work.

**Comment by Danielku15** [comment]
I gave it a try on my side and it seems this is rather a missing feature than a bug. The affected rests look like this: 
```xml
<measure number="2">
	<note>
		<rest measure="yes"/>
		<duration>4</duration>
		<voice>1</voice>
	</note>
</measure>
```

They have 1 rest with duration 4 inside the XML. This is what alphaTab currently supports. But the important part is the `measure` attribute. According to [the spec](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-rest.htm) this means: 

> If the measure attribute is set to yes, this indicates this is a complete measure rest.

alphaTab currently has no support for "full bar rests" similar to the fact it does not support multi-bar rests. Full bar rests are denoted as `whole` rests. Adding full-bar rests should be fairly straight forward.

**Comment by Danielku15** [comment]
Made the required extensions to show full bar rests as "whole rest".

**Comment by brusand** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <identification>
    <encoding>
      <software>MuseScore 3.4.2</software>
      <encoding-date>2021-01-06</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7.05556</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1683.36</page-height>
      <page-width>1190.88</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <part-list>
    <score-part id="P1">
      <part-name>Batterie</part-name>
      <part-abbreviation>Bat.</part-abbreviation>
      <score-instrument id="P1-I36">
        <instrument-name>Acoustic Bass Drum</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I37">
        <instrument-name>Bass Drum 1</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I38">
        <instrument-name>Side Stick</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I39">
        <instrument-name>Acoustic Snare</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I41">
        <instrument-name>Electric Snare</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I42">
        <instrument-name>Low Floor Tom</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I43">
        <instrument-name>Closed Hi-Hat</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I44">
        <instrument-name>High Floor Tom</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I45">
        <instrument-name>Pedal Hi-Hat</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I46">
        <instrument-name>Low Tom</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I47">
        <instrument-name>Open Hi-Hat</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I48">
        <instrument-name>Low-Mid Tom</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I49">
        <instrument-name>Hi-Mid Tom</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I50">
        <instrument-name>Crash Cymbal 1</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I51">
        <instrument-name>High Tom</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I52">
        <instrument-name>Ride Cymbal 1</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I53">
        <instrument-name>Chinese Cymbal</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I54">
        <instrument-name>Ride Bell</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I55">
        <instrument-name>Tambourine</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I56">
        <instrument-name>Splash Cymbal</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I57">
        <instrument-name>Cowbell</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I58">
        <instrument-name>Crash Cymbal 2</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I60">
        <instrument-name>Ride Cymbal 2</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I64">
        <instrument-name>Open Hi Conga</instrument-name>
        </score-instrument>
      <score-instrument id="P1-I65">
        <instrument-name>Low Conga</instrument-name>
        </score-instrument>
      <midi-device port="1"></midi-device>
      <midi-instrument id="P1-I36">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>36</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I37">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>37</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I38">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>38</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I39">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>39</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I41">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>41</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I42">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>42</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I43">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>43</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I44">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>44</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I45">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>45</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I46">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>46</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I47">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>47</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I48">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>48</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I49">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>49</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I50">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>50</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I51">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>51</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I52">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>52</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I53">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>53</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I54">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>54</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I55">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>55</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I56">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>56</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I57">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>57</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I58">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>58</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I60">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>60</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I64">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>64</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      <midi-instrument id="P1-I65">
        <midi-channel>10</midi-channel>
        <midi-program>1</midi-program>
        <midi-unpitched>65</midi-unpitched>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="119.15">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>0.00</left-margin>
            <right-margin>-0.00</right-margin>
            </system-margins>
          <top-system-distance>70.00</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>percussion</sign>
          <line>2</line>
          </clef>
        </attributes>
      <direction placement="above">
        <direction-type>
          <metronome parentheses="no" default-x="-35.96" relative-y="20.00">
            <beat-unit>quarter</beat-unit>
            <per-minute>60</per-minute>
            </metronome>
          </direction-type>
        <sound tempo="60"/>
        </direction>
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="2" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="3" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="4" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="5" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="6" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="7" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="8" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="9" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="10" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="11" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="12" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="13" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="14" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      </measure>
    <measure number="15" width="68.45">
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
'
here is the musicxml who produce the issue (the same file correctly displayed in guitar pro 7
