### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by dzava** [CoderLine/alphaTab#54]
Could we get a [bower package](http://bower.io/docs/creating-packages/)?

**Comment by Danielku15** [comment]
Sure, I'll create one soon and I'll try to maintain it properly.

**Comment by Elorfin** [comment]
+1
It would be great to be able to install your library from bower. 
Do you have a planned date for this or not ?

Anyway, alphaTab is awesome. Thanks.

**Comment by Danielku15** [comment]
Sorry for the quite delayed answer. The main issue is that for a proper bower package I will need to also finalize the 1.0 release to have a proper semver for registering the package. In the meanwhile it should be possible to consume the package via git, a valid bower.json is in the master branch.

Give this a shot: 

    bower install git://github.com/CoderLine/AlphaTab.git#master

**Comment by Elorfin** [comment]
Thanks for the tip. 
I've not thought to check if I could directly use the git URL.

**Comment by dreamzor** [comment]
Hi, I don't think that current bower package is quite correct:
* it misses jQuery dependency
* it misses alphaSynth library 
* it misses fonts needed by AlphaTab.css.

**Comment by Danielku15** [comment]
*it misses jQuery dependency*
jQuery is not mandatory. If you check the jquery.alphaTab.js you'll see that it is only a thin wrapper around the actual API. 

*it misses alphaSynth library*
alphaSynth is also an optional feature. If you use only the rendering and not any playback functionality alphaSynth is not required. Therefore is no hard dependency to alphaSynth. 

*it misses fonts needed by AlphaTab.css.*
The WebFont rendering is still in progress (see #72) Therefore bower is not yet updated to include the fonts that will actually be used. I think it's a leftover of some experiments. The web font rendering is currently only available on a local branch.
