### ISSUE TITLE
Unicode problem of haxe

### ISSUE THREAD

**Issue by feitian124** [CoderLine/alphaTab#55]
i met problems when using alphaTab.

if title of gp5(3-5) files contain chinese, the title will show as mess.

i found from the complied js version that below codes are used to read title:

```js
	readStringIntUnused: function() {
		this._data.read(4);
		return this.readString(this._data.readByte());
	}
```
while it works for english, it does not work for chinese.
this._data is `haxe.io.BytesInput`, i am not sure how to dig more.

I see haxe may have unicode issue `https://github.com/HaxeFoundation/haxe/issues/3072` until version 3.2. what's the haxe version we are using? can you help  resolve chinese problem?

thank you.

**Comment by feitian124** [comment]
you can check my [repo](https://github.com/feitian124/alphatab) which showing the problem, 

`https://github.com/feitian124/alphatab/blob/master/features.html#L42` read a chinese name gp5 file,
and 
`https://github.com/feitian124/alphatab/blob/master/lib/alphatab/alphaTab.core.js#L3633` 
can not read the title properly.

**Comment by Danielku15** [comment]
Hi there.
Yes the old unmaintained and Haxe based version had problems with Unicode parsing. Please try the new C# based version from this repository. I added proper Unicode parsing some time ago.

**Comment by feitian124** [comment]
thank you Daniel, i will try and close this if it is fine. :+1:
