### ISSUE TITLE
For iOS devices, tab numbers are not vertically centered to the lines

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#556]
### Expected Results

For iOS devices, tab numbers should be vertically centered to the lines

### Observed Results
On iOS devices, the tab numbers are not vertically centered to the lines, causing the tabs hard to read.
See a screenshot of the official website, in which the fret numbers are placed quite above the lines.
![image](https://user-images.githubusercontent.com/41455097/111280279-f9ce9a00-867e-11eb-97e1-489b91688523.png)

### Steps to Reproduce

1. Open the official website with any iOS device

### Further details 

- Tried in both Safari and Chrome on three different iOS devices, the issue is always reproducible
- Android or desktop doesn't have such issue though

### Your environment

**Version**
-  1.2

**Flavor**
- JavaScript 

**System**

- iPhone SE (iOS 13.4)
- iPhone X (iOS 14.4)
- iPad Pro (iOS 14.4)

**Comment by Danielku15** [comment]
Looks like a nasty iOS bug. iOS does not apply CSS to nested elements like the other browsers do.  
http://jsfiddle.net/danielku15/805yq9sz/2/

![image](https://user-images.githubusercontent.com/674916/111348740-c4c34700-8680-11eb-825b-8ad7e72af7c1.png)
vs
![image](https://user-images.githubusercontent.com/674916/111348685-b5dc9480-8680-11eb-806c-016dd8cff62d.png)

But it seems if you use CSS on the right element it works. 
http://jsfiddle.net/danielku15/805yq9sz/5/

This means as a temporary workaround you can add this to your page until I ship an official fix: 

```css
.at-surface-svg text {
   dominant-baseline: central;
}
```

**Comment by Reiji777** [comment]
Thanks for the prompt response. The CSS fix works like a charm!

**Comment by Danielku15** [comment]
Proper bugfix is available in the latest 1.3 and I also released today a 1.2.1 containing this fix. 
As part of the fix I made, I also added a polyfill for the `IntersectionObserver` which is not available on iOS 11.
