### ISSUE TITLE
Can anything be done about Crackling/Static ocassionally when playing?

### ISSUE THREAD

**Issue by MDoder97** [CoderLine/alphaTab#557]
### Expected Results
No crackling.

### Observed Results
Crackling every 10-30 seconds on most tabs

### Steps to Reproduce
Playing most tabs will produce this.
It seems to be a rendering / lag issue. If you point me in the right direction I'll have a look at the source too.

Also I'd be thankful if you could feel me in on this question -> https://github.com/CoderLine/alphaTab/discussions/553

Thanks.

**Comment by Danielku15** [comment]
I cannot confirm that there is a general bug in alphaTab which would cause this. To me it rather sounds your specific setup is suffering of performance issues (your device or your page). I recommend opening a [Discussion](https://github.com/CoderLine/alphaTab/discussions) where you provide more insight on your precise setup and tests you have done.

**Comment by MDoder97** [comment]
I should have been more detailed.
This actually happens on the default implementation you provided as well.
Try this tab for example in the default setup - https://firebasestorage.googleapis.com/v0/b/guitarflow-95c71.appspot.com/o/tabs%2FRed%20Hot%20Chili%20Peppers%20-%20Californication.gp3?alt=media&token=21ce9eb8-eee8-4173-a595-a9a5f861f3da

It should happen somewhere in the first 2-3 lines
Try this and let me know if you hear it.
