### ISSUE TITLE
Metronome only works on first beat

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#567]
### Expected Results

Respect tempo as per .gp file

### Observed Results

Metronome only sounds on the first beat of each bar, and not subsequent beats in each measure

### Steps to Reproduce

1. Play alphatab file
2. Enable metronome
3. Observe result

Link to Project

https://www.emotive.productions/notation/all-the-broken-hearts/stave/

### Your environment

**Version**
- [ ] 1.3-alpha.112

**Flavor**

- JavaScript 

**System**

Windows, FireFox and Chromium

**Comment by Danielku15** [comment]
Thanks for reporting this. As part of some Kotlin related changes this part got broken. I reviewed my changes multiple times but missed this tiny mistake on the condition. Added a test to ensure the right behavior for the future. If you upgrade to the latest 1.3 alpha version it should work again.

**Comment by nascent** [comment]
It's working now, Daniel.

Thank you
