### ISSUE TITLE
Hide track and hide title not working

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#569]
### Expected Results

Track name should be hidden

### Observed Results

Track name is not hidden

### Steps to Reproduce

Use `data-layout-hide-track-names="true"` as a HTML attribute in AlphaTab container

### Your environment

**Version**

1.3-alpha.112

**Flavor**

JavaScript 

**System**

Windows, FireFox and Chromium

**Comment by Danielku15** [comment]
This setting has been moved to `data-notation-elements='{"TrackNames": false}'. See https://www.alphatab.net/docs/reference/settings/notation/elements/
https://www.alphatab.net/docs/guides/breaking-changes-097-098#new-options-for-hiding-elements

Feel free to re-open the issue if the new option does not work for you 😉

**Comment by nascent** [comment]
Hi Daniel,

I tried using the data-attribute and it did not work, and as well using JavaScript, as follows:

`const settings={notation:{elements:{scoreTitle:false,trackNames:false}}};

const api=new alphaTab.AlphaTabApi(document.querySelector('fieldset+div'),settings);`

which also did not work.

Thank you for looking into this.

**Comment by Danielku15** [comment]
Can you try to prepare a jsfiddle/codepen with your issue. I gave it a try and the feature works well, both in passing in settings and the data-attribute:  https://jsfiddle.net/6kyx7hwd/1/

**Comment by nascent** [comment]
I had reversed the "" and '' it works, thank you.

I believe that we will be able to use standard data-attributes, without JSON notation, in future, which would be fantastic.

In the mean time, there is a simple method so I am grateful for your time on this, as always you support your library very well; not just with code but communication.

All the best
