### ISSUE TITLE
notation:{elements:{trackNames:false}} does not work in JavaScript

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#576]
I tried using the data-attribute

``data-notation-elements='{"TrackNames": false}'`

and it did not work, and as well using JavaScript:

`const settings={notation:{elements:{scoreTitle:false,trackNames:false}}};

const api=new alphaTab.AlphaTabApi(document.querySelector('fieldset+div'),settings);`

which also did not work. If my code is incorrect, I will recode.

Thank you

### Expected Results

Hide all track names

### Observed Results

Track names are not hidden

### Steps to Reproduce

Use either a data-attribute or script, and observe result, or lack thereof

Link to Project

https://www.emotive.productions/notation/the-battle-of-belief/stave/ 

### Further details 

It seems that neither trackNames, nor scoreTitle, work in JavaScript. I tried using the data-attribute above, however that does not work either.

### Your environment

**Version**

1.3-alpha.115

**Flavor**

JavaScript 

**System**

Windows, FireFox and Chrome

**Comment by Danielku15** [comment]
Let's handle this topic over at #569. no need to create another issue for the same topic.
