### ISSUE TITLE
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#578]
I am having a problem generating a track list, namely the below mentioned example does not allow access of nodes via querySelector() so I have tried using a Web Component instead.

### Expected Results

Allow use of HTML Custom Elements.

### Observed Results

I am getting the following error:

[AlphaTab][API] An unexpected error occurred TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### Steps to Reproduce

Use HTMLElement constructor()super()

Link to Project

https://www.emotive.productions/notation/the-battle-of-belief/tablature/

### Further details

I don't believe the problem is with my code, since nodes are being generated correctly, however in the example provided:

https://www.alphatab.net/docs/tutorial-web/track-selector

this does not allow access of generated content from outside of (or within) the script function. Saying that, I am unsure as to whether HTML Custom Elements will be supported at any stage so if no fix can be implemented at any time, I will ask about a more simple way to achieve what I am trying to do because I cannot find any code on the home page or examples.

### Your environment

**Version**

1.3-alpha.115

**Flavor**

JavaScript 

**System**

Windows, FireFox and Chrome

**Comment by Danielku15** [comment]
@nascent What's the deal with all these issues lately which are directly closed? Are you really facing issues with alphaTab and just accidentally close the issues? It generates quite some noise and confusion on my side with all these duplicate issues about the same topics.

**Comment by nascent** [comment]
My apologies for that, I could not delete the post, after I had sorted out the problem(s) myself.

There was one issue, where a post did not appear immediately, with an error from Github, so I posted again and but I cannot delete from my side only close.

If you are able to delete them, please do this as they weren't errors in your code but rather mine and I did not see that because an error also shows in AlphaTab.

I appreciate you taking the time to reply personally in relation to your library but I am still learning about the new API, which is much improved in relation to performance.

P.S. I did not know I could re-open as well, so in future this should not be a problem.

**Comment by Danielku15** [comment]
Thanks for clarifying. Wanted to be sure there is nothing for me to work on 😉
