### ISSUE TITLE
AlphaTex not supporting multi-bytes characters in lyrics

### ISSUE THREAD

**Issue by lannka** [CoderLine/alphaTab#579]
### Expected Results
AlphaTex should render multi-bytes characters (such as CJK languages) in lyrics

### Observed Results
CJK characters do not show in lyrics.

### Steps to Reproduce
Link to jsFiddle, CodePen, Project etc.: 
In lyrics, put some CJK chars (chars that have more than 1 byte).
1. https://alphatex-multi-bytes-char.glitch.me/

### Further details 
I think the problem might live here:
https://github.com/CoderLine/alphaTab/blob/bae294df68ed8f79a5c4cebca6179883056e9123/src/importer/AlphaTexImporter.ts#L364-L373

### Your environment

**Version**
- [ ] 1.0 
- [ ] 1.1
- [x] 1.2
- [ ] 1.3-alpha.## 

**Flavor**
- [x] JavaScript 
- [ ] .net 

**System**

**Comment by Danielku15** [comment]
Indeed the alphaTex parser does not respect the right input string encoding. Will work on an improved reading in this area.

**Comment by Danielku15** [comment]
And it's ready, next 1.3-alpha package should have the changes in. Non-Ascii (ANSI), CJK, Emojis, all work now:  
![image](https://user-images.githubusercontent.com/674916/113475026-8e087180-9473-11eb-9073-893bb6628b38.png)

**Comment by lannka** [comment]
Awesome! Thanks for the quick fix.
