### ISSUE TITLE
Page Unresponsive in alphatex-editor.html when starting a new line with `\`

### ISSUE THREAD

**Issue by lannka** [CoderLine/alphaTab#581]
### Expected Results
Editor playground should work with multi-track feature

### Observed Results
While trying to use the editor playground to test the multi-track feature in AlphaTex, I hit an unresponsive page every time when I try to start a new line with `\` char.

### Steps to Reproduce
1. In a local build, open http://localhost:8080/playground/alphatex-editor.html#
2. Then in the bottom text input area, start a new line with `\` char.
3. The browser will freeze

Link to jsFiddle, CodePen, Project etc.: 

1. 
2. 
3.  

### Further details 
The symptom looks to me that there could be an infinite loop triggered in the AlphaTex parser when the input is incomplete. 
If I copy/paste a whole chunk of text `\track "abc"` in a new line, it works fine.

### Your environment

**Version**
- [ ] 1.0 
- [ ] 1.1
- [ ] 1.2
- [ ] 1.3-alpha.## 
- [x] local dev build

**Flavor**
- [x] JavaScript 
- [ ] .net 

**System**
Chrome Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by Danielku15** [comment]
Fixed 😉
