### ISSUE TITLE
System.IndexOutOfRangeException in BeamingHelper.Direction.get()

### ISSUE THREAD

**Issue by webprofusion-chrisc** [CoderLine/alphaTab#59]
When _lastBeat.Voice.Bar.Clef is Neutral the converted int value for Direction will be -1. Encountered this exception when loading a .gp3 file.

**Comment by Danielku15** [comment]
Thanks for that hint. The Neutral clef is not handled properly for the beaming direction. For the neutral clef I need to check where to switch between Up- and Down-Wards Note-Flags.
