### ISSUE TITLE
the cursor and yellow box is not showing!

### ISSUE THREAD

**Issue by nadia-am** [CoderLine/alphaTab#590]
I used the tutorials and add this library in my customer wordpress site but the cursor and yellow selected box is not showing.
in my site after clicking blue button music sheet will show but after playing the cursor and yellow box is not showing.

https://broken-guitar.ir/shop/gole-goldoone-man-notes-tab-simin-ghanem/

**Comment by Danielku15** [comment]
https://github.com/CoderLine/alphaTab/blob/develop/CONTRIBUTING.md#before-entering-an-issue
