### ISSUE TITLE
MusicXML Parser

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#6]
Write a parser which allows importing MusicXML

**Comment by gburlet** [comment]
Hi Daniel,

What's the status of rendering MusicXML files? I saw a single commit for a MusicXML parser that was tagged as work in progress. Just wondering how far along it is?

**Comment by liufeigit** [comment]
hello Danielku15 , Can you give me gp3~gp5 and gpx file format ?
my email is  woaicplusplus@gmail.com

**Comment by rdp** [comment]
+1 from me, I'll offer a $50 bounty for it :)

**Comment by Danielku15** [comment]
Hi there. 
last weeks I was very busy with the new rendering engine that is available now on the master branch. alphaTab supports now properly multistave (e.g. grand staff) and multi track rendering. MusicXML is a very general description of music and covers many things that alphaTab will never be able to render. 

It would be nice to know which chapters of the music XML test suite you require most. Lilypond has quite a nice test result overview about the unofficial music XML test suite. http://lilypond.org/doc/v2.18/input/regression/musicxml/collated-files.html

until which extend do you expect alphaTab to support music XML in the first version. Please try to list the chapters you require most. It's easy to say "everything" should be supported but you all know that this is not gonna be happen easily.

**Comment by khaschuluu** [comment]
+1

**Comment by Danielku15** [comment]
Hi @nascent. 
Thanks for the compliments. MusicXml support is still on an early stage and there is still a lot to do. Whenever dedicated issues pop up i try make improvements but I strongly rely on reports from users/devs on that. 

MusicXML is a strong visual format while alphaTab relies on a semantic model and derives the visuals from it. 

Regarding the tempo and slur please provide some dedicated samples so I can have a look. Supporting tempo changes should not be a big deal. The slurs likely are. AlphaTab does not have yet an advanced collision detection to optimize the slur path, for now the height is dependent on the distance. If you have some samples maybe I can find an optimization.

**Comment by nascent** [comment]
Hi Daniel,

Thanks for writing back.

I have an example here:

https://emotive.productions/alphatab2/

I had used that file (.xml) originally, to create a .gp file, which has tempo changes, which in turn was originally from Cubase (exported as MIDI), then into Forte (exported as MusicXML) and finally the data was imported into Guitar Pro 7 and saved as a .gp file.

The tempo in the example is being played back higher, and there are also huge slurs in the notation.

Thanks again for creating such a fantastic library.

**Comment by Danielku15** [comment]
I consider MusicXML now as supported in a basic fashion. I will rather rely on individual bug-reports and feature requests to get individual things fixed/added.
