### ISSUE TITLE
Cannot open GPX file in newest build

### ISSUE THREAD

**Issue by Elewyth** [CoderLine/alphaTab#60]
The live sample included in the master build cannot open any gpx files. I tried with my own files, as well as with the included gpx files in the files/ directory. I simply get the alert message "error opening file". gp5 works fine.

Some of the files I tested can be opened in the 0.3.0 release, but not all of them (same error message).

**Comment by Danielku15** [comment]
I just tried to open various GPX files using the latest Version from the master branch and they all worked. Did you try the version from the GitHub Releases or the version commited to the Git repository?

**Comment by Elewyth** [comment]
Hi, I tried with the version linked on the alphaTab website (https://github.com/CoderLine/alphaTab/archive/master.zip). I downloaded the zip this morning (like 12 hours ago).

I will try again with the latest version tomorrow. Thanks for your time.

**Comment by Elewyth** [comment]
I tested the sample in the neweset build, and everything seems to work, even some of the files that don't work with the 0.3.0 release! Thanks!
