### ISSUE TITLE
Infinite loop in alternate ending logic

### ISSUE THREAD

**Issue by Tails** [CoderLine/alphaTab#61]
There is an infinite loop in the logic for parsing alternate endings. Try it out with the following tab: http://tabs.ultimate-guitar.com/d/deep_purple/smoke_on_the_water_ver6_guitar_pro.htm

When it gets to parsing bar 43 (1-indexed). which is where the first alternate ending is, it stalls because the currentMasterBar is neither a repeatStart or End and it will never be null since there is a traversal missing, I presume.

```` haxe
while (currentMasterBar != null)
{
    // found another repeat ending?
    if ( currentMasterBar.isRepeatEnd() && currentMasterBar != previousMasterBar)
        break;
    // found the opening?
    if (currentMasterBar.isRepeatStart) 
        break;
    
    existentAlternatives |= currentMasterBar.alternateEndings;
}
````

I think something like the following is missing from the loop:

```` haxe
// walk back the masterbars to find previously found
// alternative endings
currentMasterBar = (currentMasterBar.index != 0) 
    ? currentMasterBar.previousMasterBar
    : null
    ;
````

But even then it will fail somewhere down the line with an EOF exception. I suspect because there is an unconsumed byte somewhere in the repeat logic.

**Comment by Danielku15** [comment]
Thanks for this finding. Looks like there was some buggy parsing of GP4 files. I fixed the problem on the master branch. The mentioned file should now open properly.
