### ISSUE TITLE
Alphatab Auto Scrolling doesn't work

### ISSUE THREAD

**Issue by nadia-am** [CoderLine/alphaTab#624]
I used the code in my wordpress site, the auto-scrolling doesn't work when playing music.
to see the tableture click on blue button.
https://broken-guitar.ir/shop/gole-goldoone-man-notes-tab-simin-ghanem/

**Comment by nadia-am** [comment]
problem fixed by adding `scrollElement: wrapper.querySelector('.at-viewport')` to the seeting as the example did.

**Comment by Danielku15** [comment]
For the future, please follow the contributing guidelines. I think we are quire clear about the fact that the usage of the right issue template and place to ask is mandatory. This is obviously a question and should have been posted in the discussions where you are directed to if you follow the link of the "new issue" chooser.
