### ISSUE TITLE
Speed button doesnt work!

### ISSUE THREAD

**Issue by nadia-am** [CoderLine/alphaTab#625]
as the documentation in [playbackspeed ](https://www.alphatab.net/docs/reference/api/playbackspeed/), but i am getting error:
(index):1145 Uncaught TypeError: api.playbackSpeed is not a function
![image](https://user-images.githubusercontent.com/11175468/121844354-1c616500-ccf9-11eb-8ef5-a72d01987c2c.png)

https://broken-guitar.ir/shop/gole-goldoone-man-notes-tab-simin-ghanem/
to see the tableture click on blue button.
thanks in advance

**Comment by nadia-am** [comment]
@Danielku15 can you please help me with that issue?

**Comment by Reiji777** [comment]
@nadia-am On my end `api.playbackSpeed = 0.5` seems to be working

**Comment by nadia-am** [comment]
@Reiji777 thank you , its working

**Comment by Danielku15** [comment]
For the future, please follow the contributing guidelines. I think we are quire clear about the fact that the usage of the right issue template and place to ask is mandatory. Unless you know exactly that it is a bug, and can fill out the right template, you are better located in the discussions.
