### ISSUE TITLE
Errors in latest master

### ISSUE THREAD

**Issue by Andis59** [CoderLine/alphaTab#63]
I cloned alphaTab, using Git GUI, and compiled. I get a number of errors

Errors:
The type or namespace name 'SharpKit' could not be found (are you missing a using directive or an assembly reference?)	AlphaTab.JavaScript	
The type or namespace name 'Html' does not exist in the namespace 'SharpKit' (are you missing an assembly reference?)	AlphaTab.JavaScript

If I add the reference to the SharpKit.JavaScript.dll the first disapears.
SharpKit.Html doesn't exist in the SharpKit directory.

After searching for a while I found alphaSound and there the SharpKit included SharpKit.Html.dll. Added a reference to this file.

Now I still got this error
The type 'JsContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'SharpKit.JavaScript, Version=1.5.0.0, Culture=neutral, PublicKeyToken=2575297a09c47a96'.

Which seems to indicate that my SharpKit.JavaScript.dll is the wrong version...
In AlphaTab/SharpKit SharpKit.JavaScript.dll  has version 1.0.0.0
in AlphaSound/SharpKit SharpKit.JavaScript.dll  has version 4.30.2000.0

Changed to AlphaSounds SharpKit.JavaScript.dll. Recompiled

I now get an error from the build after event that calls the commando file  CopyAndMinify.bat
Which is calling **uglifyjs**  Which I don't have and don't know how to get or install....

There seems to be a couple of errors in the latest master, or at least a missing document on how to build alphaTab from sources.

**Comment by Danielku15** [comment]
You're right, it seems somehow alphaTab references ther SharpKit DLLs of my local alphaSynth project directory. To install uglifyjs reference the UglifyJS2 repository: https://github.com/mishoo/UglifyJS2
