### ISSUE TITLE
TestPitchesPitches fails

### ISSUE THREAD

**Issue by Andis59** [CoderLine/alphaTab#64]
The last test in **TestPitchesPitches** fails
Assert.AreEqual(1, bar.Voices[0].Beats[0].Notes[0].RealValue);

The RealValue is 31, not 1.

Don't know if it's an error in the test or if the 01a-Pitches-Pitches.xml has changed?

    Test Name:	TestPitchesPitches
    Test FullName:	AlphaTab.Test.Importer.MusicXml2ImporterTest.TestPitchesPitches
    Test Source:	C:\Users\Anders\Documents\Visual Studio    2015\Projects\alphaTab\Source\AlphaTab.Test\Importer\MusicXml2ImporterTest.cs : line 29
    Test Outcome:	Failed
    Test Duration:	0:00:00,1196179

    Result StackTrace:	at AlphaTab.Test.Importer.MusicXml2ImporterTest.TestPitchesPitches() in C:\Users\Anders\Documents\Visual Studio    2015\Projects\alphaTab\Source\AlphaTab.Test\Importer\MusicXml2ImporterTest.cs:line 49
    Result Message:	Assert.AreEqual failed. Expected:<1>. Actual:<31>.

**Comment by Danielku15** [comment]
The MusicXML importer is still in an early development state and the unit tests are not correct yet. I did not officially plan to push the changes to GitHub yet but they were simply part of some other bugfixes.
