### ISSUE TITLE
Playback of the audioworklets version doesn't work in Safari 14.1

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#646]
### Expected Results

Playback works for all devices

### Observed Results

As I am testing the latest audioworklets implementation, the playback function is not working in Safari 14.1 on iPhone or Mac. 
When clicking on the play button, the playback won't occur; instead it returns an error:
> unhandled Promise Rejection: InvalidStateError: No ScriptProcessor was registered with this name

The error is pointing to `alphaTab.js:26188`, which is the following code in the `AlphaSynthAudioWorkletOutput` class
```
this._worklet = new AudioWorkletNode(ctx, 'alphatab');
```

On other devices I have tested so far (Android phone, Safari Preview 15.0 / Chrome on Mac), the playback works with no problem

### Steps to Reproduce

Link to jsFiddle, CodePen, Project etc.: https://jsbin.com/budozuf/

1. Open the link in Safari on iPhone or Mac
2. Click on the play button

### Your environment

**Version**
- [ ] 1.0 
- [ ] 1.1
- [ ] 1.2
- [x] 1.3-alpha.127 

**Flavor**
- [x] JavaScript 
- [ ] .net 

**System**

iPhone X (iOS 14.6); Safari 14.1.1
Macbook (Big Sur 11.4); Safari 14.1.1

**Comment by Danielku15** [comment]
I just quickly looked at the behavior of Safari and it is really strange. It is resolving the promise of addModule, but it does not execute any code of the loaded file resulting in no audio worklet processor being registered. It will likely need a bit longer to dig deeper here and find out why safari is not calling the worklet code.

**Comment by Danielku15** [comment]
Found the issue and was able to fix it. Looks like Safari missed some parts when implementing AudioWorklets and I was able to work around it. Was quite nasty to find because they did not add any proper support for debugging or logging to Safari. All errors are swallowed and no custom logs are displayed. This made it really hard to find out why things are not working.
