### ISSUE TITLE
Last note of the tab is not properly played

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#647]
### Expected Results

All notes should be played properly

### Observed Results

1. If `isLooping = false`, every other playback the last note of the tab is not played
Ref video: https://drive.google.com/file/d/1lWJ_PfS0LyvfvW_Dis8zuGeT-j2GZ3qw/view?usp=sharing
2. If `isLooping = true`, in every repeat when playing the last note of the tab, a weird note rather than the actual one is played
Ref video: https://drive.google.com/file/d/1DXxbJyjaJkxlP6v__q8mwdUL2nCMN8Go/view?usp=sharing

### Steps to Reproduce

Link to jsFiddle, CodePen, Project etc.: 
- isLooping = false: https://output.jsbin.com/budozuf/15
- isLooping = true: https://output.jsbin.com/budozuf/16
1. Open the link
2. Click on play button

### Your environment

**Version**
- [ ] 1.0 
- [ ] 1.1
- [ ] 1.2
- [x] 1.3-alpha.127 

**Flavor**
- [x] JavaScript 
- [ ] .net 

**System**

Model: Samsung SM-A750C
Android version: 10
Browser: Chrome 92.0.4515.131

**Comment by Danielku15** [comment]
I had a look at the provided links and for me it works fine. Unfortunately I cannot test audio on browserstack for mobile devices, they don't support it. 

Can you test this on other devices? TBH: We know already that this phone is for some reason causing various issues with alphaTab. If it works for other devices I would like not to invest too much effort anymore into getting things running and performing well on this model/device.

**Comment by Reiji777** [comment]
@Danielku15 Thanks for the updates. I was testing with the latest build on iOS and another Android device, and I couldn't reproduce the bug. If I could someday reproduce it on more other devices I'll share the info. This particular device is indeed weird.

**Comment by Danielku15** [comment]
@Reiji777 Any new findings here?

**Comment by Reiji777** [comment]
@Danielku15 Hi Daniel not much new findings on this one. Let me close this issue for now, and post another issue when I a solid way to reproduce it.
