### ISSUE TITLE
AlphaTex hammer ons

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#65]
Hammer ons do not display when inputting AlphaTex to the render engine. All other note articulations and beat articulations seem to be rendering properly. Looks like hammer ons display properly when rendering files so this issue is isolated to the case of AlphaTex input.

Minimal working alphatex example:
```
:2 3.4{h} 4.4
```

![hammeronbug](https://cloud.githubusercontent.com/assets/1033190/10181794/b1311fcc-66d9-11e5-8130-2968cca5185d.png)

**Comment by Danielku15** [comment]
I just tested your sample with the latests alphaTab build and it is working as expected: 
http://jsfiddle.net/x9zyfqLq/

**Comment by gburlet** [comment]
I was using the latest stable build. I'll start working off of master branch now :+1:
