### ISSUE TITLE
Setting update becomes laggy

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the latest audioworklets version of AlphaTab, a setting update (e.g. change playback speed/mute tracks or change their volumes) becomes laggy. The update doesn't take effect until several seconds later (usually the delay is one or two bars).

In the previous version (ver 1.2.1), the setting update takes effect immediately.

### Expected Behavior

The setting updates should take effect immediately.

### Steps To Reproduce

1. Open the official website: https://www.alphatab.net/
2. Start playback and apply setting updates such as changing playback speed or track volume

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: macOS Big Sur 11.4
- **Browser**: Chrome 92.0.4515.159

Also reproducible on Chrome 92.0.4515.90 of iOS 14.7.1
```

**Comment by lannka** [comment]
I encountered the same issue here. Thanks @Reiji777 for reporting.

**Comment by Danielku15** [comment]
I fear it could be a side effect of some performance improvements I made. AlphaTab now buffers some more audio data to avoid crackling sounds on poorly performing devices. But this has the side effect that when changing any parameters, they cannot take effect on the already synthesized audio. 

I will need to check how to handle this best. I could drop the already synthesized samples on such changes but this also means indirectly seeking back to the start of the buffered samples.

**Comment by Danielku15** [comment]
I added some improvement which will ensure the buffered audio samples are cleared. You might experience some short audio outages on changing these settings due to the buffer-regeneration which needs to be done.
