### ISSUE TITLE
AlphaTex measure-level tempo changes

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#66]
Parsing measure-level AlphaTex tempo changes in throws an error.

Minimal example:
```
| \tempo 100
```

Error:
```
"19: Error on block measure-effects, invalid value:tempo"
```

**Comment by Danielku15** [comment]
Please try the latest build. I did some tests and fixes to ensure this is working: 
http://jsfiddle.net/sa8d2kr6/
