### ISSUE TITLE
Add support for chord diagrams in MusicXML

### ISSUE THREAD

**Issue by Danielku15** [CoderLine/alphaTab#667]
As reported [here](https://github.com/CoderLine/alphaTab/discussions/665) alphaTab does not support reading the individual frets and strings from the MusicXML harmony definition. We can use the information from the `frame` element to fill up all strings and frets of the chord accordingly:

https://w3c.github.io/musicxml/musicxml-reference/elements/frame/
[demo.xml.txt](https://github.com/CoderLine/alphaTab/files/7315535/demo.xml.txt)

**Comment by coluzziandrea** [comment]
Hello there! 
Is this issue still valid? I'd like to give it a try

**Comment by Danielku15** [comment]
Hey there. Yes the work item is still valid. 😉 Feel free to give it a try. Just reach out here if you need any assistance.
