### ISSUE TITLE
AlphaTex duration

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#67]
In the latest master build, duration ranges work fine but using the syntax ```fret.string.duration``` fails. I was looking through some of my AlphaTex files from 3 or so years ago and this was valid syntax in the [old build](http://demo.alphatab.net/old/notes.html).

This works fine:
```
<div id="alphaTab" data-tex="true">
    :2 3.4 4.4
</div>
```

This renders each note as a quarter note regardless of each note's duration:
```
<div id="alphaTab" data-tex="true">
    3.4.2 4.4.2
</div>
```

**Comment by Danielku15** [comment]
Thanks for the hint. Looks like there was something messed up when I introduced the new :2, :8,.. variant. Should be fixed on the master
