### ISSUE TITLE
Typo in onBeatMouseUp

### ISSUE THREAD

**Issue by KieranKS** [CoderLine/alphaTab#681]
In the block under the comment `//for the selection ensure start < end`

https://github.com/CoderLine/alphaTab/blob/ee308e1197faf67216bedaead607cc6f499abf97/src/AlphaTabApiBase.ts#L1052

I believe this is supposed to be ` let endTick: number = this._selectionEnd.beat.absolutePlaybackStart; `

I was trying to get the start of a selection using the API and it gave me the end when I made the selection in reverse. 
`if (endTick < startTick)` is always false since both are `this._selectionStart!.beat.absolutePlaybackStart;`

**Comment by Danielku15** [comment]
Please follow the issue templates, they are mandatory!
