### ISSUE TITLE
Unable to Use Models in Typescript Project

### ISSUE THREAD

**Issue by kyledecot** [CoderLine/alphaTab#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to use one of the models exported as `model` results in `Cannot find namespace 'model'.ts(2503)`.

### Expected Behavior

No typescript errors.

### Steps To Reproduce

```
import { Service } from "typedi";
import { Settings, importer, model } from "@coderline/alphatab";

@Service()
export class AlphaTabService {
  getScoreByBuffer(buffer: Buffer): model.Score { // Cannot find namespace 'model'.ts(2503)
    const settings = new Settings();

    return importer.ScoreLoader.loadScoreFromBytes(
      new Uint8Array(buffer),
      settings
    );
  }
}
``` 

### Found in Version

1.3-alpha

### Platform

Node.js

### Environment

```markdown
- **OS**: MacOS 12.0.1 (21A559)
- **Browser**: N/A
- **.net Version**: N/A
```

### Anything else?

<img width="823" alt="Screen Shot 2021-11-23 at 9 38 24 AM" src="https://user-images.githubusercontent.com/192464/143044402-6b293bd7-b07f-4a97-92f8-8fd25aeb94eb.png">

**Comment by Danielku15** [comment]
Can you also share your `tsconfig.json`? `model` is indeed no namespace but [an exported object](https://github.com/CoderLine/alphaTab/blob/develop/src/alphatab.ts#L151). I wonder why the import of it can fail.

**Comment by Danielku15** [comment]
I think I found a good way to workaround the previous issues. Give it a try with 1.3.0-alpha.135 and let me know if it works for you.

**Comment by kyledecot** [comment]
👋 Thanks for the quick turnaround on this @Danielku15. I'm currently on vacation but I'll give this a shot when I get back and report back later this week.
