### ISSUE TITLE
alphaTex rest after section tag causes parsing error

### ISSUE THREAD

**Issue by jonaro00** [CoderLine/alphaTab#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting a bar with a rest directly after a symbol-less `\section` tag causes the `r` in the rest to be parsed as the section name, as the `\section` tag reads up to two "names" after it. Although this is the "expected" behavior from the parser, it leads to some confusion when learning the language.

This...
```
1.3.4*4 |
\section Verse
r.1 | 2.3.4*4 |
```
...causes this to be rendered:
![image](https://user-images.githubusercontent.com/54029719/143677808-033e7749-a517-4ff6-88d7-a0ba3caada86.png)

My current workaround is to start the bar with a duration range instead:
```
1.3.4*4 |
\section Verse
:1 r | 2.3.4*4 |
```

### Expected Behavior

The expected behavior from a new user of alphaTex would be for the `r` to be parsed as a rest in the example from above.
![image](https://user-images.githubusercontent.com/54029719/143677987-ab989da4-5439-425a-b43b-88f854ee7978.png)

My suggested solution at this stage would be to disallow section names to be `r`, as it seems very unlikely for someone to legitimately use that. Fixing the "bug" and the confusion it brings is probably worth it. However, there are probably even better solutions to this problem.

### Steps To Reproduce

See above

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10
- **Browser**: Chromium 96
```

**Comment by Danielku15** [comment]
I added some detection to alphaTex. With this change you cannot use just `x` `-` or `r` as section text, but I guess nobody will do that anyhow. 😁
