### ISSUE TITLE
Playback problem of repeats

### ISSUE THREAD

**Issue by mw2c** [CoderLine/alphaTab#69]
Hi, I noticed that the playback doesn't handle repeats and alternate endings properly. the last bar or sometimes the last beat of repeats won't be played, and the player will stop at the end of the first alternate ending.

**Comment by Danielku15** [comment]
Hi. Can you please provide a sample file that shows this issue?

**Comment by mw2c** [comment]
Yes, check this Rondo Alla Turca, it has repeats and alternate endings.
https://www.dropbox.com/s/8efifoyxlwor53w/Rondo_Alla_Turca.gp5?dl=0
