### ISSUE TITLE
Example tab-sheets are positioned wrong in the alphaTex-documentation

### ISSUE THREAD

**Issue by DavidForss** [CoderLine/alphaTab#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just want to let you know that the tab-sheets in the docs for alphaTex is positioned wrong on the page.
Makes it hard to use the docs right now. It looks like an position absolute-issue of some sort.
For example at this page: https://www.alphatab.net/docs/alphatex/bar-metadata

### Expected Behavior

Each example sheet should be under their respective sections, and not all of them positioned on top of each other at the top.

### Steps To Reproduce

Go to: https://www.alphatab.net/docs/alphatex/bar-metadata

### Link to jsFiddle, CodePen, Project

https://www.alphatab.net/docs/alphatex/bar-metadata

### Found in Version

1.1

### Platform

Web

### Environment

```markdown
- **OS**: Mac
- **Browser**: Chrome
- **.net Version**:
```

**Comment by Danielku15** [comment]
Should be fixed with  fbcb236bb226c9b41902e19bfc28a7b8ef268952
