### ISSUE TITLE
Cursor getting ahead of itself

### ISSUE THREAD

**Issue by kyledecot** [CoderLine/alphaTab#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On various songs the cursor will jump ahead of where it should be–it will then jump back to it's expected position and continue on normally for a bit.

https://user-images.githubusercontent.com/192464/152048266-ffb762a4-2c27-4d7e-8cbf-098feb6f2e85.mov

.

### Expected Behavior

No jumpy cursor behavior

### Steps To Reproduce

Unsure of what exactly causes this–some scores will simply behave "normally".

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: MacOS 12.1 (21C52)
- **Browser**: Version 97.0.4692.99
- **.net Version**: N/A
```

**Comment by kyledecot** [comment]
I investigated this a bit further and it appears to be caused by what AlphaTab things is a pull off–if you look in the images below you'll see that AlphaTab has a pull off (to nothing) while GuitarPro does not. 🤔 

AlphaTab

<img width="920" alt="Screen Shot 2022-02-02 at 7 49 48 PM" src="https://user-images.githubusercontent.com/192464/152263024-11717df1-e295-440f-b3e5-619e778b39ce.png">

Guitar Pro

<img width="840" alt="Screen Shot 2022-02-02 at 7 53 33 PM" src="https://user-images.githubusercontent.com/192464/152263009-91d13821-035e-443b-be49-0fe1ce0babdc.png">

**Comment by Danielku15** [comment]
@kyledecot Any more details on this? Can you provide a fiddle and example files? Otherwise I will not be able to investigate this problem.

**Comment by Danielku15** [comment]
Last ping @kyledecot. Otherwise I would close this issue due to inactivity.

**Comment by kyledecot** [comment]
Unfortunately I only ran into this w/ some files that contained copyrighted compositions–as such I cannot post them here. If I'm able to reproduce this in the future w/ a simplified example I will reopen.
