### ISSUE TITLE
AlphaText Importer reports error when Metadata tags are used

### ISSUE THREAD

**Issue by rkenning** [CoderLine/alphaTab#73]
When attempting to parse an AlphaText file via ScoreLoader.LoadScore() or byte array version of the file via ScoreLoader.LoadScoreFromBytes(), an error occurs if Metadata tags are included in the file or byte array.

Example of error : 7:Error on block metaDataTags, invalid value:title
(Note : the specific error differs depending on used MetaTag)

Example file included below (and attached):
[test.txt](https://github.com/CoderLine/alphaTab/files/48504/test.txt)

\title Test
\words test
\music alphaTab
\copyright test
\tempo 200
\instrument 30
\capo 2
\tuning G4 D3 G3 B3 D4 A5
.
0.5.2 1.5.4 3.4.4 | 5.3.8 5.3.8 5.3.8 5.3.8 r.2

**Comment by Danielku15** [comment]
Thanks for this finding. The C# version was not respecting the string/object comparison correctly. I ensured all comparisons are done properly and added a unit test for your example. I pushed a new version.
