### ISSUE TITLE
Setting updates cut out the playback

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On any device regardless its spec, setting updates will always cut out the playback abruptly for a short period of time.

- I know that you mentioned this potential problem in the issue below, but wanna follow up a little bit.
https://github.com/CoderLine/alphaTab/issues/657

- I'm reporting it because this behavior is likely to be obvious (especially when adjusting volumes, which users would often do) **on every device regardless of its spec**, due to the current implementation. It was quite obvious on my Macbook and iPhone, which are supposed to be more than powerful to handle such playback.

### Expected Behavior

Playback shouldn't be cut out abruptly when updating settings

### Steps To Reproduce

1. Open project website alphatab.net
2. play the sample 
3. Adjust volumes of any track, and you will notice the cut out

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: MacOS
- **Browser**: Safari 15.2 (17612.3.6.1.6)

Also can reproduce the issue on iPhone X.
```

### Anything else?

Not sure if below makes sense -- I could imagine two possible approaches to possibly optimize this behavior:

1. Instead of immediately clearing all audio buffers and re-generating the audio, is it possible to still keep playing the old buffers until the new buffer becomes ready? I assume this way there won't be abrupt cut out, and thus the setting update should feel smoother.
2. We expose the buffer size as a setting property, so that users can customize it based on their devices. We set the buffer size of version 1.2.1 as the default value, which has turned out to work for most devices except for those with very poor specs. This way only users with poorly performing devices will experience the delay of the setting updates -- not the best, but I assume it'd be better than impacting all users.

**Comment by Danielku15** [comment]
I added a setting for now which controls the buffering time. I put some thoughts into a more dynamic update/transition between audio buffers with regeneration but the current architecture hardly allows this. As of today synth outputs are not aware of the timestamps of the samples they are requesting or receiving. They are rather dumb sinks with ring buffers. This makes any synchronization with regeneration hard to impossible. 

I would need to think of a bigger architectural redesign if this area. But having a 500ms delay (like now default) should be OK for all users. If we face again issues with crackling noises, we might again rather start from this side.
