### ISSUE TITLE
Missing alternate endings

### ISSUE THREAD

**Issue by Billiam** [CoderLine/alphaTab#76]
When a repeat section has alternate endings that repeat more than three times, alphatab will skip and not render some of them.

Here is an example file with a section that repeats 4 times, with an alternate ending for the last repeat.
AlphaTab will only show `1,2` for the first ending section (rather than `1-3`), and playback will be incorrect (playing bars 1-2-1-2-1-1-3, instead of 1-2-1-2-1-2-1-3).

## Display in Guitar Pro

![guitarpro](https://cloud.githubusercontent.com/assets/242008/12073593/7a6aa330-b0eb-11e5-8660-67748fc8ac00.png)

## Display in alphaTab

![alphatab](https://cloud.githubusercontent.com/assets/242008/12073594/7d434fe4-b0eb-11e5-85d9-64d8a266d1c4.png)

## Source file
[.gpx file zip](https://github.com/CoderLine/alphaTab/files/76148/Repeat.test.zip)

**Comment by Danielku15** [comment]
Thanks for this finding there was a bug in the Guitar Pro 6 file reader. Also there was a minor issue in the alignment of the alternate endings, I also fixed that one.
