### ISSUE TITLE
The color settings in display.resources. are incorrect

### ISSUE THREAD

**Issue by sad-xu** [CoderLine/alphaTab#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to change some color
But the color is not correct even throw Errors

### Expected Behavior

The color is as expected

### Steps To Reproduce

```js
resources: {
  mainGlyphColor: "#f00" // ← This color does not match
  // barNumberColor: "rgb(200,200,200)", // ← This rgb will cause an error
} 
```

### Link to jsFiddle, CodePen, Project

https://codepen.io/sad-xu/pen/RwjyQey

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10
- **Browser**: Chrome 97.0.4692.71
- **.net Version**:
```

**Comment by Danielku15** [comment]
Fixed with [d2f40af](https://github.com/CoderLine/alphaTab/commit/d2f40af6098e62c95be7fe0f34c6fd837e316a41)
