### ISSUE TITLE
JS: Repeats cause mismatch between initial cursor position and playback position.

### ISSUE THREAD

**Issue by Billiam** [CoderLine/alphaTab#77]
In the javascript/html player, if a song has any repeats, the AlphaSynth playback position may be calculated incorrectly when clicking on a bar that appears anywhere after a repeat.

## Reproduction steps

1. Render file containing repeats.
2. Click a bar that appears after a repeat
3. Bar will highlight correctly.
4. Start playback.

The selected bar and playback position will jump to a previous bar and continue playing normally. It seems like, for the purposes of setting the alphasynth position, repeats are ignored (but I can't be sure).

## Test file
[ClickTest.zip](https://github.com/CoderLine/alphaTab/files/76372/ClickTest.zip)

## Example
![clicktest](https://cloud.githubusercontent.com/assets/242008/12075912/056708a4-b158-11e5-9952-44978a7bc770.gif)

**Comment by Danielku15** [comment]
Thanks for this finding. I introduced a new lookup table to find the correct start tick for masterbars.
