### ISSUE TITLE
About add chord display to score

### ISSUE THREAD

**Issue by vivachenx** [CoderLine/alphaTab#802]
Hi there.
Thank you so much for your reply, I just briefly tried adding this feature. I found that if I directly replace the TextGlyph with the ChordDiagramGlyph instance, the rendering is a bit strange.
Then I found another problem, we currently don't seem to support rendering tempo related information
This is alpha result:
![image](https://user-images.githubusercontent.com/12762833/158959660-0d6a8374-4e7e-4c25-985d-5dd54445d044.png)
This is guitar pro result:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/12762833/158960583-131cc9d1-681d-4071-a229-aaf422afa996.png">

_Originally posted by @vivachenx in https://github.com/CoderLine/alphaTab/discussions/703#discussioncomment-2385851_

**Comment by Danielku15** [comment]
Please don't open any issues without following templates. If you want to initate discussions, keep it in the GitHub discussions space. The issues are used for the work item backlog of the project, not for support or discussions.
