### ISSUE TITLE
Play multiple tempos in a masterbar

### ISSUE THREAD

**Issue by hd-i** [CoderLine/alphaTab#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

current behavior is read last tempo of a masterbar and set in tempoAutomation.value

### Expected Behavior

Each tempo must be applied in a masterbar.
GuitarPro Musicsheet for test : Moonlight Sonata ( Piano ver ) , Masterbar 22

### Steps To Reproduce

-----------------

### Link to jsFiddle, CodePen, Project

https://github.com/hd-i/GPFiles

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10
- **Browser**: Firefox,Chrome
```

**Comment by hd-i** [comment]
I uploaded a musicsheet on github to show this to you.
Please see my uploaded musicsheet and open that with guitarpro and see masterbar 22. on this masterbar , there are 4 tempos ( 48, 45, 42, 40)  that guitarpro can handle correctly and it can controls playing speed but alphatab cannot handle all tempos in masterbar 22 and just  playing last tempo of this masterbar.
please see my uploaded guitarpro file in this repository :
https://github.com/hd-i/GPFiles

**Comment by Danielku15** [comment]
Merged from https://github.com/CoderLine/alphaTab/issues/1207

alphaTab currently assumes a single tempo change per master bar but this is not correct. Guitar Pro and many other formats can have multiple tempo changes (and other automations) within a single bar. 

We currently already read the automations correctly into the beats. but for tempo automations which are having an impact on master bar level we only treat one change. 

Related code places: 
https://github.com/CoderLine/alphaTab/blob/develop/src/importer/Gp3To5Importer.ts#L867 (GP3-5 importer)
https://github.com/CoderLine/alphaTab/blob/develop/src/importer/GpifParser.ts#L2328 (Gp6-8 importer)
https://github.com/CoderLine/alphaTab/blob/develop/src/importer/AlphaTexImporter.ts#L1889 (alphaTex importer)
https://github.com/CoderLine/alphaTab/blob/develop/src/model/MasterBar.ts#L111 (data model)
https://github.com/CoderLine/alphaTab/blob/develop/src/midi/MidiFileGenerator.ts#L187 (midi generation)
https://github.com/CoderLine/alphaTab/blob/develop/src/rendering/effects/TempoEffectInfo.ts (rendering)
https://github.com/CoderLine/alphaTab/blob/develop/src/midi/MidiTickLookup.ts#L201 (midi tick)

This change will have significant impact on certain duration calculations.
