### ISSUE TITLE
Aligment problem in multitracks rendering

### ISSUE THREAD

**Issue by eddyfosman** [CoderLine/alphaTab#82]
I have a piano sheet with two hands (each hand is in a track) as the image below

![music_sheet](https://cloud.githubusercontent.com/assets/1407281/14104849/bbd1ef1a-f5d1-11e5-82d1-cf4fa8a694a6.png)

But the second line is not rendered correctly (it's shorter than the first line)

Do you have any suggestion to fix it?

Thank you so much!

**Comment by Danielku15** [comment]
Hello. 
Multitrack rendering is not yet supported. I'm still struggling to find an algorithm that properly aligns the independent beat durations correctly.

**Comment by eddyfosman** [comment]
Thanks for your reply. At the moment, I'm trying to fix this problem with a fake object that created inside Guitar pro, maybe it will work, I hope so.

**Comment by Danielku15** [comment]
My idea was to set the beat width based on a formula that considers the duration whereas the longest beat duration specifies an overall sizing factor to safe space. If this is done right, no alignment between the different tracks is not required. Another idea was to give the overall bar a fixed width and the tick position of the beat is used as X-position within the bar. This would then also properly work for the multi-voice rendering.

**Comment by eddyfosman** [comment]
I tried to edit the code but I have to say that it's not easy (because
there isn't any documentation).
And you added this feature to 1.x.x, so it would be a long time for
this problem. But we need this feature immediately for piano music
sheet rendering with right and left hand.
We also want an another feature is: showing the number of finger of a note.

Therefore we really want to donate to you, so you could focus on
developing these two features for alphaTab as soon as possible. If you
agree, could you determine the amount of money?

Thank you so much!

**Comment by Danielku15** [comment]
I will do some investigations the next days on this feature. the Finger indicator should be an easy task. The multi track rendering was really a long runner where I had struggles with my algorithms. I put it on hold due to other enhancements I was interested into. 

Sorry about not responding via E-Mail. I lately had to struggle a lot with Spam Mails. Since alphaTab became a bit more popular it seems my E-Mail address was picked up by some bots. I'll try to find your mail in my inbox and contact you then.

**Comment by eddyfosman** [comment]
At the moment,I thinh your second solution is completely acceptable, for example: 
http://rockby.net/en/gtp.php?tab=Godsmack/Trippin#multitrack
This guy just uses the same bar width. 

Please contact me at quan.nm@rubycell.com. 
Thank you!
