### ISSUE TITLE
alphata.net example appears to be blank while playing on ipadOS

### ISSUE THREAD

**Issue by WindBise** [CoderLine/alphaTab#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![IMG_0073](https://user-images.githubusercontent.com/34051534/165662244-87519cda-7c6a-421c-bbc9-6d4793a25fdb.PNG)

### Expected Behavior

tab should be rendered correctly

### Steps To Reproduce

1. open ipad
2. open safari
3. navigate to url alphatab.net
4. play the example "canon rock"

### Found in Version

1.2

### Platform

Other

### Environment

```markdown
- **OS**:
ipad pro with ipados 14.0.1
- **Browser**:
safari
- **.net Version**:
1.2 stable
```

**Comment by Danielku15** [comment]
I just tested with iPad Pro 12.9 2021 having iPadOS 14 and it works fine:
![image](https://user-images.githubusercontent.com/674916/166719506-4feacc71-a7c6-4e1c-9663-04c9e426fc86.png)

I also tested with iPad Pro 12.9 2020 having iPadOS 14 and it also works fine:
![image](https://user-images.githubusercontent.com/674916/166720024-c3fdc78c-1221-47a3-ba0b-375eb0393e96.png)

But I noticed on the 2020 device some browser errors: 
![image](https://user-images.githubusercontent.com/674916/166719861-cb217465-dd04-44fa-9f21-f9ca7ec2e296.png)

Not sure if the error is related but it could be. I could not reproduce the visual error that you are describing with these steps. Did you maybe do something else additionally?

**Comment by WindBise** [comment]
> I just tested with iPad Pro 12.9 2021 having iPadOS 14 and it works fine: ![image](https://user-images.githubusercontent.com/674916/166719506-4feacc71-a7c6-4e1c-9663-04c9e426fc86.png)
> 
> I also tested with iPad Pro 12.9 2020 having iPadOS 14 and it also works fine: ![image](https://user-images.githubusercontent.com/674916/166720024-c3fdc78c-1221-47a3-ba0b-375eb0393e96.png)
> 
> But I noticed on the 2020 device some browser errors: ![image](https://user-images.githubusercontent.com/674916/166719861-cb217465-dd04-44fa-9f21-f9ca7ec2e296.png)
> 
> Not sure if the error is related but it could be. I could not reproduce the visual error that you are describing with these steps. Did you maybe do something else additionally?

Yes, i use my ipad to connect my mbp and i found this error too.
<img width="1023" alt="截屏2022-05-06 下午12 37 24" src="https://user-images.githubusercontent.com/34051534/167068104-8b06ea52-18c6-4b49-8a1a-37eae56dcf33.png">

**Comment by WindBise** [comment]
when the tick go down to next row of the tab, and if the row is invisible the same error will appear, if the row is visible, the error will not appear.

**Comment by WindBise** [comment]
Additionally, my ipad is 2018 ipad pro 11 inch
