### ISSUE TITLE
CSS highlighted area slowly moves out of position

### ISSUE THREAD

**Issue by ShredDead** [CoderLine/alphaTab#85]
During the playback of a file that has 189 measures I noticed that the CSS highlighted areas slowly moved its way out of position. This can be seen in the following screenshots. Within time of a much longer arrangement this will not even be highlighting the played measure or note.

![alphatab5](https://cloud.githubusercontent.com/assets/18369457/14407450/0c1c9a72-fe8f-11e5-8dce-a5e0773ef6cc.jpg)
![alphatab6](https://cloud.githubusercontent.com/assets/18369457/14407449/0c1c97a2-fe8f-11e5-980e-851121132224.jpg)

**Comment by Danielku15** [comment]
Thanks for this finding. Looks like I missed one of the small spacings for the calculation of the cursor area.
