### ISSUE TITLE
#-sign on wrong  bass clef line in a G major scale

### ISSUE THREAD

**Issue by solveit68** [CoderLine/alphaTab#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my WPF application the # sign is displayed in the bass clef on the G line instead of the F line in a G major scale.
<img width="475" alt="Screenshot 2022-05-24 165914" src="https://user-images.githubusercontent.com/106169352/170068041-f88a8b70-cb79-497c-a0a7-364c78bc7220.png">

### Expected Behavior

The # sign should be on the F line also in the bass clef.

Perhaps this issue could be solved by changing the value of 2 to 3 for the Clef.F4 in the CreateKeySignatureGlyphs method.

### Steps To Reproduce

Use a treble and bass clef with a G major scale at the same time with WPF.

### Found in Version

1.2

### Platform

.net (WPF)

### Environment

```markdown
- Windows 11
- Chrome
- .NET6
```

**Comment by Danielku15** [comment]
Can you provide the file you are using? It is crucial for reproducing.

**Comment by solveit68** [comment]
Sorry, but there is no song file. I've developed a simple chord trainig program.

By this I've created the clefs by a function like the function below and then added some chord notes thats all.


        public static (Score Score, Voice TrebleBeat, Voice BassBeat) CreateChordScore(KeySignature keySignature = KeySignature.C, KeySignatureType keySignatureType = KeySignatureType.Major, double tempo = 120)
        {
            var trebleStaff = new Staff();
            var trebleBar = new Bar { Clef = Clef.G2 };
            var trebleVoice = new Voice();

            trebleStaff.AddBar(trebleBar);
            trebleBar.AddVoice(trebleVoice);

            var bassStaff = new Staff();
            var bassBar = new Bar { Clef = Clef.F4 };
            var bassVoice = new Voice();

            bassStaff.AddBar(bassBar);
            bassBar.AddVoice(bassVoice);

            var track = new Track();
            track.AddStaff(trebleStaff);
            track.AddStaff(bassStaff);

            var score = new Score { Tempo = tempo };
            var masterBar = new MasterBar { KeySignatureType = keySignatureType, KeySignature = keySignature };
            score.AddMasterBar(masterBar);
            score.AddTrack(track);

            return (score, trebleVoice, bassVoice);
        }

**Comment by Danielku15** [comment]
Can you please create a full fiddle/example project showing the problem. It is quite cumbersome to stich together problems from individual snippets. Also in your code you are missing definitely a call to [`score.Finish()`](https://alphatab.net/docs/reference/score#:~:text=The%20score%20provides%20a%20finish%20method%20which%20consolidates%20many%20aspects%20of%20the%20data%20model%20like%20resolving%20tied%20notes%2C%20calculating%20times%20and%20linking%20elements.)

**Comment by solveit68** [comment]
Hello Daniel,
in my real code there is already a score.Finish() but that doesn't make any difference,
Enclosed is a sample code as originally requested.
Thank you.
[WpfApp1.zip](https://github.com/CoderLine/alphaTab/files/8791513/WpfApp1.zip)
