### ISSUE TITLE
Circular dependency between chunks with runtime

### ISSUE THREAD

**Issue by kyledecot** [CoderLine/alphaTab#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the latest alpha release (`1.3.0-alpha.278`) in a web based project that also uses webpack (`5.72.1`) you will see the following warning in the console:

```
Circular dependency between chunks with runtime (alphatab.worker, webpack)
This prevents using hashes of each other and should be avoided.
```

### Expected Behavior

Webpack should emit no warnings.

### Steps To Reproduce

1. Create a new React Project
2. Integrate Latest AlphaTab Package (1.3 Alpha)
3. Start server
4. View warning in browser

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: MacOS 12.4 (21F79)
- **Browser**: Chrome Version 101.0.4951.64 (Official Build) (arm64)
- **.net Version**: N/A
```

### Anything else?

<img width="936" alt="Screen Shot 2022-05-25 at 10 48 29 AM" src="https://user-images.githubusercontent.com/192464/170291508-7373f234-4be8-4282-8bfb-487b14cb95bb.png">

**Comment by Danielku15** [comment]
Nothing to fix and no bug. alphaTab by-design points to itself to spawn background workers. It's rather a design flaw in WebPack that they do not have proper WebWorker and AudioWorklet support where a script spawns itself. 

Also without any code as example it is not possible to give maybe advises .
