### ISSUE TITLE
Unsure of where editable variables are located

### ISSUE THREAD

**Issue by ShredDead** [CoderLine/alphaTab#88]
How does one change the width of the layout without editing the scale of it? I'm trying to use this within Joomla and the overall MAX width of the blog is 900px

**Comment by Danielku15** [comment]
Check the `Page Layout (custom width)` example: http://demo.alphatab.net/features.html#layouts
You can pass the desired with when initializing alphaTab.

**Comment by Danielku15** [comment]
Did the setting work for you or do you still have troubles on setting the width?

**Comment by ShredDead** [comment]
I'm still having problems. Your demo shows the options but not how to do it.

**Comment by Danielku15** [comment]
I am not sure if I understand you correctly. The source code of the sample clearly shows what setting to use: 
https://github.com/CoderLine/alphaTab/blob/master/Samples/JavaScript/features.html#L181
```js
<script type="text/javascript">
    $('#alphaTabPageLayoutWidth').alphaTab({
        layout: {
            mode: 'page',
            additionalSettings: {
                autoSize: false
            }
        },         
        width: 1280
    });
</script>
```
 
AlphaTab is not capable of dynamically resizing the score (responsive layout) if you are asking for that.

**Comment by Danielku15** [comment]
I changed the behavior a bit to make it more simple to set the expected width. I completely removed the separate autoSize setting and always use the width specified. 

https://github.com/CoderLine/alphaTab/blob/master/Samples/JavaScript/features.html#L181

```js
<script type="text/javascript">
    $('#alphaTabPageLayoutWidth').alphaTab({
        width: 1280
    });
</script>
```

**Comment by ShredDead** [comment]
Daniel,

Thank you for taking the time with me. I will work on this today. Also, did
you get my donation?

Chad

**Comment by Danielku15** [comment]
Yes, I received your donation. Thanks a lot, I'll have a beer on you ;)

**Comment by Danielku15** [comment]
New documentation is in progress. In the meanwhile also the problems of this issue have been improved: 

* AlphaTab is responsive now, automatic sizing is enabled by default. 
* AlphaSynth initialization is also a lot easier now.
