### ISSUE TITLE
Top overflowed with bend

### ISSUE THREAD

**Issue by ChiHoc** [CoderLine/alphaTab#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when setting RenderStaff topSpacing = 0, top overflowed with bend
![image](https://user-images.githubusercontent.com/4478983/174708963-b5c0c7c3-4b69-40b6-9f98-4f2b88413ce7.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/4478983/174709035-adbeefa2-8db0-41b5-9e27-8aace9ac2868.png)

### Steps To Reproduce

1. Set RenderStaff topSpacing = 0
2. Render gp with bend

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: macOS 12.1
- **Browser**: Chrome 102.0.5005.115
```

**Comment by Danielku15** [comment]
For future bug reports, please try to explain a bit more about what exactly is not working and why.

**Comment by Danielku15** [comment]
I looked at this topic again and consider it not a bug. The `RenderStaff topSpacing` is not a setting which can be modified from the outside hence you are causing this bug by this step.
