### ISSUE TITLE
when beat is Duration.half  Looks too narrow ，How to make it longer

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#913]
now is:
 
 
![1](https://user-images.githubusercontent.com/17884664/175757531-f2f54a9a-0643-4794-ad6e-47f00a96732a.png)

I hope Like this

![2](https://user-images.githubusercontent.com/17884664/175614957-e67f1930-16da-4b8d-8e39-5f61f15fe137.png)

I noticed this code I add （Red frame part）:src\rendering\glyphs\BeatContainerGlyph.ts
 
![3](https://user-images.githubusercontent.com/17884664/175527029-414bee9d-85f6-4ead-9e2f-b1cb0b27d722.png)

 but No effect ，I don't know why！

**Comment by Danielku15** [comment]
Issues are not for asking questions. Please [open a discussion](https://github.com/CoderLine/alphaTab/discussions)
