### ISSUE TITLE
Beat RemoveNote function not working correctly

### ISSUE THREAD

**Issue by gallegretti** [CoderLine/alphaTab#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when calling the `removeNote` function from a Beat, the `noteStringLookup` is not correctly updated: The reference is not removed from the map, which can causes other methods like `getNoteOnString` and `hasNoteOnString` to return incorrect values.

### Expected Behavior

The `removeNote` function should remove the note from the `noteStringLookup` reference.

### Steps To Reproduce

1. Load a score
2. Use `removeNote` in a beat with a valid note
3. Use `getNoteOnString` with the string of the previous note.
4. The return should be `null` but still is the removed note

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10 Pro
- **Browser**: Chrome 103.0.5060.134
```

**Comment by Danielku15** [comment]
Thanks for pointing this out. This method mainly serves some internal infrastructure in alphaTab and we likely do not run into this issue. But it it is obviously a missing behavior there which should be fixed.
