### ISSUE TITLE
TabBrushGlyph have  Bug: when 6str Note  heighter than 5str     Will happen

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the erro like:
![未命名-3](https://user-images.githubusercontent.com/17884664/181739163-43d54bec-ef6c-4f24-958e-567ced308b25.png)

### Expected Behavior

The right one should be like this
 
![未命名-5](https://user-images.githubusercontent.com/17884664/181748593-11b9c7ee-a512-49f5-b2f9-08f12e16668b.png)

### Steps To Reproduce

the err file here 
[sb.zip](https://github.com/CoderLine/alphaTab/files/9219142/sb.zip)

### Found in Version

1.2

### Platform

Node.js

### Environment

```markdown
- **Browser**:chrome
```

### Anything else?

I found 
TabBrushGlyph.ts  on 24 line begin  may be wrong:
-----------------------------------------
      let startY: number =
            cy + this.x + (tabBarRenderer.getNoteY(this._beat.maxNote!, NoteYPosition.Top));
        let endY: number =
            cy + this.y + tabBarRenderer.getNoteY(this._beat.minNote!, NoteYPosition.Bottom);
  -------------------------------------------------------
 this._beat.maxNote! and  this._beat.minNote! is erro      Should be changed to     
 
 ---------------
 this._beat.maxStringNote! and  this._beat.minStringNote!
 
 --------------------   
 
 Complete code：

-------------------------------------------

      let startY: number =
            cy + this.x + (tabBarRenderer.getNoteY(this._beat.maxNote!, NoteYPosition.Top));
        let endY: number =
            cy + this.y + tabBarRenderer.getNoteY(this._beat.minStringNote!, NoteYPosition.Bottom);

-----------------------------------------------

**Comment by Danielku15** [comment]
Your findings were pointing in the right direction, we have to choose the notes for brushes based on the highest/lowest string, not the note height. Especially on tunings like ukulele it can easily be that a higher string is a lower note resulting in wrong brush strokes.
