### ISSUE TITLE
Adding position numbers in AlphaText for classical guitar

### ISSUE THREAD

**Issue by cjrobe** [CoderLine/alphaTab#945]
AlphaTab and AlphaTex are so dang cool. I'm using it for a classical guitar project and am hiding the tablature. Normally in classical guitar, you signify position by putting a roman numeral above the note - even if I could put arbitrary text above a note using AlphaTex, that would fulfill my needs. See image attached for example.

[chrome_FhaxazhEBm](https://user-images.githubusercontent.com/5606066/185807489-21e96560-ec11-4034-94d8-9f9b1c686581.png)

Thank you!

**Comment by Danielku15** [comment]
Please do not use issues for discussing topics. That's what the Discussions tab is for. 
https://github.com/CoderLine/alphaTab/blob/develop/CONTRIBUTING.md#discussions-vs-issues
