### ISSUE TITLE
Key signature problem

### ISSUE THREAD

**Issue by eddyfosman** [CoderLine/alphaTab#95]
Hi, I've came across a problem with key signature, the first two notes are not rendered correctly.

In GP

![key_e_gp](https://cloud.githubusercontent.com/assets/1407281/16104870/22a7c5fa-33af-11e6-8d74-314e10dea747.png)

In AlphaTab
![key_e_at](https://cloud.githubusercontent.com/assets/1407281/16104876/2c562f06-33af-11e6-9023-ca55a179d3de.png)

Here is the .gpx file

[kiss_the_rain_guitar.zip](https://github.com/CoderLine/alphaTab/files/317622/kiss_the_rain_guitar.zip)

And the natural signs are repeated in a unnecessary way.
Please help me solve this problem.

Best regards.

**Comment by Danielku15** [comment]
The old accidental calculation had quite some issues, I reworked it in commit 0dbe21bc4c1908c8c478857c901ac52fc9c1f65a
