### ISSUE TITLE
Cursor and its elements get displaced incrementally upon continuous scrolling

### ISSUE THREAD

**Issue by mxAlexG** [CoderLine/alphaTab#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
This happens in different browsers and not only chrome. The cursor and the highlight selection elements get displaced (offset) by a positive value the more your scroll down.

![image](https://user-images.githubusercontent.com/105655048/187023609-642fd1c0-c001-4a52-9c7b-7503f9d6ab00.png)

However, when this happens, if you perform a render operation or anything that seemingly calls it, the cursor reverts back to its proper position.

### Expected Behavior

Cursor should always stay in place.

### Steps To Reproduce

1. open a long piece (above ~100 bars) of any kind (single or grand staff)
2. scroll to the middle or beyond of the view

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **Multiple**:
- **Multiple**:
```

**Comment by Danielku15** [comment]
Please try to fully provide all information requested in the issue template. Your steps to reproduce do not really allow me to reproduce this issue on my side and there is no description about the environment you are using. I want to be able to focus on solving the problem, not investing too much time in even reproducing it. 

I only have seen this issue when in the browser you manually have zoomed to a zoom beside 100%. This is a known issue to me and rather a bug in Chrome that somehow the absolute layouting combined with zooming is done wrong. 

100% Zoom:
![image](https://user-images.githubusercontent.com/674916/187024993-8b687542-1478-427f-937d-3ea065db6111.png)

75% Zoom: 
![image](https://user-images.githubusercontent.com/674916/187025000-c01514bb-bf5b-4a7d-ac1f-72bf21f1da2c.png)

**Comment by mxAlexG** [comment]
HI,
This happens at zoom level 100% in both the browser and the player. I am using the tutorial example with no alteration to demonstrate the issues I encounter and not something from my project. This is to ensure that it's not something caused by anything I've done inadvertently. Hope this screen capture shows it clearly. 
[Screencast from 08-27-2022 01:19:47 PM.webm](https://user-images.githubusercontent.com/105655048/187026084-c4bbd05e-1332-4792-8363-952b4cb9ad35.webm)

Thanks for the response.

**Comment by mxAlexG** [comment]
This is also after turning off all the extensions
![image](https://user-images.githubusercontent.com/105655048/187026174-5bb12b13-1ef1-46f6-aff8-7ef616290c43.png)

**Comment by Danielku15** [comment]
I was able to reproduce this issue locally. It is indeed very weird. It does not seem to be fully consistent. Some bars suffer of misalignment, while others are then again correct. 

The problem seems to be solved already in 1.3 thanks to the new absolute positioning of all sub-partials rendered. Very likely in 1.2 some paddings/margins were not taking into account. 

Version 1.2.2:
![image](https://user-images.githubusercontent.com/674916/187027413-c31506fd-53b2-4f62-9ee9-953063cb5d47.png)

Version 1.3:
![image](https://user-images.githubusercontent.com/674916/187027416-1f2de6c8-019f-4b7b-9c6d-a1280b2b8946.png)

**Comment by Danielku15** [comment]
I will close the bug as this issue does not appear in 1.3 anymore. I will try to ship also a fix for 1.2.3.
