### ISSUE TITLE
KeySignatureType from .gpx

### ISSUE THREAD

**Issue by eddyfosman** [CoderLine/alphaTab#97]
I need to this information from .gpx, I found its definition in the code: 

AlphaTab.Model.KeySignatureType = {
    Major: 0,
    Minor: 1
};

But unfortunately, it hasn't been implemented anywhere. Please help me.

**Comment by Danielku15** [comment]
yes this info is currently missing from the file readers. I did some basic tests with Guitar Pro and also did some reading and could not see any difference in the rendering or in the playback so far. It should be easy to add the key signature type to the data model but I have to do some further reading on how this affects the music notation. Do you expect some special behavior/display as part of the key signature types?

**Comment by eddyfosman** [comment]
Thank you so much. At the moment, I just need to display this information when transposing, just major or minor.

**Comment by Danielku15** [comment]
Key signature types are now properly part of the data model and read for Guitar Pro files.
