### ISSUE TITLE
Another problem with character encoding

### ISSUE THREAD

**Issue by MrDrone-ru** [CoderLine/alphaTab#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you load a .gp5 file containing Cyrillic into the player, these characters are displayed incorrectly (in the form of question marks inside diamonds).

### Expected Behavior

Correct display of characters.

### Steps To Reproduce

1. Load any .gp5 file containing Cyrillic into the AT web player, for example this one mealntabs.ru/gpt/dark_soul_mod.gp5
2. You will see Ҹ���� ���� in the title and track names
3. Profit!

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
OS: Windows 10 Pro
Browser: Chrome 92.0.4515.159 Opera 89.0.4447.83
I think, this bug is browser independent.
```

### Anything else?

Cyrillic characters in .gp format are displayed correctly.

**Comment by Danielku15** [comment]
Guitar Pro 5 only contained ANSI Strings and no info about the right character encoding. AlphaTab tries to decode in UTF8 by default. In such cases where you have different encodings specify the right one through https://alphatab.net/docs/reference/settings/importer/encoding/ (internally https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder will be used to convert the raw bytes to a string).
