### ISSUE TITLE
api.tex("\title 'Test' . 3.3.4") error

### ISSUE THREAD

**Issue by 798714773** [CoderLine/alphaTab#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

var api = new alphaTab.AlphaTabApi(document.querySelector('#alphaTab'));
api.tex("\title 'Test' . 3.3.4");

[AlphaTab][AlphaTex] MalFormed AlphaTex: @6: Error on block note-fret, expected a Number found a String: 'null'

### Expected Behavior

show

### Steps To Reproduce

var api = new alphaTab.AlphaTabApi(document.querySelector('#alphaTab'));
api.tex("\title 'Test' . 3.3.4");

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**:
- **Browser**:
- **.net Version**:
```

**Comment by Danielku15** [comment]
You need to escape the backslashes. If you write `"\title"` this is a tab character followed by  `itle`and not a raw
`\title` text.

**Comment by 798714773** [comment]
I want to know why I don't use / or other symbols. I think it will cause trouble. What are the advantages of using \?

**Comment by Danielku15** [comment]
It is mainly aligned with/inspirer by markup languages like LaTeX and lilypond. Hence also the name alphaTex. From parsing perspective it is also a bit more straightforward to use distinctive characters for different elements. i am currently on holidays abroad but when I am back home I could check if there would be any negative implications allowing also slashes beside backslashes.
