### ISSUE TITLE
Slur signature is not rendered correctly

### ISSUE THREAD

**Issue by eddyfosman** [CoderLine/alphaTab#98]
In seventh bar of our .gpx, there is a problem with the slur signature:
AlphaTab

![slur1](https://cloud.githubusercontent.com/assets/1407281/16681377/840950a4-451e-11e6-80a8-e79918cbb3f7.png)

GuitarPro

![slur2](https://cloud.githubusercontent.com/assets/1407281/16681382/89cad1e8-451e-11e6-8280-1287d64377e4.png)

Here is the .gpx file (in E major)
[kiss_the_rain_guitar.zip](https://github.com/CoderLine/alphaTab/files/353757/kiss_the_rain_guitar.zip)

Please help me, and thank you for your great work.
Best reards.

**Comment by Danielku15** [comment]
I just pushed a very new version of alphaTab to the repostiory. There the tie is aligned properly.
