### ISSUE TITLE
Could not load font 'Georgia'

### ISSUE THREAD

**Issue by ljfreelancer88** [CoderLine/alphaTab#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried the existing code on the documentation but I got the following error below. And in the browser it renders the `Music sheet is loading`.

`alphaTab.min.js:17 [AlphaTab][Rendering] Could not load font 'Georgia' within 5 seconds null`

### Expected Behavior

I would be able to view the notation from GP extension used in the documentation.

### Steps To Reproduce

Just copy the code here `https://www.alphatab.net/docs/tutorial-web/player`

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**:
Ubuntu
- **Browser**:
Chrome
- **.net Version**:
```

**Comment by Danielku15** [comment]
Please actually search for existing issues before kust checking the checkbox in the template.
https://github.com/CoderLine/alphaTab/issues/546

**Comment by hhly** [comment]
How to solve Chinese garbled characters

**Comment by hhly** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/29226405/191897091-0208da31-9910-4ff8-b071-1d9182313457.png">

**Comment by Danielku15** [comment]
@hhly Please do not hijack the issues of others for your questions.
