### ISSUE TITLE
don't support chinease display

### ISSUE THREAD

**Issue by tongliangcui** [CoderLine/alphaTab#99]
can not read chinease text   in the gtp file correctly,such as title property.

**Comment by Danielku15** [comment]
Can you please provide example files where you are experiencing the issues with?

**Comment by zhangchn** [comment]
This is probably a design flaw for GTP file format (up to version 5) where textual string encodings are not explicitly defined.

**Comment by tongliangcui** [comment]
certainly, how can i send to u? my email address is tongliangcui@163.com,  can u send sth to me,then i will reply to u.

**Comment by tongliangcui** [comment]
i found that  the chinese  character  in this gb5 file  encoded with gb2312 not unicode.    the decode method AlphaTab.Platform.Std.ToString use unicode  to decode,

**Comment by yaras6** [comment]
Here is example for Polish encoding. Would be great if you could fix it.
https://tabs.ultimate-guitar.com/p/perfect/niepokonani_guitar_pro.htm

**Comment by yaras6** [comment]
In track names "ó" is not correctly displayed

**Comment by MetalLee** [comment]
I think the reason why Chinese characters cannot be displayed correctly is that GP files are encoded with GBK. After I edit the ReadString method , I finally fix my display problems in my own web site:

`ReadString: function (length){
        var b = new Uint8Array(length);
        this.Data.Read(b, 0, b.length);
        var gbkDecoder = new TextDecoder('gbk');
        console.log(gbkDecoder.decode(b));
        //return AlphaTab.Platform.Std.ToString(b);
        return gbkDecoder.decode(b)
}` 

However, I don't think my solution would work when reading GP files encoded with other charset. Maybe we have to figure out a better solution to this problem, which enable us to read files encoded with any charsets.

**Comment by RicardoCao-Biker** [comment]
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: HTML5
* Browser Name and Version: Chrome
* Operating System and version desktop

# Expected Results

I want alphaTab could display Chinese correct

# Observed Results

when I trying to render a  .gp5 file with chinese ,title and text display wrong.

![qq 20180427171925](https://user-images.githubusercontent.com/29997411/39355222-2add8f86-4a3f-11e8-97fd-2f5efc2792f1.png)


# Possible Solution 
I tried the solution at #99 commented by MetalLee like 
`ReadString: function (length){ var b = new Uint8Array(length); this.Data.Read(b, 0, b.length); var gbkDecoder = new TextDecoder('gbk'); console.log(gbkDecoder.decode(b)); return gbkDecoder.decode(b) }`
but it doesn't works.

**Comment by Danielku15** [comment]
I added now a setting where the text encoding can be specified. 

Either via data attribute: 
```html
<div id="alphaTab" data-file="files/Perfect (Poland) - Niepokonani.gp3" data-importer-encoding="iso-8859-2"></div>
```

Or via settings object: 
```javascript
$('#alphaTab').alphaTab({
	importer: {
		"encoding": "iso-8859-2"
	}
}); 
```

By default utf-8 is used.
