### ISSUE TITLE
[AlphaTab][API] An unexpected error occurred TypeError: right-hand side of 'in' should be an object, got undefined

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#999]
Hi,

I am not sure if this is how to submit a bug, however in relation to the aforementioned issue, my specs:

OS. Windows 10
Browser: Firefox
AlphaTab version: alphaTab v1.3.0-alpha.411 (develop, build 411)
Example: https://www.emotive.productions/notation/love-and-fear/player/

The same issue occurs on Chrome, however the first time the page is opened there is no sound but on a subsequent refresh or navigation, the file plays but with the same error.

In each case, there is no rendering of notation either.

Thank you

**Comment by Danielku15** [comment]
https://github.com/CoderLine/alphaTab/blob/develop/CONTRIBUTING.md#when-entering-an-issue
